// Main PDF Report Component - Scannable table format

import { Document, Page, Text, View } from '@react-pdf/renderer';
import { PropertyContext, ProvisionForPDF, ReportMetadata } from '@/lib/pdf/types';
import { groupProvisionsByTopic, generateReportId } from '@/lib/pdf/formatProvisions';
import { CoverPage } from './CoverPage';
import { ContextSection } from './ContextSection';
import { ProvisionTable } from './ProvisionTable';
import { TableOfContents } from './TableOfContents';
import { styles } from './styles';

interface ProvisionReportProps {
  provisions: ProvisionForPDF[];
  property: PropertyContext;
  totalProvisions?: number; // Total provisions for this property (unfiltered)
  activeFilters?: string[]; // Active filter labels
  includeNonActionable?: boolean; // Whether to include non-actionable provisions (default: true)
  isSeeMode?: boolean; // Whether to render as Draft SEE document
  devType?: string; // Development type for SEE mode
}

export function ProvisionReport({
  provisions,
  property,
  totalProvisions,
  activeFilters = [],
  includeNonActionable = true,
  isSeeMode = false,
  devType,
}: ProvisionReportProps) {
  // Group provisions by topic (optionally filter non-actionable)
  const groups = groupProvisionsByTopic(provisions, { includeNonActionable });

  // Generate report metadata
  const reportDate = new Date().toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const metadata: ReportMetadata = {
    reportDate,
    reportId: generateReportId(
      property.former_council,
      property.zone,
      property.heritage_status.in_hca,
      provisions.length,
      new Date()
    ),
    totalProvisions: provisions.length,
  };

  return (
    <Document>
      {/* Context Section - LEP/SEPP/Pathway with Header */}
      <Page size="A4" style={styles.page}>
        {/* Compact Cover Header */}
        <CoverPage property={property} groups={groups} metadata={metadata} />

        {isSeeMode && (
          <View style={{ marginTop: 8, padding: 10, backgroundColor: '#fefce8', borderLeft: '3pt solid #f59e0b', marginBottom: 8 }}>
            <Text style={{ fontSize: 9, color: '#92400e', fontFamily: 'Helvetica-Bold' }}>
              DRAFT — for review by qualified planning consultant before submission
            </Text>
          </View>
        )}

        {isSeeMode && devType && (
          <View style={{ marginBottom: 8 }}>
            <Text style={{ fontSize: 9, color: '#4b5563' }}>Development Type: <Text style={{ fontFamily: 'Helvetica-Bold', color: '#1f2937' }}>{devType}</Text></Text>
          </View>
        )}

        {/* Context Content */}
        <ContextSection
          property={property}
          exportedCount={provisions.length}
          totalCount={totalProvisions || provisions.length}
          activeFilters={activeFilters}
          isEmbedded={true}
        />
      </Page>

      {/* Table of Contents - only when >30 provisions */}
      {provisions.length > 30 && (
        <TableOfContents groups={groups} />
      )}

      {/* DCP Provisions - Continuous Flow */}
      <Page size="A4" style={styles.page} wrap>
        <Text style={{ fontSize: 16, fontWeight: 'bold', marginBottom: 8, marginTop: 0, color: '#1f2937' }}>
          {isSeeMode ? 'Draft Statement of Environmental Effects' : 'DCP Provisions Schedule'}
        </Text>

        {/* All provision tables flow continuously */}
        {groups.map((group, idx) => (
          <ProvisionTable
            key={group.topic}
            group={group}
            sectionNumber={idx + 1}
            isFirst={idx === 0}
          />
        ))}

        {/* FOOTER COMPLETELY DISABLED - position:absolute causes coordinate overflow */}
      </Page>

      {/* Report Metadata - Final Page */}
      <Page size="A4" style={styles.page}>
        <View style={{ marginTop: 100, padding: 20 }}>
          <Text style={{ fontSize: 12, fontWeight: 'bold', marginBottom: 16, color: '#1f2937' }}>
            Report Information
          </Text>
          <View style={{ marginBottom: 8 }}>
            <Text style={{ fontSize: 9, color: '#6b7280' }}>Report Date:</Text>
            <Text style={{ fontSize: 10, color: '#1f2937', marginTop: 2 }}>{metadata.reportDate}</Text>
          </View>
          <View style={{ marginBottom: 8 }}>
            <Text style={{ fontSize: 9, color: '#6b7280' }}>Report ID:</Text>
            <Text style={{ fontSize: 10, color: '#1f2937', marginTop: 2 }}>{metadata.reportId}</Text>
          </View>
          <View style={{ marginTop: 20, paddingTop: 12, borderTop: '1pt solid #e5e7eb' }}>
            <Text style={{ fontSize: 9, color: '#6b7280' }}>Generated by PlotDetect</Text>
            <Text style={{ fontSize: 10, color: '#0f766e', marginTop: 4, textDecoration: 'underline' }}>
              verify.plotdetect.com.au
            </Text>
          </View>

          {/* Legal Disclaimer */}
          <View style={{ marginTop: 24, paddingTop: 12, borderTop: '1pt solid #f59e0b', backgroundColor: '#fefce8', padding: 12, borderRadius: 4 }}>
            <Text style={{ fontSize: 8, color: '#92400e', marginBottom: 4, fontFamily: 'Helvetica-Bold' }}>
              Important Legal Disclaimer
            </Text>
            <Text style={{ fontSize: 7, color: '#78350f', lineHeight: 1.4 }}>
              PlotDetect presents DCP, LEP and SEPP provisions as published by relevant authorities. It does not constitute planning advice. Users should verify provisions against current council instruments and seek professional advice for development applications.
            </Text>
          </View>
        </View>
      </Page>
    </Document>
  );
}
