// Main PDF Report Component - Scannable table format

import { Document, Page, Text, View } from '@react-pdf/renderer';
import { PropertyContext, ProvisionForPDF, ReportMetadata } from '@/lib/pdf/types';
import { groupProvisionsByTopic, generateReportId } from '@/lib/pdf/formatProvisions';
import { CoverPage } from './CoverPage';
import { ContextSection } from './ContextSection';
import { ProvisionTable } from './ProvisionTable';
import { styles } from './styles';

interface ProvisionReportProps {
  provisions: ProvisionForPDF[];
  property: PropertyContext;
  totalProvisions?: number; // Total provisions for this property (unfiltered)
  activeFilters?: string[]; // Active filter labels
}

export function ProvisionReport({
  provisions,
  property,
  totalProvisions,
  activeFilters = []
}: ProvisionReportProps) {
  // Group provisions by topic
  const groups = groupProvisionsByTopic(provisions);

  // Generate report metadata
  const reportDate = new Date().toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const metadata: ReportMetadata = {
    reportDate,
    reportId: generateReportId(
      property.former_council,
      property.zone,
      property.heritage_status.in_hca,
      provisions.length,
      new Date()
    ),
    totalProvisions: provisions.length,
  };

  return (
    <Document>
      {/* Context Section - LEP/SEPP/Pathway with Header */}
      <Page size="A4" style={styles.page}>
        {/* Compact Cover Header */}
        <CoverPage property={property} groups={groups} metadata={metadata} />

        {/* Context Content */}
        <ContextSection
          property={property}
          exportedCount={provisions.length}
          totalCount={totalProvisions || provisions.length}
          activeFilters={activeFilters}
          isEmbedded={true}
        />
      </Page>

      {/* DCP Provisions - Continuous Flow */}
      <Page size="A4" style={styles.page} wrap>
        <Text style={{ fontSize: 16, fontWeight: 'bold', marginBottom: 8, marginTop: 0, color: '#1f2937' }}>
          DCP Provisions Schedule
        </Text>

        {/* All provision tables flow continuously */}
        {groups.map((group, idx) => (
          <ProvisionTable
            key={group.topic}
            group={group}
            sectionNumber={idx + 1}
            isFirst={idx === 0}
          />
        ))}

        {/* FOOTER COMPLETELY DISABLED - position:absolute causes coordinate overflow */}
      </Page>

      {/* Report Metadata - Final Page */}
      <Page size="A4" style={styles.page}>
        <View style={{ marginTop: 100, padding: 20 }}>
          <Text style={{ fontSize: 12, fontWeight: 'bold', marginBottom: 16, color: '#1f2937' }}>
            Report Information
          </Text>
          <View style={{ marginBottom: 8 }}>
            <Text style={{ fontSize: 9, color: '#6b7280' }}>Report Date:</Text>
            <Text style={{ fontSize: 10, color: '#1f2937', marginTop: 2 }}>{metadata.reportDate}</Text>
          </View>
          <View style={{ marginBottom: 8 }}>
            <Text style={{ fontSize: 9, color: '#6b7280' }}>Report ID:</Text>
            <Text style={{ fontSize: 10, color: '#1f2937', marginTop: 2 }}>{metadata.reportId}</Text>
          </View>
          <View style={{ marginTop: 20, paddingTop: 12, borderTop: '1pt solid #e5e7eb' }}>
            <Text style={{ fontSize: 9, color: '#6b7280' }}>Generated by PlotDetect</Text>
            <Text style={{ fontSize: 10, color: '#0f766e', marginTop: 4, textDecoration: 'underline' }}>
              verify.plotdetect.com.au
            </Text>
          </View>
        </View>
      </Page>
    </Document>
  );
}
