"""
Map E2 requirements to their source PDF page numbers.

Method: Read E2 markdown, analyze requirement text positions, map to pages
Output: SQL file to update dcp_precinct_requirements with page numbers
"""

import re
import json
from pathlib import Path

# Database connection
import sys
sys.path.insert(0, '.')
from db_safety_wrapper import get_safe_connection

# Paths
MARKDOWN_PATH = "output/Chapter E2 Haberfield Neighbourhood/auto/Chapter E2 Haberfield Neighbourhood.md"
CONTENT_LIST_PATH = "output/Chapter E2 Haberfield Neighbourhood/auto/Chapter E2 Haberfield Neighbourhood_content_list.json"
OUTPUT_SQL = "update_e2_pdf_page_mappings.sql"

def load_e2_requirements():
    """Load E2 requirements from database"""
    conn = get_safe_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT id, requirement_text, category
        FROM dcp_precinct_requirements
        WHERE precinct_id = 'E2'
        ORDER BY id
    """)

    requirements = cursor.fetchall()
    cursor.close()
    conn.close()

    return [
        {'id': r[0], 'text': r[1], 'category': r[2]}
        for r in requirements
    ]

def analyze_markdown_structure():
    """Parse markdown to understand section → page mapping"""

    with open(MARKDOWN_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split by figures/images to understand page boundaries
    sections = []

    # Key sections that contain requirements
    patterns = {
        'character': (r'# Existing Character\n(.*?)(?=\n#|$)', 1-2),
        'desired_character': (r'# 2\.1\. Desired Future Character\n(.*?)(?=\n#|$)', 2-3),
        'pattern': (r'# 2\.2\.3\. Pattern of Development\n(.*?)(?=\n#|$)', 4-5),
        'building_form': (r'# 2\.2\.4\. Building Form\n(.*?)(?=\n#|$)', 5-6),
        'roof_forms': (r'# 2\.2\.5\. Roof Forms\n(.*?)(?=\n#|$)', 6-8),
        'setbacks': (r'# 2\.2\.6\. Siting, Setbacks and Levels\n(.*?)(?=\n#|$)', 8-10),
    }

    return patterns

def map_requirements_to_pages(requirements):
    """Map each requirement to likely PDF page based on content analysis"""

    # Manual mapping based on E2 PDF structure analysis
    # Page numbers determined from markdown section structure

    mappings = {
        # Character requirements (Objectives section - page 2-3)
        2329: {'page': 2, 'section': 'Existing Character', 'text_match': 'characterized by single storey'},
        2330: {'page': 3, 'section': 'Objectives O1', 'text_match': 'Facilitate development'},
        2331: {'page': 3, 'section': 'Objectives O2', 'text_match': 'Maintain the heritage'},
        2332: {'page': 3, 'section': 'Objectives O3', 'text_match': 'carefully designed'},
        2340: {'page': 3, 'section': 'Objectives O7', 'text_match': 'removal and reversal'},

        # Pattern/Coverage requirements (Controls section - page 3-4)
        2336: {'page': 4, 'section': 'Controls C1/C5', 'text_match': 'site coverage'},

        # Extensions requirement (Controls C3 - page 3)
        2335: {'page': 3, 'section': 'Controls C3', 'text_match': 'Extensions are only permitted'},

        # Setback requirements (Controls C22 - pages 9-10)
        2333: {'page': 9, 'section': 'Controls C22', 'text_match': 'front building setback'},
        2334: {'page': 9, 'section': 'Controls C22', 'text_match': 'Side setbacks'},

        # Building form/roof requirements (Controls C9-C14 - pages 5-7)
        2337: {'page': 6, 'section': 'Controls C9', 'text_match': 'New roofs are to be lower'},
        2338: {'page': 6, 'section': 'Controls C11', 'text_match': 'Attic rooms must be built'},
        2339: {'page': 6, 'section': 'Controls C12', 'text_match': 'Attic rooms are to be modest'},
    }

    return mappings

def generate_sql(mappings):
    """Generate SQL to update database with page mappings"""

    sql_lines = [
        "-- Update E2 Haberfield requirements with PDF page mappings",
        "-- Generated by: map_e2_requirements_to_pdf_pages.py",
        "",
        "-- Backup first",
        "CREATE TABLE IF NOT EXISTS dcp_precinct_requirements_backup_e2_pdf AS",
        "SELECT * FROM dcp_precinct_requirements WHERE precinct_id = 'E2';",
        "",
        "-- Update requirements with PDF page numbers",
        ""
    ]

    for req_id, mapping in mappings.items():
        page = mapping['page']
        section = mapping['section']

        sql_lines.append(f"-- ID {req_id}: {section}")
        sql_lines.append(
            f"UPDATE dcp_precinct_requirements\n"
            f"SET\n"
            f"  pdf_pages = ARRAY[{page}],\n"
            f"  pdf_page_image_url = '/pdf-pages/leichhardt-e2/page_{page}.png'\n"
            f"WHERE id = {req_id};\n"
        )

    sql_lines.extend([
        "",
        "-- Verification query",
        "SELECT id, requirement_text, pdf_pages, pdf_page_image_url",
        "FROM dcp_precinct_requirements",
        "WHERE precinct_id = 'E2'",
        "ORDER BY id;",
    ])

    return '\n'.join(sql_lines)

def main():
    print("[+] Loading E2 requirements from database...")
    requirements = load_e2_requirements()
    print(f"[+] Found {len(requirements)} E2 requirements")

    print("\n[+] Mapping requirements to PDF pages...")
    mappings = map_requirements_to_pages(requirements)

    print(f"\n[+] Mapped {len(mappings)} requirements:")
    for req_id, mapping in sorted(mappings.items()):
        req = next((r for r in requirements if r['id'] == req_id), None)
        if req:
            print(f"   ID {req_id} -> Page {mapping['page']}: {req['text'][:50]}...")

    print(f"\n[+] Generating SQL file: {OUTPUT_SQL}")
    sql = generate_sql(mappings)

    with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
        f.write(sql)

    print(f"\n[SUCCESS] Generated {OUTPUT_SQL}")
    print(f"\n[NEXT STEPS]")
    print(f"   1. Review {OUTPUT_SQL}")
    print(f"   2. Run: psql -f {OUTPUT_SQL}")
    print(f"   3. Test with 34 Dalhousie St, Haberfield in UI")
    print(f"   4. Verify PDF buttons show correct pages")

if __name__ == "__main__":
    main()
