"""
Root conftest.py — mock injection + fixtures for the test suite.

IMPORTANT: conftest_mocks MUST be imported before anything else so that
sys.modules stubs are in place before pytest collects test files that
import services/*.py (which depend on psycopg2, requests, etc.).
"""

# ── Mock injection — must be first ───────────────────────────────────────────
import tests.conftest_mocks  # noqa: F401, E402

import json
import os
import pytest
from pathlib import Path

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "test_addresses.json"

# ── Non-test scripts and stale files to exclude from collection ──────────────
collect_ignore = [
    # Non-test utility scripts
    "analyze_dcp_general_structure.py",
    "analyze_dcp_structure_by_council.py",
    "check_dcp_general.py",
    "check_dev_types_complete.py",
    "check_leichhardt_db.py",
    "check_leichhardt_docs.py",
    "check_pdf_urls.py",
    "check_requirements_zones.py",
    "generate_test_addresses.py",
    "quick_test.py",
    "sample_leichhardt_precincts.py",
    "verify_ashfield_fix.py",
    "verify_leichhardt_fix.py",
    "01_verify_database_tables.py",
    "02_verify_api_queries.py",
    "03_verify_data_transform.py",
    "04_verify_end_to_end.py",
    # Stale subdirectories (import errors during collection)
    "processing",
    "root_tests",
    # ── Quarantined test files ───────────────────────────────────────────────
    # Any entry here MUST have a matching entry in tests/quarantine-baseline.json.
    # scripts/check_test_quarantine.py enforces it both ways: quarantining without
    # a recorded reason fails, and a listed file that starts PASSING also fails,
    # so it is released rather than left as standing amnesty.
    #
    # 2026-08-09: this list was 16. Measuring each one found SIX already passing,
    # TWO broken by the quarantining itself (a marker inserted above a
    # `from __future__` import — a SyntaxError), FIVE that were not tests at all
    # (1,090 lines, zero assertions — deleted), and THREE needing a live server or
    # a real database, now released with skip guards. What remains is genuinely
    # blocked and says so in the baseline.
]


def pytest_report_header(config):
    """Print the quarantine count on every run.

    The whole failure this guards against is invisibility: an uncollected file
    produces no output at all, so nobody is reminded it exists. One line at the
    top of every test run is the cheapest possible reminder.
    """
    n = sum(1 for f in collect_ignore if f.startswith("test_"))
    if n:
        return (f"quarantined: {n} test files excluded from collection "
                f"(see tests/quarantine-baseline.json)")
    return None

# ---------------------------------------------------------------------------
# test_address_validation.py — test_addr + report
# ---------------------------------------------------------------------------

def _load_test_addresses():
    """Return the address fixture, or [] when it is not present.

    The fixture is generated by tests/generate_test_addresses.py and was never
    committed, because .gitignore's `test_*.json` pattern silently swallows
    `tests/fixtures/test_addresses.json`. (That pattern is aimed at scratch
    output; an explicit re-include now sits beside it.)

    Raising here was the actual reason test_address_validation.py could not be
    collected: this runs inside pytest_generate_tests, so a FileNotFoundError
    aborts COLLECTION and no skipif on the test module can ever be reached.
    Returning an empty list instead lets parametrisation produce zero cases,
    which pytest reports as a visible skip rather than a collection error.
    """
    if not FIXTURES_PATH.exists():
        return []
    with open(FIXTURES_PATH) as f:
        return json.load(f).get("addresses") or []


class _ValidationReport:
    """Minimal stand-in so tests can call report.add() without importing the
    test module (which would cause collection-time side effects)."""
    def __init__(self):
        self.total_tests = 0
        self.passed = 0
        self.failed = 0
        self.results = []

    def add(self, result):
        self.total_tests += 1
        if getattr(result, "passed", False):
            self.passed += 1
        else:
            self.failed += 1
        self.results.append(result)


@pytest.fixture
def report():
    return _ValidationReport()


def pytest_generate_tests(metafunc):
    """Parametrize fixtures that differ per test file."""

    # test_address_validation.py
    if "test_addr" in metafunc.fixturenames:
        addresses = _load_test_addresses()
        if not addresses:
            # Zero cases -> pytest reports the module as skipped, which is
            # visible. The alternative (raising) aborts collection and is how
            # this file ended up quarantined and invisible in the first place.
            metafunc.parametrize("test_addr", [], ids=[])
        else:
            metafunc.parametrize(
                "test_addr",
                addresses,
                ids=[a["address"][:50] for a in addresses],
            )

    # test_dev_type_filtering.py
    if "council_name" in metafunc.fixturenames:
        metafunc.parametrize("council_name", ["Marrickville", "Ashfield", "Leichhardt"])

    # test_leichhardt_thorough.py — address only (no description)
    if (
        "address" in metafunc.fixturenames
        and "description" not in metafunc.fixturenames
    ):
        addresses = [
            "180 Addison Road Marrickville 2204",
            "45 Denison Road Dulwich Hill 2203",
            "15 Alt Street Ashfield 2131",
            "1 The Parade Haberfield 2045",
            "10 Norton Street Leichhardt 2040",
            "25 Marion Street Leichhardt 2040",
            "150 Balmain Road Leichhardt 2040",
            "5 Lombard Street Glebe 2037",
        ]
        metafunc.parametrize("address", addresses)

    # test_real_user_flow_with_pp.py — paired address + description
    if (
        "address" in metafunc.fixturenames
        and "description" in metafunc.fixturenames
    ):
        cases = [
            ("10 Norton Street, Leichhardt NSW 2040", "Commercial/retail in Norton St precinct"),
            ("45 Terry Street, Rozelle NSW 2039", "Residential in Rozelle"),
            ("25 Flood Street, Leichhardt NSW 2040", "Residential near Norton Street"),
            ("100 Stanmore Road, Stanmore NSW 2048", "Main road property in Stanmore"),
            ("52 Norton Street, Leichhardt NSW 2040", "Norton Street retail/commercial"),
            ("50 Liverpool Road, Ashfield NSW 2131", "Commercial area in Ashfield"),
            ("1 Metropolitan Road, Enmore NSW 2042", "Residential in Enmore"),
        ]
        metafunc.parametrize("address,description", cases)


# ---------------------------------------------------------------------------
# test_version_tracking.py — db cursor
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def cur():
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        pytest.skip("DATABASE_URL not set -- skipping DB tests")

    try:
        import psycopg2
        from psycopg2.extras import RealDictCursor
    except ImportError:
        pytest.skip("psycopg2 not installed")

    conn = psycopg2.connect(database_url, cursor_factory=RealDictCursor)
    cursor = conn.cursor()
    yield cursor
    cursor.close()
    conn.close()


# ---------------------------------------------------------------------------
# Dependency-skip census — the counter-measure to a gate going quiet
# ---------------------------------------------------------------------------
#
# ORIGIN: 2026-08-06. main was red from 08-03 because four tests in
# test_dcp_as_at.py needed PyMuPDF, which requirements-test.txt did not
# install. `pytest -x` stopped at the first, so ~1,800 tests did not execute
# for three days and nobody noticed. Auditing the rest turned up a second,
# quieter version of the same thing: 23 tests that never run ANYWHERE because
# a missing import turns them into a skip, and a skip is silent.
#
# A test that cannot run is not a passing test. This hook makes that
# countable: every dependency-driven skip is written to .pytest-skips.json and
# printed as its own terminal section, and scripts/check_dependency_skips.py
# ratchets the count so a new one cannot appear without failing the build.
# The existing 23 are baselined, not blessed — the baseline only shrinks.

import re as _re

_DEP_SKIP_PATTERNS = [
    _re.compile(r"could not import '([\w.]+)'"),          # pytest.importorskip
    _re.compile(r"No module named '([\w.]+)'"),
    _re.compile(r"^([\w.]+) not installed"),
    _re.compile(r"needs real ([\w .+]+)"),
    _re.compile(r"([\w.]+) (?:postconditions )?not active"),
]


def _dependency_from_skip_reason(reason: str):
    """The module a skip blames, or None if the skip is about something else.

    Deliberately narrow: an env-gated skip ("set RUN_LIVE_GEMINI=1") is a
    choice, not a missing dependency, and must not be swept into the same
    number — otherwise the ratchet measures intent instead of coverage.
    """
    text = (reason or "").strip()
    for pat in _DEP_SKIP_PATTERNS:
        m = pat.search(text)
        if m:
            return m.group(1).strip()
    return None


def pytest_sessionstart(session):
    """Delete last run's census before this one starts.

    Belt to the terminal_summary braces: if this run dies before the summary
    hook fires — a collection error, a crash, a killed job — a stale
    .pytest-skips.json would otherwise still be sitting there for the ratchet
    to read as though it described this run. Gone at the start means the
    ratchet exits 2 rather than passing on last week's numbers.
    """
    try:
        (Path(session.config.rootdir) / ".pytest-skips.json").unlink(missing_ok=True)
    except OSError:
        pass


def pytest_terminal_summary(terminalreporter, exitstatus, config):
    # EVERY skip is recorded, not only the ones a regex recognises. Classifying
    # first and counting second would leave the obvious hole: a skip whose
    # reason happens to be phrased differently — pytest.mark.skipif(boto3 is
    # None, reason="requires boto3") — matches nothing, gets counted nowhere,
    # and disappears exactly like the tests this exists to catch. The total is
    # what the ratchet enforces; the dependency breakdown is for diagnosis.
    skipped = terminalreporter.stats.get("skipped", [])
    all_skips = []
    for rep in skipped:
        reason = ""
        if isinstance(getattr(rep, "longrepr", None), tuple) and len(rep.longrepr) == 3:
            reason = rep.longrepr[2]
        reason = _re.sub(r"^Skipped: ", "", str(reason))
        all_skips.append({
            "test": rep.nodeid,
            "dependency": _dependency_from_skip_reason(reason),
            "reason": reason,
        })

    found = [s for s in all_skips if s["dependency"]]
    out = Path(config.rootdir) / ".pytest-skips.json"
    try:
        out.write_text(json.dumps({
            "total": len(all_skips),
            "count": len(found),
            "skips": sorted(all_skips, key=lambda s: s["test"]),
        }, indent=1), encoding="utf-8")
    except OSError as exc:
        # Do NOT swallow. A failed write leaves the PREVIOUS run's census on
        # disk, and the ratchet would then judge this run against stale
        # numbers and pass. Removing the file makes the ratchet exit 2
        # ("report not found") instead, which is the honest outcome.
        terminalreporter.write_line(
            f"WARNING: could not write {out.name} ({exc}); removing any stale "
            "copy so the ratchet cannot read it as this run's result.", red=True)
        try:
            out.unlink(missing_ok=True)
        except OSError:
            pass

    if not found:
        return
    by_dep = {}
    for s in found:
        by_dep.setdefault(s["dependency"], []).append(s["test"])
    terminalreporter.write_sep("=", "TESTS THAT DID NOT RUN (missing dependency)", yellow=True)
    for dep in sorted(by_dep):
        terminalreporter.write_line(f"  {dep:<28} {len(by_dep[dep])} test(s)")
    terminalreporter.write_line(
        f"  {len(found)} test(s) skipped for a missing import — these are NOT passing tests.")
