import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { createClient } from '@supabase/supabase-js'
import { SharedBushfireResult } from './SharedBushfireResult'

function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  )
}

interface Props {
  params: Promise<{ id: string }>
}

async function getReport(id: string) {
  const { data, error } = await getSupabase()
    .from('property_reports')
    .select('*')
    .eq('id', id)
    .eq('product', 'bushfire')
    .single()

  if (error || !data) return null
  return data
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const report = await getReport(id)
  if (!report) return { title: 'Report not found' }

  const signal = report.outputs?.fire_signal ?? 'unknown'
  const address = report.address ?? 'Property'

  return {
    title: `Bushfire Pre-Screen — ${address}`,
    description: `Bushfire risk assessment for ${address}. Fire signal: ${signal}. Generated by plotdetect.com.au.`,
    openGraph: {
      title: `Bushfire Pre-Screen — ${address}`,
      description: `BFPL status, BAL band estimate, and development implications for ${address}.`,
      url: `https://verify.plotdetect.com.au/reports/bushfire/${id}`,
      siteName: 'plotdetect.com.au',
      type: 'website',
    },
  }
}

export default async function SharedBushfirePage({ params }: Props) {
  const { id } = await params
  const report = await getReport(id)

  if (!report) notFound()

  const result = {
    address: report.address,
    lat: report.lat,
    lng: report.lng,
    run_date: report.run_date,
    outputs: report.outputs,
    confidence: report.confidence,
    data_sources: report.data_sources ?? [],
    report_id: report.id,
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-10">
      <div className="mb-6">
        <p className="text-xs text-gray-400 mb-1">Shared bushfire pre-screen result</p>
        <p className="text-xs text-gray-400">
          Run your own check at{' '}
          <a href="/reports/bushfire" className="text-teal-600 hover:text-teal-700 underline">
            plotdetect.com.au/reports/bushfire
          </a>
        </p>
      </div>
      <SharedBushfireResult result={result} reportId={id} />
    </div>
  )
}
