-- Migration 009: Full lep_land_use_table replacement for Inner West LEP 2022
-- Source: Inner West LEP 2022 (epi-2022-0457) Schedule 1 Land Use Table
-- Replaces whitelist-only data with all three permissibility categories:
--   exempt    = permitted without development consent
--   permitted = permitted with development consent
--   prohibited = prohibited
--
-- Also creates lep_zone_coverage safety gate table.
-- Zones covered: R1, R2, R3, R4, E1, E2, E3, E4, MU1, SP1, SP2, RE1, RE2, W1, W2, W4

-- ============================================================
-- 1. lep_zone_coverage safety gate
-- ============================================================
CREATE TABLE IF NOT EXISTS public.lep_zone_coverage (
    id          serial PRIMARY KEY,
    zone        varchar(10)  NOT NULL,
    lga         varchar(255) NOT NULL,
    is_complete boolean      NOT NULL DEFAULT false,
    notes       text,
    created_at  timestamp    NOT NULL DEFAULT now(),
    UNIQUE (zone, lga)
);

ALTER TABLE public.lep_zone_coverage ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.lep_zone_coverage TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.lep_zone_coverage_id_seq TO anon, authenticated, service_role;

-- ============================================================
-- 2. Replace Inner West data in lep_land_use_table
-- ============================================================
DELETE FROM public.lep_land_use_table WHERE lga = 'Inner West';

INSERT INTO public.lep_land_use_table (zone, zone_name, lga, development_type, permissibility, notes) VALUES

-- ============================================================
-- R1 General Residential
-- ============================================================
('R1','General Residential','Inner West','home_occupations','exempt','Permitted without development consent'),

('R1','General Residential','Inner West','attached_dwellings','permitted',NULL),
('R1','General Residential','Inner West','bed_and_breakfast_accommodation','permitted',NULL),
('R1','General Residential','Inner West','boarding_houses','permitted',NULL),
('R1','General Residential','Inner West','centre_based_child_care_facilities','permitted',NULL),
('R1','General Residential','Inner West','community_facilities','permitted',NULL),
('R1','General Residential','Inner West','dwelling_houses','permitted',NULL),
('R1','General Residential','Inner West','group_homes','permitted',NULL),
('R1','General Residential','Inner West','home_industries','permitted',NULL),
('R1','General Residential','Inner West','hostels','permitted',NULL),
('R1','General Residential','Inner West','multi_dwelling_housing','permitted',NULL),
('R1','General Residential','Inner West','neighbourhood_shops','permitted',NULL),
('R1','General Residential','Inner West','oyster_aquaculture','permitted',NULL),
('R1','General Residential','Inner West','places_of_public_worship','permitted',NULL),
('R1','General Residential','Inner West','pond_based_aquaculture','permitted',NULL),
('R1','General Residential','Inner West','residential_flat_buildings','permitted',NULL),
('R1','General Residential','Inner West','respite_day_care_centres','permitted',NULL),
('R1','General Residential','Inner West','roads','permitted',NULL),
('R1','General Residential','Inner West','semi_detached_dwellings','permitted',NULL),
('R1','General Residential','Inner West','seniors_housing','permitted',NULL),
('R1','General Residential','Inner West','shop_top_housing','permitted',NULL),
('R1','General Residential','Inner West','tank_based_aquaculture','permitted',NULL),
('R1','General Residential','Inner West','any_other_development','permitted',NULL),

('R1','General Residential','Inner West','advertising_structures','prohibited',NULL),
('R1','General Residential','Inner West','agriculture','prohibited',NULL),
('R1','General Residential','Inner West','air_transport_facilities','prohibited',NULL),
('R1','General Residential','Inner West','airstrips','prohibited',NULL),
('R1','General Residential','Inner West','amusement_centres','prohibited',NULL),
('R1','General Residential','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('R1','General Residential','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('R1','General Residential','Inner West','boat_building_and_repair_facilities','prohibited',NULL),
('R1','General Residential','Inner West','boat_launching_ramps','prohibited',NULL),
('R1','General Residential','Inner West','camping_grounds','prohibited',NULL),
('R1','General Residential','Inner West','car_parks','prohibited',NULL),
('R1','General Residential','Inner West','caravan_parks','prohibited',NULL),
('R1','General Residential','Inner West','cemeteries','prohibited',NULL),
('R1','General Residential','Inner West','charter_and_tourism_boating_facilities','prohibited',NULL),
('R1','General Residential','Inner West','commercial_premises','prohibited',NULL),
('R1','General Residential','Inner West','correctional_centres','prohibited',NULL),
('R1','General Residential','Inner West','crematoria','prohibited',NULL),
('R1','General Residential','Inner West','depots','prohibited',NULL),
('R1','General Residential','Inner West','dual_occupancies','prohibited',NULL),
('R1','General Residential','Inner West','eco_tourist_facilities','prohibited',NULL),
('R1','General Residential','Inner West','emergency_services_facilities','prohibited',NULL),
('R1','General Residential','Inner West','entertainment_facilities','prohibited',NULL),
('R1','General Residential','Inner West','environmental_facilities','prohibited',NULL),
('R1','General Residential','Inner West','exhibition_homes','prohibited',NULL),
('R1','General Residential','Inner West','exhibition_villages','prohibited',NULL),
('R1','General Residential','Inner West','extractive_industries','prohibited',NULL),
('R1','General Residential','Inner West','farm_buildings','prohibited',NULL),
('R1','General Residential','Inner West','forestry','prohibited',NULL),
('R1','General Residential','Inner West','freight_transport_facilities','prohibited',NULL),
('R1','General Residential','Inner West','function_centres','prohibited',NULL),
('R1','General Residential','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('R1','General Residential','Inner West','helipads','prohibited',NULL),
('R1','General Residential','Inner West','highway_service_centres','prohibited',NULL),
('R1','General Residential','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('R1','General Residential','Inner West','industrial_retail_outlets','prohibited',NULL),
('R1','General Residential','Inner West','industrial_training_facilities','prohibited',NULL),
('R1','General Residential','Inner West','industries','prohibited',NULL),
('R1','General Residential','Inner West','information_and_education_facilities','prohibited',NULL),
('R1','General Residential','Inner West','marinas','prohibited',NULL),
('R1','General Residential','Inner West','mooring_pens','prohibited',NULL),
('R1','General Residential','Inner West','moorings','prohibited',NULL),
('R1','General Residential','Inner West','mortuaries','prohibited',NULL),
('R1','General Residential','Inner West','open_cut_mining','prohibited',NULL),
('R1','General Residential','Inner West','passenger_transport_facilities','prohibited',NULL),
('R1','General Residential','Inner West','port_facilities','prohibited',NULL),
('R1','General Residential','Inner West','recreation_facilities_(indoor)','prohibited',NULL),
('R1','General Residential','Inner West','recreation_facilities_(major)','prohibited',NULL),
('R1','General Residential','Inner West','recreation_facilities_(outdoor)','prohibited',NULL),
('R1','General Residential','Inner West','registered_clubs','prohibited',NULL),
('R1','General Residential','Inner West','research_stations','prohibited',NULL),
('R1','General Residential','Inner West','restricted_premises','prohibited',NULL),
('R1','General Residential','Inner West','rural_industries','prohibited',NULL),
('R1','General Residential','Inner West','rural_workers_dwellings','prohibited',NULL),
('R1','General Residential','Inner West','service_stations','prohibited',NULL),
('R1','General Residential','Inner West','sewage_treatment_plants','prohibited',NULL),
('R1','General Residential','Inner West','sex_services_premises','prohibited',NULL),
('R1','General Residential','Inner West','storage_premises','prohibited',NULL),
('R1','General Residential','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('R1','General Residential','Inner West','transport_depots','prohibited',NULL),
('R1','General Residential','Inner West','truck_depots','prohibited',NULL),
('R1','General Residential','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('R1','General Residential','Inner West','vehicle_repair_stations','prohibited',NULL),
('R1','General Residential','Inner West','veterinary_hospitals','prohibited',NULL),
('R1','General Residential','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('R1','General Residential','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('R1','General Residential','Inner West','water_recreation_structures','prohibited',NULL),
('R1','General Residential','Inner West','water_supply_systems','prohibited',NULL),
('R1','General Residential','Inner West','wharf_or_boating_facilities','prohibited',NULL),
('R1','General Residential','Inner West','wholesale_supplies','prohibited',NULL),

-- ============================================================
-- R2 Low Density Residential
-- ============================================================
('R2','Low Density Residential','Inner West','home_occupations','exempt','Permitted without development consent'),

('R2','Low Density Residential','Inner West','bed_and_breakfast_accommodation','permitted',NULL),
('R2','Low Density Residential','Inner West','centre_based_child_care_facilities','permitted',NULL),
('R2','Low Density Residential','Inner West','dwelling_houses','permitted',NULL),
('R2','Low Density Residential','Inner West','group_homes','permitted',NULL),
('R2','Low Density Residential','Inner West','home_businesses','permitted',NULL),
('R2','Low Density Residential','Inner West','home_industries','permitted',NULL),
('R2','Low Density Residential','Inner West','hostels','permitted',NULL),
('R2','Low Density Residential','Inner West','neighbourhood_shops','permitted',NULL),
('R2','Low Density Residential','Inner West','oyster_aquaculture','permitted',NULL),
('R2','Low Density Residential','Inner West','pond_based_aquaculture','permitted',NULL),
('R2','Low Density Residential','Inner West','respite_day_care_centres','permitted',NULL),
('R2','Low Density Residential','Inner West','roads','permitted',NULL),
('R2','Low Density Residential','Inner West','secondary_dwellings','permitted',NULL),
('R2','Low Density Residential','Inner West','semi_detached_dwellings','permitted',NULL),
('R2','Low Density Residential','Inner West','seniors_housing','permitted',NULL),
('R2','Low Density Residential','Inner West','tank_based_aquaculture','permitted',NULL),
('R2','Low Density Residential','Inner West','any_other_development','permitted',NULL),

('R2','Low Density Residential','Inner West','advertising_structures','prohibited',NULL),
('R2','Low Density Residential','Inner West','agriculture','prohibited',NULL),
('R2','Low Density Residential','Inner West','air_transport_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','airstrips','prohibited',NULL),
('R2','Low Density Residential','Inner West','amusement_centres','prohibited',NULL),
('R2','Low Density Residential','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('R2','Low Density Residential','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','boarding_houses','prohibited',NULL),
('R2','Low Density Residential','Inner West','boat_building_and_repair_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','boat_launching_ramps','prohibited',NULL),
('R2','Low Density Residential','Inner West','boat_sheds','prohibited',NULL),
('R2','Low Density Residential','Inner West','camping_grounds','prohibited',NULL),
('R2','Low Density Residential','Inner West','car_parks','prohibited',NULL),
('R2','Low Density Residential','Inner West','caravan_parks','prohibited',NULL),
('R2','Low Density Residential','Inner West','cemeteries','prohibited',NULL),
('R2','Low Density Residential','Inner West','charter_and_tourism_boating_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','commercial_premises','prohibited',NULL),
('R2','Low Density Residential','Inner West','correctional_centres','prohibited',NULL),
('R2','Low Density Residential','Inner West','crematoria','prohibited',NULL),
('R2','Low Density Residential','Inner West','depots','prohibited',NULL),
('R2','Low Density Residential','Inner West','eco_tourist_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','emergency_services_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','entertainment_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','environmental_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','exhibition_homes','prohibited',NULL),
('R2','Low Density Residential','Inner West','exhibition_villages','prohibited',NULL),
('R2','Low Density Residential','Inner West','extractive_industries','prohibited',NULL),
('R2','Low Density Residential','Inner West','farm_buildings','prohibited',NULL),
('R2','Low Density Residential','Inner West','forestry','prohibited',NULL),
('R2','Low Density Residential','Inner West','freight_transport_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','function_centres','prohibited',NULL),
('R2','Low Density Residential','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('R2','Low Density Residential','Inner West','helipads','prohibited',NULL),
('R2','Low Density Residential','Inner West','highway_service_centres','prohibited',NULL),
('R2','Low Density Residential','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('R2','Low Density Residential','Inner West','industrial_retail_outlets','prohibited',NULL),
('R2','Low Density Residential','Inner West','industrial_training_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','industries','prohibited',NULL),
('R2','Low Density Residential','Inner West','information_and_education_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','jetties','prohibited',NULL),
('R2','Low Density Residential','Inner West','marinas','prohibited',NULL),
('R2','Low Density Residential','Inner West','mooring_pens','prohibited',NULL),
('R2','Low Density Residential','Inner West','moorings','prohibited',NULL),
('R2','Low Density Residential','Inner West','mortuaries','prohibited',NULL),
('R2','Low Density Residential','Inner West','open_cut_mining','prohibited',NULL),
('R2','Low Density Residential','Inner West','passenger_transport_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','port_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','recreation_facilities_(indoor)','prohibited',NULL),
('R2','Low Density Residential','Inner West','recreation_facilities_(major)','prohibited',NULL),
('R2','Low Density Residential','Inner West','recreation_facilities_(outdoor)','prohibited',NULL),
('R2','Low Density Residential','Inner West','registered_clubs','prohibited',NULL),
('R2','Low Density Residential','Inner West','research_stations','prohibited',NULL),
('R2','Low Density Residential','Inner West','residential_accommodation','prohibited',NULL),
('R2','Low Density Residential','Inner West','restricted_premises','prohibited',NULL),
('R2','Low Density Residential','Inner West','rural_industries','prohibited',NULL),
('R2','Low Density Residential','Inner West','service_stations','prohibited',NULL),
('R2','Low Density Residential','Inner West','sewage_treatment_plants','prohibited',NULL),
('R2','Low Density Residential','Inner West','sex_services_premises','prohibited',NULL),
('R2','Low Density Residential','Inner West','storage_premises','prohibited',NULL),
('R2','Low Density Residential','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('R2','Low Density Residential','Inner West','transport_depots','prohibited',NULL),
('R2','Low Density Residential','Inner West','truck_depots','prohibited',NULL),
('R2','Low Density Residential','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('R2','Low Density Residential','Inner West','vehicle_repair_stations','prohibited',NULL),
('R2','Low Density Residential','Inner West','veterinary_hospitals','prohibited',NULL),
('R2','Low Density Residential','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('R2','Low Density Residential','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','water_recreation_structures','prohibited',NULL),
('R2','Low Density Residential','Inner West','water_supply_systems','prohibited',NULL),
('R2','Low Density Residential','Inner West','wharf_or_boating_facilities','prohibited',NULL),
('R2','Low Density Residential','Inner West','wholesale_supplies','prohibited',NULL),

-- ============================================================
-- R3 Medium Density Residential
-- ============================================================
('R3','Medium Density Residential','Inner West','home_occupations','exempt','Permitted without development consent'),

('R3','Medium Density Residential','Inner West','attached_dwellings','permitted',NULL),
('R3','Medium Density Residential','Inner West','bed_and_breakfast_accommodation','permitted',NULL),
('R3','Medium Density Residential','Inner West','boarding_houses','permitted',NULL),
('R3','Medium Density Residential','Inner West','centre_based_child_care_facilities','permitted',NULL),
('R3','Medium Density Residential','Inner West','community_facilities','permitted',NULL),
('R3','Medium Density Residential','Inner West','dwelling_houses','permitted',NULL),
('R3','Medium Density Residential','Inner West','group_homes','permitted',NULL),
('R3','Medium Density Residential','Inner West','home_industries','permitted',NULL),
('R3','Medium Density Residential','Inner West','hostels','permitted',NULL),
('R3','Medium Density Residential','Inner West','multi_dwelling_housing','permitted',NULL),
('R3','Medium Density Residential','Inner West','neighbourhood_shops','permitted',NULL),
('R3','Medium Density Residential','Inner West','oyster_aquaculture','permitted',NULL),
('R3','Medium Density Residential','Inner West','places_of_public_worship','permitted',NULL),
('R3','Medium Density Residential','Inner West','respite_day_care_centres','permitted',NULL),
('R3','Medium Density Residential','Inner West','roads','permitted',NULL),
('R3','Medium Density Residential','Inner West','secondary_dwellings','permitted',NULL),
('R3','Medium Density Residential','Inner West','semi_detached_dwellings','permitted',NULL),
('R3','Medium Density Residential','Inner West','seniors_housing','permitted',NULL),
('R3','Medium Density Residential','Inner West','shop_top_housing','permitted',NULL),
('R3','Medium Density Residential','Inner West','tank_based_aquaculture','permitted',NULL),
('R3','Medium Density Residential','Inner West','any_other_development','permitted',NULL),

('R3','Medium Density Residential','Inner West','advertising_structures','prohibited',NULL),
('R3','Medium Density Residential','Inner West','agriculture','prohibited',NULL),
('R3','Medium Density Residential','Inner West','air_transport_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','airstrips','prohibited',NULL),
('R3','Medium Density Residential','Inner West','amusement_centres','prohibited',NULL),
('R3','Medium Density Residential','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('R3','Medium Density Residential','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','boat_building_and_repair_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','boat_launching_ramps','prohibited',NULL),
('R3','Medium Density Residential','Inner West','boat_sheds','prohibited',NULL),
('R3','Medium Density Residential','Inner West','camping_grounds','prohibited',NULL),
('R3','Medium Density Residential','Inner West','car_parks','prohibited',NULL),
('R3','Medium Density Residential','Inner West','caravan_parks','prohibited',NULL),
('R3','Medium Density Residential','Inner West','cemeteries','prohibited',NULL),
('R3','Medium Density Residential','Inner West','charter_and_tourism_boating_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','commercial_premises','prohibited',NULL),
('R3','Medium Density Residential','Inner West','correctional_centres','prohibited',NULL),
('R3','Medium Density Residential','Inner West','crematoria','prohibited',NULL),
('R3','Medium Density Residential','Inner West','depots','prohibited',NULL),
('R3','Medium Density Residential','Inner West','eco_tourist_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','emergency_services_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','entertainment_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','environmental_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','exhibition_homes','prohibited',NULL),
('R3','Medium Density Residential','Inner West','exhibition_villages','prohibited',NULL),
('R3','Medium Density Residential','Inner West','extractive_industries','prohibited',NULL),
('R3','Medium Density Residential','Inner West','farm_buildings','prohibited',NULL),
('R3','Medium Density Residential','Inner West','forestry','prohibited',NULL),
('R3','Medium Density Residential','Inner West','freight_transport_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','function_centres','prohibited',NULL),
('R3','Medium Density Residential','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('R3','Medium Density Residential','Inner West','helipads','prohibited',NULL),
('R3','Medium Density Residential','Inner West','highway_service_centres','prohibited',NULL),
('R3','Medium Density Residential','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('R3','Medium Density Residential','Inner West','industrial_retail_outlets','prohibited',NULL),
('R3','Medium Density Residential','Inner West','industrial_training_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','industries','prohibited',NULL),
('R3','Medium Density Residential','Inner West','information_and_education_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','jetties','prohibited',NULL),
('R3','Medium Density Residential','Inner West','marinas','prohibited',NULL),
('R3','Medium Density Residential','Inner West','mooring_pens','prohibited',NULL),
('R3','Medium Density Residential','Inner West','moorings','prohibited',NULL),
('R3','Medium Density Residential','Inner West','mortuaries','prohibited',NULL),
('R3','Medium Density Residential','Inner West','open_cut_mining','prohibited',NULL),
('R3','Medium Density Residential','Inner West','passenger_transport_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','port_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','recreation_facilities_(indoor)','prohibited',NULL),
('R3','Medium Density Residential','Inner West','recreation_facilities_(major)','prohibited',NULL),
('R3','Medium Density Residential','Inner West','recreation_facilities_(outdoor)','prohibited',NULL),
('R3','Medium Density Residential','Inner West','registered_clubs','prohibited',NULL),
('R3','Medium Density Residential','Inner West','research_stations','prohibited',NULL),
('R3','Medium Density Residential','Inner West','residential_accommodation','prohibited',NULL),
('R3','Medium Density Residential','Inner West','restricted_premises','prohibited',NULL),
('R3','Medium Density Residential','Inner West','rural_industries','prohibited',NULL),
('R3','Medium Density Residential','Inner West','service_stations','prohibited',NULL),
('R3','Medium Density Residential','Inner West','sewage_treatment_plants','prohibited',NULL),
('R3','Medium Density Residential','Inner West','sex_services_premises','prohibited',NULL),
('R3','Medium Density Residential','Inner West','storage_premises','prohibited',NULL),
('R3','Medium Density Residential','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('R3','Medium Density Residential','Inner West','transport_depots','prohibited',NULL),
('R3','Medium Density Residential','Inner West','truck_depots','prohibited',NULL),
('R3','Medium Density Residential','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('R3','Medium Density Residential','Inner West','vehicle_repair_stations','prohibited',NULL),
('R3','Medium Density Residential','Inner West','veterinary_hospitals','prohibited',NULL),
('R3','Medium Density Residential','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('R3','Medium Density Residential','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','water_recreation_structures','prohibited',NULL),
('R3','Medium Density Residential','Inner West','water_recycling_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','water_supply_systems','prohibited',NULL),
('R3','Medium Density Residential','Inner West','wharf_or_boating_facilities','prohibited',NULL),
('R3','Medium Density Residential','Inner West','wholesale_supplies','prohibited',NULL),

-- ============================================================
-- R4 High Density Residential
-- ============================================================
('R4','High Density Residential','Inner West','home_occupations','exempt','Permitted without development consent'),

('R4','High Density Residential','Inner West','bed_and_breakfast_accommodation','permitted',NULL),
('R4','High Density Residential','Inner West','boarding_houses','permitted',NULL),
('R4','High Density Residential','Inner West','centre_based_child_care_facilities','permitted',NULL),
('R4','High Density Residential','Inner West','community_facilities','permitted',NULL),
('R4','High Density Residential','Inner West','dwelling_houses','permitted',NULL),
('R4','High Density Residential','Inner West','group_homes','permitted',NULL),
('R4','High Density Residential','Inner West','home_industries','permitted',NULL),
('R4','High Density Residential','Inner West','hostels','permitted',NULL),
('R4','High Density Residential','Inner West','kiosks','permitted',NULL),
('R4','High Density Residential','Inner West','neighbourhood_shops','permitted',NULL),
('R4','High Density Residential','Inner West','oyster_aquaculture','permitted',NULL),
('R4','High Density Residential','Inner West','places_of_public_worship','permitted',NULL),
('R4','High Density Residential','Inner West','residential_flat_buildings','permitted',NULL),
('R4','High Density Residential','Inner West','respite_day_care_centres','permitted',NULL),
('R4','High Density Residential','Inner West','roads','permitted',NULL),
('R4','High Density Residential','Inner West','secondary_dwellings','permitted',NULL),
('R4','High Density Residential','Inner West','seniors_housing','permitted',NULL),
('R4','High Density Residential','Inner West','shop_top_housing','permitted',NULL),
('R4','High Density Residential','Inner West','any_other_development','permitted',NULL),

('R4','High Density Residential','Inner West','advertising_structures','prohibited',NULL),
('R4','High Density Residential','Inner West','agriculture','prohibited',NULL),
('R4','High Density Residential','Inner West','air_transport_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','airstrips','prohibited',NULL),
('R4','High Density Residential','Inner West','amusement_centres','prohibited',NULL),
('R4','High Density Residential','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('R4','High Density Residential','Inner West','boat_building_and_repair_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','boat_launching_ramps','prohibited',NULL),
('R4','High Density Residential','Inner West','boat_sheds','prohibited',NULL),
('R4','High Density Residential','Inner West','camping_grounds','prohibited',NULL),
('R4','High Density Residential','Inner West','car_parks','prohibited',NULL),
('R4','High Density Residential','Inner West','caravan_parks','prohibited',NULL),
('R4','High Density Residential','Inner West','cemeteries','prohibited',NULL),
('R4','High Density Residential','Inner West','charter_and_tourism_boating_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','commercial_premises','prohibited',NULL),
('R4','High Density Residential','Inner West','correctional_centres','prohibited',NULL),
('R4','High Density Residential','Inner West','crematoria','prohibited',NULL),
('R4','High Density Residential','Inner West','depots','prohibited',NULL),
('R4','High Density Residential','Inner West','eco_tourist_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','emergency_services_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','entertainment_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','environmental_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','exhibition_homes','prohibited',NULL),
('R4','High Density Residential','Inner West','exhibition_villages','prohibited',NULL),
('R4','High Density Residential','Inner West','extractive_industries','prohibited',NULL),
('R4','High Density Residential','Inner West','farm_buildings','prohibited',NULL),
('R4','High Density Residential','Inner West','forestry','prohibited',NULL),
('R4','High Density Residential','Inner West','freight_transport_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','function_centres','prohibited',NULL),
('R4','High Density Residential','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('R4','High Density Residential','Inner West','helipads','prohibited',NULL),
('R4','High Density Residential','Inner West','highway_service_centres','prohibited',NULL),
('R4','High Density Residential','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('R4','High Density Residential','Inner West','industrial_retail_outlets','prohibited',NULL),
('R4','High Density Residential','Inner West','industrial_training_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','industries','prohibited',NULL),
('R4','High Density Residential','Inner West','information_and_education_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','jetties','prohibited',NULL),
('R4','High Density Residential','Inner West','marinas','prohibited',NULL),
('R4','High Density Residential','Inner West','mooring_pens','prohibited',NULL),
('R4','High Density Residential','Inner West','moorings','prohibited',NULL),
('R4','High Density Residential','Inner West','mortuaries','prohibited',NULL),
('R4','High Density Residential','Inner West','open_cut_mining','prohibited',NULL),
('R4','High Density Residential','Inner West','passenger_transport_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','port_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','recreation_facilities_(indoor)','prohibited',NULL),
('R4','High Density Residential','Inner West','recreation_facilities_(major)','prohibited',NULL),
('R4','High Density Residential','Inner West','recreation_facilities_(outdoor)','prohibited',NULL),
('R4','High Density Residential','Inner West','registered_clubs','prohibited',NULL),
('R4','High Density Residential','Inner West','research_stations','prohibited',NULL),
('R4','High Density Residential','Inner West','residential_accommodation','prohibited',NULL),
('R4','High Density Residential','Inner West','restricted_premises','prohibited',NULL),
('R4','High Density Residential','Inner West','rural_industries','prohibited',NULL),
('R4','High Density Residential','Inner West','service_stations','prohibited',NULL),
('R4','High Density Residential','Inner West','sewerage_systems','prohibited',NULL),
('R4','High Density Residential','Inner West','sex_services_premises','prohibited',NULL),
('R4','High Density Residential','Inner West','storage_premises','prohibited',NULL),
('R4','High Density Residential','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('R4','High Density Residential','Inner West','transport_depots','prohibited',NULL),
('R4','High Density Residential','Inner West','truck_depots','prohibited',NULL),
('R4','High Density Residential','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('R4','High Density Residential','Inner West','vehicle_repair_stations','prohibited',NULL),
('R4','High Density Residential','Inner West','veterinary_hospitals','prohibited',NULL),
('R4','High Density Residential','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('R4','High Density Residential','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','water_recreation_structures','prohibited',NULL),
('R4','High Density Residential','Inner West','water_supply_systems','prohibited',NULL),
('R4','High Density Residential','Inner West','wharf_or_boating_facilities','prohibited',NULL),
('R4','High Density Residential','Inner West','wholesale_supplies','prohibited',NULL),

-- ============================================================
-- E1 Local Centre
-- ============================================================
('E1','Local Centre','Inner West','home_occupations','exempt','Permitted without development consent'),

('E1','Local Centre','Inner West','amusement_centres','permitted',NULL),
('E1','Local Centre','Inner West','boarding_houses','permitted',NULL),
('E1','Local Centre','Inner West','building_identification_signs','permitted',NULL),
('E1','Local Centre','Inner West','business_identification_signs','permitted',NULL),
('E1','Local Centre','Inner West','centre_based_child_care_facilities','permitted',NULL),
('E1','Local Centre','Inner West','commercial_premises','permitted',NULL),
('E1','Local Centre','Inner West','community_facilities','permitted',NULL),
('E1','Local Centre','Inner West','entertainment_facilities','permitted',NULL),
('E1','Local Centre','Inner West','function_centres','permitted',NULL),
('E1','Local Centre','Inner West','hostels','permitted',NULL),
('E1','Local Centre','Inner West','hotel_or_motel_accommodation','permitted',NULL),
('E1','Local Centre','Inner West','information_and_education_facilities','permitted',NULL),
('E1','Local Centre','Inner West','light_industries','permitted',NULL),
('E1','Local Centre','Inner West','local_distribution_premises','permitted',NULL),
('E1','Local Centre','Inner West','medical_centres','permitted',NULL),
('E1','Local Centre','Inner West','oyster_aquaculture','permitted',NULL),
('E1','Local Centre','Inner West','places_of_public_worship','permitted',NULL),
('E1','Local Centre','Inner West','public_administration_buildings','permitted',NULL),
('E1','Local Centre','Inner West','recreation_facilities_(indoor)','permitted',NULL),
('E1','Local Centre','Inner West','respite_day_care_centres','permitted',NULL),
('E1','Local Centre','Inner West','service_stations','permitted',NULL),
('E1','Local Centre','Inner West','shop_top_housing','permitted',NULL),
('E1','Local Centre','Inner West','tank_based_aquaculture','permitted',NULL),
('E1','Local Centre','Inner West','veterinary_hospitals','permitted',NULL),
('E1','Local Centre','Inner West','any_other_development','permitted',NULL),

('E1','Local Centre','Inner West','agriculture','prohibited',NULL),
('E1','Local Centre','Inner West','air_transport_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','airstrips','prohibited',NULL),
('E1','Local Centre','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('E1','Local Centre','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','camping_grounds','prohibited',NULL),
('E1','Local Centre','Inner West','caravan_parks','prohibited',NULL),
('E1','Local Centre','Inner West','cemeteries','prohibited',NULL),
('E1','Local Centre','Inner West','correctional_centres','prohibited',NULL),
('E1','Local Centre','Inner West','crematoria','prohibited',NULL),
('E1','Local Centre','Inner West','depots','prohibited',NULL),
('E1','Local Centre','Inner West','eco_tourist_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','exhibition_villages','prohibited',NULL),
('E1','Local Centre','Inner West','extractive_industries','prohibited',NULL),
('E1','Local Centre','Inner West','farm_buildings','prohibited',NULL),
('E1','Local Centre','Inner West','forestry','prohibited',NULL),
('E1','Local Centre','Inner West','freight_transport_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('E1','Local Centre','Inner West','helipads','prohibited',NULL),
('E1','Local Centre','Inner West','highway_service_centres','prohibited',NULL),
('E1','Local Centre','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('E1','Local Centre','Inner West','industrial_training_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','industries','prohibited',NULL),
('E1','Local Centre','Inner West','marinas','prohibited',NULL),
('E1','Local Centre','Inner West','mortuaries','prohibited',NULL),
('E1','Local Centre','Inner West','open_cut_mining','prohibited',NULL),
('E1','Local Centre','Inner West','recreation_facilities_(major)','prohibited',NULL),
('E1','Local Centre','Inner West','registered_clubs','prohibited',NULL),
('E1','Local Centre','Inner West','residential_accommodation','prohibited',NULL),
('E1','Local Centre','Inner West','restricted_premises','prohibited',NULL),
('E1','Local Centre','Inner West','rural_industries','prohibited',NULL),
('E1','Local Centre','Inner West','sewage_treatment_plants','prohibited',NULL),
('E1','Local Centre','Inner West','sex_services_premises','prohibited',NULL),
('E1','Local Centre','Inner West','signage','prohibited',NULL),
('E1','Local Centre','Inner West','storage_premises','prohibited',NULL),
('E1','Local Centre','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('E1','Local Centre','Inner West','transport_depots','prohibited',NULL),
('E1','Local Centre','Inner West','truck_depots','prohibited',NULL),
('E1','Local Centre','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('E1','Local Centre','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('E1','Local Centre','Inner West','waste_disposal_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','waste_or_resource_transfer_stations','prohibited',NULL),
('E1','Local Centre','Inner West','water_storage_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','water_treatment_facilities','prohibited',NULL),
('E1','Local Centre','Inner West','wholesale_supplies','prohibited',NULL),

-- ============================================================
-- E2 Commercial Centre
-- ============================================================
('E2','Commercial Centre','Inner West','home_based_child_care','exempt','Permitted without development consent'),
('E2','Commercial Centre','Inner West','home_occupations','exempt','Permitted without development consent'),

('E2','Commercial Centre','Inner West','amusement_centres','permitted',NULL),
('E2','Commercial Centre','Inner West','artisan_food_and_drink_industries','permitted',NULL),
('E2','Commercial Centre','Inner West','backpackers_accommodation','permitted',NULL),
('E2','Commercial Centre','Inner West','boarding_houses','permitted',NULL),
('E2','Commercial Centre','Inner West','centre_based_child_care_facilities','permitted',NULL),
('E2','Commercial Centre','Inner West','commercial_premises','permitted',NULL),
('E2','Commercial Centre','Inner West','community_facilities','permitted',NULL),
('E2','Commercial Centre','Inner West','entertainment_facilities','permitted',NULL),
('E2','Commercial Centre','Inner West','function_centres','permitted',NULL),
('E2','Commercial Centre','Inner West','hostels','permitted',NULL),
('E2','Commercial Centre','Inner West','hotel_or_motel_accommodation','permitted',NULL),
('E2','Commercial Centre','Inner West','information_and_education_facilities','permitted',NULL),
('E2','Commercial Centre','Inner West','light_industries','permitted',NULL),
('E2','Commercial Centre','Inner West','local_distribution_premises','permitted',NULL),
('E2','Commercial Centre','Inner West','medical_centres','permitted',NULL),
('E2','Commercial Centre','Inner West','mortuaries','permitted',NULL),
('E2','Commercial Centre','Inner West','oyster_aquaculture','permitted',NULL),
('E2','Commercial Centre','Inner West','passenger_transport_facilities','permitted',NULL),
('E2','Commercial Centre','Inner West','places_of_public_worship','permitted',NULL),
('E2','Commercial Centre','Inner West','recreation_areas','permitted',NULL),
('E2','Commercial Centre','Inner West','recreation_facilities_(indoor)','permitted',NULL),
('E2','Commercial Centre','Inner West','recreation_facilities_(outdoor)','permitted',NULL),
('E2','Commercial Centre','Inner West','registered_clubs','permitted',NULL),
('E2','Commercial Centre','Inner West','resource_recovery_facilities','permitted',NULL),
('E2','Commercial Centre','Inner West','respite_day_care_centres','permitted',NULL),
('E2','Commercial Centre','Inner West','restricted_premises','permitted',NULL),
('E2','Commercial Centre','Inner West','shop_top_housing','permitted',NULL),
('E2','Commercial Centre','Inner West','tank_based_aquaculture','permitted',NULL),
('E2','Commercial Centre','Inner West','vehicle_repair_stations','permitted',NULL),
('E2','Commercial Centre','Inner West','veterinary_hospitals','permitted',NULL),
('E2','Commercial Centre','Inner West','any_other_development','permitted',NULL),

('E2','Commercial Centre','Inner West','agriculture','prohibited',NULL),
('E2','Commercial Centre','Inner West','air_transport_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','airstrips','prohibited',NULL),
('E2','Commercial Centre','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('E2','Commercial Centre','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','boat_building_and_repair_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','camping_grounds','prohibited',NULL),
('E2','Commercial Centre','Inner West','caravan_parks','prohibited',NULL),
('E2','Commercial Centre','Inner West','cemeteries','prohibited',NULL),
('E2','Commercial Centre','Inner West','correctional_centres','prohibited',NULL),
('E2','Commercial Centre','Inner West','crematoria','prohibited',NULL),
('E2','Commercial Centre','Inner West','depots','prohibited',NULL),
('E2','Commercial Centre','Inner West','eco_tourist_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','exhibition_homes','prohibited',NULL),
('E2','Commercial Centre','Inner West','exhibition_villages','prohibited',NULL),
('E2','Commercial Centre','Inner West','extractive_industries','prohibited',NULL),
('E2','Commercial Centre','Inner West','farm_buildings','prohibited',NULL),
('E2','Commercial Centre','Inner West','forestry','prohibited',NULL),
('E2','Commercial Centre','Inner West','freight_transport_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('E2','Commercial Centre','Inner West','helipads','prohibited',NULL),
('E2','Commercial Centre','Inner West','highway_service_centres','prohibited',NULL),
('E2','Commercial Centre','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('E2','Commercial Centre','Inner West','industrial_training_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','industries','prohibited',NULL),
('E2','Commercial Centre','Inner West','open_cut_mining','prohibited',NULL),
('E2','Commercial Centre','Inner West','port_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','recreation_facilities_(major)','prohibited',NULL),
('E2','Commercial Centre','Inner West','residential_accommodation','prohibited',NULL),
('E2','Commercial Centre','Inner West','rural_industries','prohibited',NULL),
('E2','Commercial Centre','Inner West','sewage_treatment_plants','prohibited',NULL),
('E2','Commercial Centre','Inner West','storage_premises','prohibited',NULL),
('E2','Commercial Centre','Inner West','transport_depots','prohibited',NULL),
('E2','Commercial Centre','Inner West','truck_depots','prohibited',NULL),
('E2','Commercial Centre','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('E2','Commercial Centre','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('E2','Commercial Centre','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','water_storage_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','water_treatment_facilities','prohibited',NULL),
('E2','Commercial Centre','Inner West','wholesale_supplies','prohibited',NULL),

-- ============================================================
-- E3 Productivity Support
-- ============================================================
-- (no exempt uses)
('E3','Productivity Support','Inner West','animal_boarding_or_training_establishments','permitted',NULL),
('E3','Productivity Support','Inner West','boat_building_and_repair_facilities','permitted',NULL),
('E3','Productivity Support','Inner West','business_premises','permitted',NULL),
('E3','Productivity Support','Inner West','centre_based_child_care_facilities','permitted',NULL),
('E3','Productivity Support','Inner West','community_facilities','permitted',NULL),
('E3','Productivity Support','Inner West','depots','permitted',NULL),
('E3','Productivity Support','Inner West','function_centres','permitted',NULL),
('E3','Productivity Support','Inner West','garden_centres','permitted',NULL),
('E3','Productivity Support','Inner West','hardware_and_building_supplies','permitted',NULL),
('E3','Productivity Support','Inner West','hotel_or_motel_accommodation','permitted',NULL),
('E3','Productivity Support','Inner West','industrial_retail_outlets','permitted',NULL),
('E3','Productivity Support','Inner West','industrial_training_facilities','permitted',NULL),
('E3','Productivity Support','Inner West','information_and_education_facilities','permitted',NULL),
('E3','Productivity Support','Inner West','kiosks','permitted',NULL),
('E3','Productivity Support','Inner West','landscaping_material_supplies','permitted',NULL),
('E3','Productivity Support','Inner West','light_industries','permitted',NULL),
('E3','Productivity Support','Inner West','local_distribution_premises','permitted',NULL),
('E3','Productivity Support','Inner West','markets','permitted',NULL),
('E3','Productivity Support','Inner West','mortuaries','permitted',NULL),
('E3','Productivity Support','Inner West','neighbourhood_shops','permitted',NULL),
('E3','Productivity Support','Inner West','office_premises','permitted',NULL),
('E3','Productivity Support','Inner West','oyster_aquaculture','permitted',NULL),
('E3','Productivity Support','Inner West','passenger_transport_facilities','permitted',NULL),
('E3','Productivity Support','Inner West','places_of_public_worship','permitted',NULL),
('E3','Productivity Support','Inner West','plant_nurseries','permitted',NULL),
('E3','Productivity Support','Inner West','recreation_areas','permitted',NULL),
('E3','Productivity Support','Inner West','recreation_facilities_(indoor)','permitted',NULL),
('E3','Productivity Support','Inner West','recreation_facilities_(major)','permitted',NULL),
('E3','Productivity Support','Inner West','recreation_facilities_(outdoor)','permitted',NULL),
('E3','Productivity Support','Inner West','research_stations','permitted',NULL),
('E3','Productivity Support','Inner West','respite_day_care_centres','permitted',NULL),
('E3','Productivity Support','Inner West','rural_supplies','permitted',NULL),
('E3','Productivity Support','Inner West','service_stations','permitted',NULL),
('E3','Productivity Support','Inner West','specialised_retail_premises','permitted',NULL),
('E3','Productivity Support','Inner West','storage_premises','permitted',NULL),
('E3','Productivity Support','Inner West','take_away_food_and_drink_premises','permitted',NULL),
('E3','Productivity Support','Inner West','tank_based_aquaculture','permitted',NULL),
('E3','Productivity Support','Inner West','timber_yards','permitted',NULL),
('E3','Productivity Support','Inner West','vehicle_body_repair_workshops','permitted',NULL),
('E3','Productivity Support','Inner West','vehicle_repair_stations','permitted',NULL),
('E3','Productivity Support','Inner West','vehicle_sales_or_hire_premises','permitted',NULL),
('E3','Productivity Support','Inner West','veterinary_hospitals','permitted',NULL),
('E3','Productivity Support','Inner West','warehouse_or_distribution_centres','permitted',NULL),
('E3','Productivity Support','Inner West','wholesale_supplies','permitted',NULL),
('E3','Productivity Support','Inner West','any_other_development','permitted',NULL),

('E3','Productivity Support','Inner West','agriculture','prohibited',NULL),
('E3','Productivity Support','Inner West','air_transport_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','airstrips','prohibited',NULL),
('E3','Productivity Support','Inner West','amusement_centres','prohibited',NULL),
('E3','Productivity Support','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','camping_grounds','prohibited',NULL),
('E3','Productivity Support','Inner West','caravan_parks','prohibited',NULL),
('E3','Productivity Support','Inner West','cemeteries','prohibited',NULL),
('E3','Productivity Support','Inner West','charter_and_tourism_boating_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','commercial_premises','prohibited',NULL),
('E3','Productivity Support','Inner West','correctional_centres','prohibited',NULL),
('E3','Productivity Support','Inner West','crematoria','prohibited',NULL),
('E3','Productivity Support','Inner West','eco_tourist_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','electricity_generating_works','prohibited',NULL),
('E3','Productivity Support','Inner West','entertainment_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','environmental_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','exhibition_homes','prohibited',NULL),
('E3','Productivity Support','Inner West','exhibition_villages','prohibited',NULL),
('E3','Productivity Support','Inner West','extractive_industries','prohibited',NULL),
('E3','Productivity Support','Inner West','farm_buildings','prohibited',NULL),
('E3','Productivity Support','Inner West','forestry','prohibited',NULL),
('E3','Productivity Support','Inner West','freight_transport_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','general_industries','prohibited',NULL),
('E3','Productivity Support','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('E3','Productivity Support','Inner West','heavy_industries','prohibited',NULL),
('E3','Productivity Support','Inner West','helipads','prohibited',NULL),
('E3','Productivity Support','Inner West','highway_service_centres','prohibited',NULL),
('E3','Productivity Support','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('E3','Productivity Support','Inner West','marinas','prohibited',NULL),
('E3','Productivity Support','Inner West','mooring_pens','prohibited',NULL),
('E3','Productivity Support','Inner West','moorings','prohibited',NULL),
('E3','Productivity Support','Inner West','open_cut_mining','prohibited',NULL),
('E3','Productivity Support','Inner West','port_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','registered_clubs','prohibited',NULL),
('E3','Productivity Support','Inner West','residential_accommodation','prohibited',NULL),
('E3','Productivity Support','Inner West','resource_recovery_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','restricted_premises','prohibited',NULL),
('E3','Productivity Support','Inner West','rural_industries','prohibited',NULL),
('E3','Productivity Support','Inner West','sewage_treatment_plants','prohibited',NULL),
('E3','Productivity Support','Inner West','sex_services_premises','prohibited',NULL),
('E3','Productivity Support','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('E3','Productivity Support','Inner West','transport_depots','prohibited',NULL),
('E3','Productivity Support','Inner West','truck_depots','prohibited',NULL),
('E3','Productivity Support','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('E3','Productivity Support','Inner West','water_recreation_structures','prohibited',NULL),
('E3','Productivity Support','Inner West','water_supply_systems','prohibited',NULL),
('E3','Productivity Support','Inner West','wharf_or_boating_facilities','prohibited',NULL),

-- ============================================================
-- E4 General Industrial
-- ============================================================
-- (no exempt uses)
('E4','General Industrial','Inner West','agricultural_produce_industries','permitted',NULL),
('E4','General Industrial','Inner West','depots','permitted',NULL),
('E4','General Industrial','Inner West','freight_transport_facilities','permitted',NULL),
('E4','General Industrial','Inner West','garden_centres','permitted',NULL),
('E4','General Industrial','Inner West','general_industries','permitted',NULL),
('E4','General Industrial','Inner West','goods_repair_and_reuse_premises','permitted',NULL),
('E4','General Industrial','Inner West','hardware_and_building_supplies','permitted',NULL),
('E4','General Industrial','Inner West','industrial_retail_outlets','permitted',NULL),
('E4','General Industrial','Inner West','industrial_training_facilities','permitted',NULL),
('E4','General Industrial','Inner West','intensive_plant_agriculture','permitted',NULL),
('E4','General Industrial','Inner West','kiosks','permitted',NULL),
('E4','General Industrial','Inner West','landscaping_material_supplies','permitted',NULL),
('E4','General Industrial','Inner West','light_industries','permitted',NULL),
('E4','General Industrial','Inner West','local_distribution_premises','permitted',NULL),
('E4','General Industrial','Inner West','markets','permitted',NULL),
('E4','General Industrial','Inner West','neighbourhood_shops','permitted',NULL),
('E4','General Industrial','Inner West','oyster_aquaculture','permitted',NULL),
('E4','General Industrial','Inner West','take_away_food_and_drink_premises','permitted',NULL),
('E4','General Industrial','Inner West','tank_based_aquaculture','permitted',NULL),
('E4','General Industrial','Inner West','timber_yards','permitted',NULL),
('E4','General Industrial','Inner West','warehouse_or_distribution_centres','permitted',NULL),
('E4','General Industrial','Inner West','any_other_development','permitted',NULL),

('E4','General Industrial','Inner West','agriculture','prohibited',NULL),
('E4','General Industrial','Inner West','air_transport_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','airstrips','prohibited',NULL),
('E4','General Industrial','Inner West','amusement_centres','prohibited',NULL),
('E4','General Industrial','Inner West','camping_grounds','prohibited',NULL),
('E4','General Industrial','Inner West','caravan_parks','prohibited',NULL),
('E4','General Industrial','Inner West','cemeteries','prohibited',NULL),
('E4','General Industrial','Inner West','commercial_premises','prohibited',NULL),
('E4','General Industrial','Inner West','community_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','correctional_centres','prohibited',NULL),
('E4','General Industrial','Inner West','crematoria','prohibited',NULL),
('E4','General Industrial','Inner West','early_education_and_care_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','eco_tourist_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','educational_establishments','prohibited',NULL),
('E4','General Industrial','Inner West','environmental_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','exhibition_homes','prohibited',NULL),
('E4','General Industrial','Inner West','exhibition_villages','prohibited',NULL),
('E4','General Industrial','Inner West','extractive_industries','prohibited',NULL),
('E4','General Industrial','Inner West','farm_buildings','prohibited',NULL),
('E4','General Industrial','Inner West','forestry','prohibited',NULL),
('E4','General Industrial','Inner West','function_centres','prohibited',NULL),
('E4','General Industrial','Inner West','health_services_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('E4','General Industrial','Inner West','heavy_industries','prohibited',NULL),
('E4','General Industrial','Inner West','helipads','prohibited',NULL),
('E4','General Industrial','Inner West','highway_service_centres','prohibited',NULL),
('E4','General Industrial','Inner West','home_businesses','prohibited',NULL),
('E4','General Industrial','Inner West','home_occupations','prohibited',NULL),
('E4','General Industrial','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('E4','General Industrial','Inner West','information_and_education_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','marinas','prohibited',NULL),
('E4','General Industrial','Inner West','open_cut_mining','prohibited',NULL),
('E4','General Industrial','Inner West','port_facilities','prohibited',NULL),
('E4','General Industrial','Inner West','public_administration_buildings','prohibited',NULL),
('E4','General Industrial','Inner West','recreation_facilities_(major)','prohibited',NULL),
('E4','General Industrial','Inner West','recreation_facilities_(outdoor)','prohibited',NULL),
('E4','General Industrial','Inner West','registered_clubs','prohibited',NULL),
('E4','General Industrial','Inner West','research_stations','prohibited',NULL),
('E4','General Industrial','Inner West','residential_accommodation','prohibited',NULL),
('E4','General Industrial','Inner West','respite_day_care_centres','prohibited',NULL),
('E4','General Industrial','Inner West','restricted_premises','prohibited',NULL),
('E4','General Industrial','Inner West','rural_industries','prohibited',NULL),
('E4','General Industrial','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('E4','General Industrial','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('E4','General Industrial','Inner West','water_recreation_structures','prohibited',NULL),
('E4','General Industrial','Inner West','water_supply_systems','prohibited',NULL),

-- ============================================================
-- MU1 Mixed Use
-- ============================================================
('MU1','Mixed Use','Inner West','home_occupations','exempt','Permitted without development consent'),

('MU1','Mixed Use','Inner West','amusement_centres','permitted',NULL),
('MU1','Mixed Use','Inner West','boarding_houses','permitted',NULL),
('MU1','Mixed Use','Inner West','car_parks','permitted',NULL),
('MU1','Mixed Use','Inner West','centre_based_child_care_facilities','permitted',NULL),
('MU1','Mixed Use','Inner West','commercial_premises','permitted',NULL),
('MU1','Mixed Use','Inner West','community_facilities','permitted',NULL),
('MU1','Mixed Use','Inner West','entertainment_facilities','permitted',NULL),
('MU1','Mixed Use','Inner West','function_centres','permitted',NULL),
('MU1','Mixed Use','Inner West','hostels','permitted',NULL),
('MU1','Mixed Use','Inner West','information_and_education_facilities','permitted',NULL),
('MU1','Mixed Use','Inner West','light_industries','permitted',NULL),
('MU1','Mixed Use','Inner West','local_distribution_premises','permitted',NULL),
('MU1','Mixed Use','Inner West','medical_centres','permitted',NULL),
('MU1','Mixed Use','Inner West','oyster_aquaculture','permitted',NULL),
('MU1','Mixed Use','Inner West','passenger_transport_facilities','permitted',NULL),
('MU1','Mixed Use','Inner West','places_of_public_worship','permitted',NULL),
('MU1','Mixed Use','Inner West','recreation_areas','permitted',NULL),
('MU1','Mixed Use','Inner West','recreation_facilities_(indoor)','permitted',NULL),
('MU1','Mixed Use','Inner West','registered_clubs','permitted',NULL),
('MU1','Mixed Use','Inner West','respite_day_care_centres','permitted',NULL),
('MU1','Mixed Use','Inner West','restricted_premises','permitted',NULL),
('MU1','Mixed Use','Inner West','shop_top_housing','permitted',NULL),
('MU1','Mixed Use','Inner West','tank_based_aquaculture','permitted',NULL),
('MU1','Mixed Use','Inner West','tourist_and_visitor_accommodation','permitted',NULL),
('MU1','Mixed Use','Inner West','vehicle_repair_stations','permitted',NULL),
('MU1','Mixed Use','Inner West','any_other_development','permitted',NULL),

('MU1','Mixed Use','Inner West','agriculture','prohibited',NULL),
('MU1','Mixed Use','Inner West','air_transport_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','airstrips','prohibited',NULL),
('MU1','Mixed Use','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('MU1','Mixed Use','Inner West','biosolids_treatment_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','boat_building_and_repair_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','boat_launching_ramps','prohibited',NULL),
('MU1','Mixed Use','Inner West','boat_sheds','prohibited',NULL),
('MU1','Mixed Use','Inner West','camping_grounds','prohibited',NULL),
('MU1','Mixed Use','Inner West','caravan_parks','prohibited',NULL),
('MU1','Mixed Use','Inner West','cemeteries','prohibited',NULL),
('MU1','Mixed Use','Inner West','charter_and_tourism_boating_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','correctional_centres','prohibited',NULL),
('MU1','Mixed Use','Inner West','crematoria','prohibited',NULL),
('MU1','Mixed Use','Inner West','depots','prohibited',NULL),
('MU1','Mixed Use','Inner West','eco_tourist_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','environmental_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','exhibition_homes','prohibited',NULL),
('MU1','Mixed Use','Inner West','exhibition_villages','prohibited',NULL),
('MU1','Mixed Use','Inner West','extractive_industries','prohibited',NULL),
('MU1','Mixed Use','Inner West','farm_buildings','prohibited',NULL),
('MU1','Mixed Use','Inner West','forestry','prohibited',NULL),
('MU1','Mixed Use','Inner West','freight_transport_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','heavy_industrial_storage_establishments','prohibited',NULL),
('MU1','Mixed Use','Inner West','helipads','prohibited',NULL),
('MU1','Mixed Use','Inner West','highway_service_centres','prohibited',NULL),
('MU1','Mixed Use','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('MU1','Mixed Use','Inner West','industries','prohibited',NULL),
('MU1','Mixed Use','Inner West','jetties','prohibited',NULL),
('MU1','Mixed Use','Inner West','marinas','prohibited',NULL),
('MU1','Mixed Use','Inner West','mooring_pens','prohibited',NULL),
('MU1','Mixed Use','Inner West','moorings','prohibited',NULL),
('MU1','Mixed Use','Inner West','mortuaries','prohibited',NULL),
('MU1','Mixed Use','Inner West','open_cut_mining','prohibited',NULL),
('MU1','Mixed Use','Inner West','port_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','recreation_facilities_(major)','prohibited',NULL),
('MU1','Mixed Use','Inner West','residential_accommodation','prohibited',NULL),
('MU1','Mixed Use','Inner West','rural_industries','prohibited',NULL),
('MU1','Mixed Use','Inner West','sewage_treatment_plants','prohibited',NULL),
('MU1','Mixed Use','Inner West','sex_services_premises','prohibited',NULL),
('MU1','Mixed Use','Inner West','transport_depots','prohibited',NULL),
('MU1','Mixed Use','Inner West','truck_depots','prohibited',NULL),
('MU1','Mixed Use','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('MU1','Mixed Use','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('MU1','Mixed Use','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('MU1','Mixed Use','Inner West','water_recreation_structures','prohibited',NULL),
('MU1','Mixed Use','Inner West','water_supply_systems','prohibited',NULL),
('MU1','Mixed Use','Inner West','wharf_or_boating_facilities','prohibited',NULL),

-- ============================================================
-- SP1 Special Activities
-- ============================================================
-- (no exempt uses)
('SP1','Special Activities','Inner West','aquaculture','permitted',NULL),
('SP1','Special Activities','Inner West','roads','permitted',NULL),
('SP1','Special Activities','Inner West','purpose_shown_on_zoning_map','permitted','Including development ordinarily incidental or ancillary to that purpose'),

('SP1','Special Activities','Inner West','any_other_development','prohibited',NULL),

-- ============================================================
-- SP2 Infrastructure
-- ============================================================
-- (no exempt uses)
('SP2','Infrastructure','Inner West','aquaculture','permitted',NULL),
('SP2','Infrastructure','Inner West','environmental_protection_works','permitted',NULL),
('SP2','Infrastructure','Inner West','recreation_areas','permitted',NULL),
('SP2','Infrastructure','Inner West','roads','permitted',NULL),
('SP2','Infrastructure','Inner West','purpose_shown_on_zoning_map','permitted','Including development ordinarily incidental or ancillary to that purpose'),

('SP2','Infrastructure','Inner West','any_other_development','prohibited',NULL),

-- ============================================================
-- RE1 Public Recreation
-- ============================================================
('RE1','Public Recreation','Inner West','environmental_protection_works','exempt','Permitted without development consent'),

('RE1','Public Recreation','Inner West','aquaculture','permitted',NULL),
('RE1','Public Recreation','Inner West','boat_launching_ramps','permitted',NULL),
('RE1','Public Recreation','Inner West','boat_sheds','permitted',NULL),
('RE1','Public Recreation','Inner West','building_identification_signs','permitted',NULL),
('RE1','Public Recreation','Inner West','centre_based_child_care_facilities','permitted',NULL),
('RE1','Public Recreation','Inner West','community_facilities','permitted',NULL),
('RE1','Public Recreation','Inner West','electricity_generating_works','permitted',NULL),
('RE1','Public Recreation','Inner West','emergency_services_facilities','permitted',NULL),
('RE1','Public Recreation','Inner West','environmental_facilities','permitted',NULL),
('RE1','Public Recreation','Inner West','flood_mitigation_works','permitted',NULL),
('RE1','Public Recreation','Inner West','food_and_drink_premises','permitted',NULL),
('RE1','Public Recreation','Inner West','information_and_education_facilities','permitted',NULL),
('RE1','Public Recreation','Inner West','jetties','permitted',NULL),
('RE1','Public Recreation','Inner West','kiosks','permitted',NULL),
('RE1','Public Recreation','Inner West','marinas','permitted',NULL),
('RE1','Public Recreation','Inner West','markets','permitted',NULL),
('RE1','Public Recreation','Inner West','recreation_areas','permitted',NULL),
('RE1','Public Recreation','Inner West','recreation_facilities_(indoor)','permitted',NULL),
('RE1','Public Recreation','Inner West','recreation_facilities_(major)','permitted',NULL),
('RE1','Public Recreation','Inner West','recreation_facilities_(outdoor)','permitted',NULL),
('RE1','Public Recreation','Inner West','research_stations','permitted',NULL),
('RE1','Public Recreation','Inner West','respite_day_care_centres','permitted',NULL),
('RE1','Public Recreation','Inner West','roads','permitted',NULL),
('RE1','Public Recreation','Inner West','water_recreation_structures','permitted',NULL),
('RE1','Public Recreation','Inner West','water_recycling_facilities','permitted',NULL),
('RE1','Public Recreation','Inner West','water_supply_systems','permitted',NULL),
('RE1','Public Recreation','Inner West','wharf_or_boating_facilities','permitted',NULL),

('RE1','Public Recreation','Inner West','pubs','prohibited',NULL),
('RE1','Public Recreation','Inner West','any_other_development','prohibited',NULL),

-- ============================================================
-- RE2 Private Recreation
-- ============================================================
('RE2','Private Recreation','Inner West','environmental_protection_works','exempt','Permitted without development consent'),

('RE2','Private Recreation','Inner West','aquaculture','permitted',NULL),
('RE2','Private Recreation','Inner West','boat_launching_ramps','permitted',NULL),
('RE2','Private Recreation','Inner West','boat_sheds','permitted',NULL),
('RE2','Private Recreation','Inner West','building_identification_signs','permitted',NULL),
('RE2','Private Recreation','Inner West','business_identification_signs','permitted',NULL),
('RE2','Private Recreation','Inner West','centre_based_child_care_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','community_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','entertainment_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','environmental_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','flood_mitigation_works','permitted',NULL),
('RE2','Private Recreation','Inner West','food_and_drink_premises','permitted',NULL),
('RE2','Private Recreation','Inner West','information_and_education_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','jetties','permitted',NULL),
('RE2','Private Recreation','Inner West','kiosks','permitted',NULL),
('RE2','Private Recreation','Inner West','marinas','permitted',NULL),
('RE2','Private Recreation','Inner West','markets','permitted',NULL),
('RE2','Private Recreation','Inner West','places_of_public_worship','permitted',NULL),
('RE2','Private Recreation','Inner West','recreation_areas','permitted',NULL),
('RE2','Private Recreation','Inner West','recreation_facilities_(indoor)','permitted',NULL),
('RE2','Private Recreation','Inner West','recreation_facilities_(major)','permitted',NULL),
('RE2','Private Recreation','Inner West','recreation_facilities_(outdoor)','permitted',NULL),
('RE2','Private Recreation','Inner West','registered_clubs','permitted',NULL),
('RE2','Private Recreation','Inner West','respite_day_care_centres','permitted',NULL),
('RE2','Private Recreation','Inner West','roads','permitted',NULL),
('RE2','Private Recreation','Inner West','water_recreation_structures','permitted',NULL),
('RE2','Private Recreation','Inner West','water_recycling_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','water_storage_facilities','permitted',NULL),
('RE2','Private Recreation','Inner West','wharf_or_boating_facilities','permitted',NULL),

('RE2','Private Recreation','Inner West','pubs','prohibited',NULL),
('RE2','Private Recreation','Inner West','small_bars','prohibited',NULL),
('RE2','Private Recreation','Inner West','any_other_development','prohibited',NULL),

-- ============================================================
-- W1 Natural Waterways
-- ============================================================
('W1','Natural Waterways','Inner West','environmental_protection_works','exempt','Permitted without development consent'),

('W1','Natural Waterways','Inner West','aquaculture','permitted',NULL),
('W1','Natural Waterways','Inner West','boat_launching_ramps','permitted',NULL),
('W1','Natural Waterways','Inner West','boat_sheds','permitted',NULL),
('W1','Natural Waterways','Inner West','environmental_facilities','permitted',NULL),
('W1','Natural Waterways','Inner West','flood_mitigation_works','permitted',NULL),
('W1','Natural Waterways','Inner West','jetties','permitted',NULL),
('W1','Natural Waterways','Inner West','marinas','permitted',NULL),
('W1','Natural Waterways','Inner West','mooring_pens','permitted',NULL),
('W1','Natural Waterways','Inner West','moorings','permitted',NULL),
('W1','Natural Waterways','Inner West','water_recreation_structures','permitted',NULL),

('W1','Natural Waterways','Inner West','business_premises','prohibited',NULL),
('W1','Natural Waterways','Inner West','hotel_or_motel_accommodation','prohibited',NULL),
('W1','Natural Waterways','Inner West','industries','prohibited',NULL),
('W1','Natural Waterways','Inner West','local_distribution_premises','prohibited',NULL),
('W1','Natural Waterways','Inner West','multi_dwelling_housing','prohibited',NULL),
('W1','Natural Waterways','Inner West','recreation_facilities_(major)','prohibited',NULL),
('W1','Natural Waterways','Inner West','residential_flat_buildings','prohibited',NULL),
('W1','Natural Waterways','Inner West','restricted_premises','prohibited',NULL),
('W1','Natural Waterways','Inner West','retail_premises','prohibited',NULL),
('W1','Natural Waterways','Inner West','seniors_housing','prohibited',NULL),
('W1','Natural Waterways','Inner West','service_stations','prohibited',NULL),
('W1','Natural Waterways','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('W1','Natural Waterways','Inner West','any_other_development','prohibited',NULL),

-- ============================================================
-- W2 Recreational Waterways
-- ============================================================
('W2','Recreational Waterways','Inner West','environmental_protection_works','exempt','Permitted without development consent'),

('W2','Recreational Waterways','Inner West','aquaculture','permitted',NULL),
('W2','Recreational Waterways','Inner West','boat_building_and_repair_facilities','permitted',NULL),
('W2','Recreational Waterways','Inner West','boat_launching_ramps','permitted',NULL),
('W2','Recreational Waterways','Inner West','boat_sheds','permitted',NULL),
('W2','Recreational Waterways','Inner West','building_identification_signs','permitted',NULL),
('W2','Recreational Waterways','Inner West','environmental_facilities','permitted',NULL),
('W2','Recreational Waterways','Inner West','flood_mitigation_works','permitted',NULL),
('W2','Recreational Waterways','Inner West','jetties','permitted',NULL),
('W2','Recreational Waterways','Inner West','kiosks','permitted',NULL),
('W2','Recreational Waterways','Inner West','marinas','permitted',NULL),
('W2','Recreational Waterways','Inner West','recreation_areas','permitted',NULL),
('W2','Recreational Waterways','Inner West','water_recreation_structures','permitted',NULL),

('W2','Recreational Waterways','Inner West','industries','prohibited',NULL),
('W2','Recreational Waterways','Inner West','local_distribution_premises','prohibited',NULL),
('W2','Recreational Waterways','Inner West','multi_dwelling_housing','prohibited',NULL),
('W2','Recreational Waterways','Inner West','residential_flat_buildings','prohibited',NULL),
('W2','Recreational Waterways','Inner West','seniors_housing','prohibited',NULL),
('W2','Recreational Waterways','Inner West','warehouse_or_distribution_centres','prohibited',NULL),
('W2','Recreational Waterways','Inner West','any_other_development','prohibited',NULL),

-- ============================================================
-- W4 Working Waterfront
-- ============================================================
-- (no exempt uses)
('W4','Working Waterfront','Inner West','aquaculture','permitted',NULL),
('W4','Working Waterfront','Inner West','boat_building_and_repair_facilities','permitted',NULL),
('W4','Working Waterfront','Inner West','boat_launching_ramps','permitted',NULL),
('W4','Working Waterfront','Inner West','building_identification_signs','permitted',NULL),
('W4','Working Waterfront','Inner West','business_identification_signs','permitted',NULL),
('W4','Working Waterfront','Inner West','jetties','permitted',NULL),
('W4','Working Waterfront','Inner West','kiosks','permitted',NULL),
('W4','Working Waterfront','Inner West','light_industries','permitted',NULL),
('W4','Working Waterfront','Inner West','any_other_development','permitted',NULL),

('W4','Working Waterfront','Inner West','agriculture','prohibited',NULL),
('W4','Working Waterfront','Inner West','air_transport_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','airstrips','prohibited',NULL),
('W4','Working Waterfront','Inner West','amusement_centres','prohibited',NULL),
('W4','Working Waterfront','Inner West','animal_boarding_or_training_establishments','prohibited',NULL),
('W4','Working Waterfront','Inner West','camping_grounds','prohibited',NULL),
('W4','Working Waterfront','Inner West','car_parks','prohibited',NULL),
('W4','Working Waterfront','Inner West','caravan_parks','prohibited',NULL),
('W4','Working Waterfront','Inner West','cemeteries','prohibited',NULL),
('W4','Working Waterfront','Inner West','commercial_premises','prohibited',NULL),
('W4','Working Waterfront','Inner West','crematoria','prohibited',NULL),
('W4','Working Waterfront','Inner West','early_education_and_care_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','eco_tourist_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','educational_establishments','prohibited',NULL),
('W4','Working Waterfront','Inner West','entertainment_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','environmental_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','exhibition_homes','prohibited',NULL),
('W4','Working Waterfront','Inner West','exhibition_villages','prohibited',NULL),
('W4','Working Waterfront','Inner West','extractive_industries','prohibited',NULL),
('W4','Working Waterfront','Inner West','farm_buildings','prohibited',NULL),
('W4','Working Waterfront','Inner West','forestry','prohibited',NULL),
('W4','Working Waterfront','Inner West','freight_transport_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','function_centres','prohibited',NULL),
('W4','Working Waterfront','Inner West','health_services_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','helipads','prohibited',NULL),
('W4','Working Waterfront','Inner West','highway_service_centres','prohibited',NULL),
('W4','Working Waterfront','Inner West','home_businesses','prohibited',NULL),
('W4','Working Waterfront','Inner West','home_occupations','prohibited',NULL),
('W4','Working Waterfront','Inner West','home_occupations_(sex_services)','prohibited',NULL),
('W4','Working Waterfront','Inner West','industrial_retail_outlets','prohibited',NULL),
('W4','Working Waterfront','Inner West','industries','prohibited',NULL),
('W4','Working Waterfront','Inner West','marinas','prohibited',NULL),
('W4','Working Waterfront','Inner West','mortuaries','prohibited',NULL),
('W4','Working Waterfront','Inner West','open_cut_mining','prohibited',NULL),
('W4','Working Waterfront','Inner West','port_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','recreation_areas','prohibited',NULL),
('W4','Working Waterfront','Inner West','recreation_facilities_(indoor)','prohibited',NULL),
('W4','Working Waterfront','Inner West','recreation_facilities_(major)','prohibited',NULL),
('W4','Working Waterfront','Inner West','recreation_facilities_(outdoor)','prohibited',NULL),
('W4','Working Waterfront','Inner West','registered_clubs','prohibited',NULL),
('W4','Working Waterfront','Inner West','residential_accommodation','prohibited',NULL),
('W4','Working Waterfront','Inner West','restricted_premises','prohibited',NULL),
('W4','Working Waterfront','Inner West','rural_industries','prohibited',NULL),
('W4','Working Waterfront','Inner West','service_stations','prohibited',NULL),
('W4','Working Waterfront','Inner West','sewerage_systems','prohibited',NULL),
('W4','Working Waterfront','Inner West','sex_services_premises','prohibited',NULL),
('W4','Working Waterfront','Inner West','signage','prohibited',NULL),
('W4','Working Waterfront','Inner West','storage_premises','prohibited',NULL),
('W4','Working Waterfront','Inner West','tourist_and_visitor_accommodation','prohibited',NULL),
('W4','Working Waterfront','Inner West','transport_depots','prohibited',NULL),
('W4','Working Waterfront','Inner West','truck_depots','prohibited',NULL),
('W4','Working Waterfront','Inner West','vehicle_body_repair_workshops','prohibited',NULL),
('W4','Working Waterfront','Inner West','vehicle_repair_stations','prohibited',NULL),
('W4','Working Waterfront','Inner West','veterinary_hospitals','prohibited',NULL),
('W4','Working Waterfront','Inner West','waste_or_resource_management_facilities','prohibited',NULL),
('W4','Working Waterfront','Inner West','water_recreation_structures','prohibited',NULL),
('W4','Working Waterfront','Inner West','water_supply_systems','prohibited',NULL),
('W4','Working Waterfront','Inner West','wholesale_supplies','prohibited',NULL)

ON CONFLICT (zone, lga, development_type) DO UPDATE
    SET permissibility = EXCLUDED.permissibility,
        zone_name      = EXCLUDED.zone_name,
        notes          = EXCLUDED.notes;

-- ============================================================
-- 3. lep_zone_coverage — mark all 16 zones as complete
-- ============================================================
INSERT INTO public.lep_zone_coverage (zone, lga, is_complete, notes) VALUES
('R1',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('R2',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('R3',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('R4',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('E1',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('E2',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('E3',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('E4',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('MU1', 'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('SP1', 'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('SP2', 'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('RE1', 'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('RE2', 'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('W1',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('W2',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20'),
('W4',  'Inner West', true, 'Inner West LEP 2022 (epi-2022-0457) Schedule 1 — verified 2026-03-20')
ON CONFLICT (zone, lga) DO UPDATE
    SET is_complete = EXCLUDED.is_complete,
        notes       = EXCLUDED.notes;
