-- 075: seed dcp_clause_sibling_citations with Wingecarribee's 28 verified citations (companion to 074).
--
-- prior-art-checked: 074 creates the table; this file carries its data so a fresh, staging or restored database gets
-- the same citations production has, and DQ-66 (declared fixed) holds there too. Without it the table would be empty
-- everywhere but production and every Wingecarribee number would fall back to the one-town caveat.
--
-- Each row was located on 2026-09-15 in our R2 copies of the Mittagong and Moss Vale town plans (each hash-matched to
-- dcp_chapter_registry.content_hash): the clause code starts on or just before the recorded page, and every number of
-- every served control citing the clause is printed on it. sibling_excerpt is that page's own text.
-- Idempotent: ON CONFLICT DO NOTHING on the table's one-per-sibling key.
--
-- Blank identifiers are refused (cross-review 2026-09-15). 074 required them NOT NULL only, so a row with an empty
-- sibling clause could satisfy DQ-66 while the served citation silently left that plan out. Added here, not in 074,
-- because 074 is already applied to production; each constraint is added only if absent.

DO $$
DECLARE
    col text;
BEGIN
    FOREACH col IN ARRAY ARRAY['council', 'chapter_key', 'section_ref', 'sibling_chapter_key', 'sibling_section_ref'] LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
             WHERE conname = 'dcp_clause_sibling_citations_' || col || '_not_blank'
               AND conrelid = 'dcp_clause_sibling_citations'::regclass
        ) THEN
            EXECUTE format('ALTER TABLE dcp_clause_sibling_citations ADD CONSTRAINT %I CHECK (btrim(%I) <> %L)',
                           'dcp_clause_sibling_citations_' || col || '_not_blank', col, '');
        END IF;
    END LOOP;
END
$$;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.12.2(f)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s2/C2.12.2(f)$sib$, 193,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 189 of 319 (b) In established residential areas, the location of new garages should reflect the current garage location pattern. (c) Where possible, garages should not impede solar access to key internal and external living areas. (d) Where possible, garages should offer linkages between on-site open space areas. C2.12.2 Specific Controls All applications for residential development shall comply with the following controls: (a) Where garages form part of the dwelling they shall not exceed 40% of the total width of the dwelling frontage to a maximum width of six (6) metres. (b) The height of the garage shall not exceed the height of the principal dwelling. (c) Double garages are only permitted on allotments of at least 12.5 metres in width. (d) Triple fronted garages are not permitted where they face directly on to the street. (e) The garage shall be set back from the front façade and designed so that the dwelling entry and façade are the dominant building features. (f) New development shall provide a minimum of two car spaces behind the building line which may include an access way to the side of the dwelling of a minimum width of 2700mm. (g) Garages shall be designed and located to minimise adverse solar impacts. (h) Driveways are to be located a minimum of 1.5 metres from the nearest street tree. (i) The vehicular crossing point to the garage from the street shall be located to reflect the existing vehicular access point pattern in the street. Applicants are directed to Council’s relevant Endorsed Technical Specifications. (j) The width of the driveway at the street shall reflect the current streetscape. Council’s Customer Services Branch can provide the standard driveway design details. (k) The width of the driveway on site shall not exceed the width of the garage opening and shall reflect the surface material currently in the streetscape. (l) Where possible, hard surfaces shall be softened through landscaping and material treatment. C2.13 Private Landscaped Open Space Useable private landscaped open space is an essential element of residential development. Private open space serves a number of functions - separation between adjacent dwellings, visual and acoustic buffering, areas for planting and opportunities for various forms of outdoor passive and active recreation. Back yards,$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C2.12.2 starts on page 193; every number of served control(s) [1157] ([Decimal('2')]) is printed on page 193.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.12.2(f)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s2/C2.12.2(f)$sib$, 198,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 194 of 283 (b) In established residential areas, the location of new garages should reflect the current garage location pattern. (c) Where possible, garages should not impede solar access to key internal and external living areas. (d) Where possible, garages should offer linkages between on-site open space areas. C2.12.2 Specific Controls All applications for residential development shall comply with the following controls: (a) Where garages form part of the dwelling they shall not exceed 40% of the total width of the dwelling frontage to a maximum width of six (6) metres. (b) The height of the garage shall not exceed the height of the principal dwelling. (c) Double garages are only permitted on allotments of at least 12.5 metres in width. (d) Triple fronted garages are not permitted where they face directly on to the street. (e) The garage shall be set back from the front façade and designed so that the dwelling entry and façade are the dominant building features. (f) New development shall provide a minimum of two car spaces behind the building line which may include an access way to the side of the dwelling of a minimum width of 2700mm. (g) Garages shall be designed and located to minimise adverse solar impacts. (h) Driveways are to be located a minimum of 1.5 metres from the nearest street tree. (i) The vehicular crossing point to the garage from the street shall be located to reflect the existing vehicular access point pattern in the street. Applicants are directed to Council’s relevant Endorsed Technical Specifications. (j) The width of the driveway at the street shall reflect the current streetscape. Council’s Customer Services Branch can provide the standard driveway design details. (k) The width of the driveway on site shall not exceed the width of the garage opening and shall reflect the surface material currently in the streetscape. (l) Where possible, hard surfaces shall be softened through landscaping and material treatment. C2.13 Private Landscaped Open Space Useable private landscaped open space is an essential element of residential development. Private open space serves a number of functions - separation between adjacent dwellings, visual and acoustic buffering, areas for planting and opportunities for various forms of outdoor passive and active recreation. Back yards,$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C2.12.2 starts on page 198; every number of served control(s) [1157] ([Decimal('2')]) is printed on page 198.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.13.2(a)-Table-C2.2$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s2/C2.13.2(a)-Table-C2.1$sib$, 195,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 191 of 319 (g) Provides useable open space, located to maximise solar access. (h) Allows for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (i) Ensures that the dimensions of verandahs and porches are sufficient to make a legitimate contribution to private open space. (j) Ensures ease of movement between living areas of dwellings and private open space. (k) Provides sufficient site area to support mature trees and vegetation and allow for water infiltration. (l) Creates attractive, landscaped front gardens that include a number of small trees and shrubs. (m) Encourages the use of the front garden and front of dwelling spaces such as verandahs and porches, for both active and passive recreation. C2.13.2 Specific Controls (a) Low density residential development, including additions and alterations to existing dwellings, shall meet the following minimum private landscaped open space standards. Lot size Minimum Private Landscaped Open Space Maximum Development Footprint Less than 2,000m² 35% of the site area or 90m2, whichever is the greater. 65% of the site area Less than 2,000m2 on a site which is an Item of Heritage or located within a Heritage Conservation Area 50% of the site area 50% of the site area Between 2,000m² and 4,000m² 50% of the site area 50% of the site area Over 4,000m² 75% of the site area 25% of the site area Table C2.1 Minimum Private Landscaped Open Space Standards (b) Development, alterations or additions to existing buildings, on any site which is, or is in the vicinity of, an Item of Heritage or is within a Heritage$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C2.13.2 starts on page 195; every number of served control(s) [1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156] ([Decimal('35'), Decimal('50'), Decimal('50'), Decimal('75'), Decimal('65'), Decimal('50'), Decimal('50'), Decimal('25')]) is printed on page 195.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.13.2(a)-Table-C2.2$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s2/C2.13.2(a)-Table-C2.1$sib$, 200,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 196 of 283 (g) Provides useable open space, located to maximise solar access. (h) Allows for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (i) Ensures that the dimensions of verandahs and porches are sufficient to make a legitimate contribution to private open space. (j) Ensures ease of movement between living areas of dwellings and private open space. (k) Provides sufficient site area to support mature trees and vegetation and allow for water infiltration. (l) Creates attractive, landscaped front gardens that include a number of small trees and shrubs. (m) Encourages the use of the front garden and front of dwelling spaces such as verandahs and porches, for both active and passive recreation. C2.13.2 Specific Controls (a) Low density residential development, including additions and alterations to existing dwellings, shall meet the following minimum private landscaped open space standards. Lot size Minimum Private Landscaped Open Space Maximum Development Footprint Less than 2,000m² 35% of the site area or 90m2, whichever is the greater. 65% of the site area Less than 2,000m2 on a site which is an Item of Heritage or located within a Heritage Conservation Area 50% of the site area 50% of the site area Between 2,000m² and 4,000m² 50% of the site area 50% of the site area Over 4,000m² 75% of the site area 25% of the site area Table C2.1 Minimum Private Landscaped Open Space Standards (b) Development, alterations or additions to existing buildings, on any site which is, or is in the vicinity of, an Item of Heritage or is within a Heritage Conservation Area, shall provide A Landscape Plan prepared by a person considered by Council to be suitably qualified for such a task which: (i) maps and identifies the plantings of any private open space on the development site.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C2.13.2 starts on page 200; every number of served control(s) [1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156] ([Decimal('35'), Decimal('50'), Decimal('50'), Decimal('75'), Decimal('65'), Decimal('50'), Decimal('50'), Decimal('25')]) is printed on page 200.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.6.2(e)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s2/C2.6.2(e)$sib$, 188,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 184 of 319 C2.6.2 Specific Controls All applications for residential development shall comply with the following controls: (a) Front setbacks of new residential development shall be consistent with those of the dwellings immediately adjacent to the site and to those in the immediate vicinity. (b) Where properties immediately adjacent to the proposed development do not feature a consistent front setback, the following guidelines will apply: (c) If the difference between existing front setbacks is 2 metres or greater, new dwellings shall adopt a setback within the range established by adjacent dwellings. (d) If the difference between existing front setbacks is greater than 2 metres, the new dwellings shall adopt an average of the existing setbacks. (e) In general, subject to site assessment, Council requires the following front setbacks, exclusive of garage setbacks: Lot size Minimum front setback Less than 900m² 4.5m Between 900m² and 1500m² 6.5m Over 1500m² 15m (f) Proposals that seek to vary these front setback controls may do so only if it can be demonstrated to the satisfaction of Council that the proposed variation: (i) will enhance the quality of the existing streetscape, and (ii) will not compromise the amenity of any proposed or existing dwellings immediately adjacent to the proposed development. (iii) Where it is common practice in the streetscape to have some variation in the alignment of the front setback, new development should complement this pattern. C2.7 Side Setbacks Side setbacks provide separation between adjacent dwellings, contributing to the quality of the overall streetscape as well as ensuring privacy, ventilation and solar access between dwellings. C2.7.1 Objectives The side setbacks controls below are intended to achieve the following objectives:$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C2.6.2 starts on page 188; every number of served control(s) [1138, 1139, 1140] ([Decimal('4.5'), Decimal('6.5'), Decimal('15.0')]) is printed on page 188.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.6.2(e)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s2/C2.6.2(e)$sib$, 193,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 189 of 283 C2.6.2 Specific Controls All applications for residential development shall comply with the following controls: (a) Front setbacks of new residential development shall be consistent with those of the dwellings immediately adjacent to the site and to those in the immediate vicinity. (b) Where properties immediately adjacent to the proposed development do not feature a consistent front setback, the following guidelines will apply: (c) If the difference between existing front setbacks is 2 metres or greater, new dwellings shall adopt a setback within the range established by adjacent dwellings. (d) If the difference between existing front setbacks is greater than 2 metres, the new dwellings shall adopt an average of the existing setbacks. (e) In general, subject to site assessment, Council requires the following front setbacks, exclusive of garage setbacks: Lot size Minimum front setback Less than 900m² 4.5m Between 900m² and 1500m² 6.5m Over 1500m² 15m (f) Proposals that seek to vary these front setback controls may do so only if it can be demonstrated to the satisfaction of Council that the proposed variation: (i) will enhance the quality of the existing streetscape, and (ii) will not compromise the amenity of any proposed or existing dwellings immediately adjacent to the proposed development. (iii) Where it is common practice in the streetscape to have some variation in the alignment of the front setback, new development should complement this pattern. C2.7 Side Setbacks Side setbacks provide separation between adjacent dwellings, contributing to the quality of the overall streetscape as well as ensuring privacy, ventilation and solar access between dwellings. C2.7.1 Objectives The side setbacks controls below are intended to achieve the following objectives:$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C2.6.2 starts on page 193; every number of served control(s) [1138, 1139, 1140] ([Decimal('4.5'), Decimal('6.5'), Decimal('15.0')]) is printed on page 193.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.7.2(c)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s2/C2.7.2(c)$sib$, 189,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 185 of 319 (g) Provide adequate building separation between new and existing development for the purposes of privacy, ventilation, fire safety and solar access. (h) Provide space between dwellings to maintain the detached housing character and for individual identity and visual interest. (i) Ensure consistent patterns of built and unbuilt spaces within the streetscape. (j) Offer opportunities for deep soil areas and landscaping. C2.7.2 Specific Controls All applications for residential development shall comply with the following controls: (a) Side setbacks of new development will be generally consistent with those of immediately adjacent existing development. (b) Where the side setbacks of immediately adjacent existing development are inconsistent, Council will assess the proposed setbacks of the new development on merit, taking into consideration potential impacts on: (i) The character of the existing streetscape; (ii) Privacy of the proposed dwellings and existing adjacent dwellings; (iii) Solar access to the proposed dwellings and existing dwellings. (iv) Building Code of Australia issues relating to Fire Safety. (c) In general, subject to site assessment, Council requires the following side setbacks: Lot size Minimum required side setback Less than 900m² 0.9m Between 900m² and 1500m² 1.5m Over 1500m² 2.5m C2.8 Rear Setbacks Rear setbacks provide private open space opportunities for both passive and active recreation. Such spaces also provide contiguous areas of mid block tree canopy and significant areas of deep soil. C2.8.1 Objectives The objectives of providing adequate rear setbacks are to: (a) provide private open space for both active and passive recreation which has good solar access. (b) Ensure sufficient area on the site for mature trees and vegetation.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C2.7.2 starts on page 189; every number of served control(s) [1141, 1142, 1143] ([Decimal('0.9'), Decimal('1.5'), Decimal('2.5')]) is printed on page 189.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.7.2(c)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s2/C2.7.2(c)$sib$, 194,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 190 of 283 (g) Provide adequate building separation between new and existing development for the purposes of privacy, ventilation, fire safety and solar access. (h) Provide space between dwellings to maintain the detached housing character and for individual identity and visual interest. (i) Ensure consistent patterns of built and unbuilt spaces within the streetscape. (j) Offer opportunities for deep soil areas and landscaping. C2.7.2 Specific Controls All applications for residential development shall comply with the following controls: (a) Side setbacks of new development will be generally consistent with those of immediately adjacent existing development. (b) Where the side setbacks of immediately adjacent existing development are inconsistent, Council will assess the proposed setbacks of the new development on merit, taking into consideration potential impacts on: (i) The character of the existing streetscape; (ii) Privacy of the proposed dwellings and existing adjacent dwellings; (iii) Solar access to the proposed dwellings and existing dwellings. (iv) Building Code of Australia issues relating to Fire Safety. (c) In general, subject to site assessment, Council requires the following side setbacks: Lot size Minimum required side setback Less than 900m² 0.9m Between 900m² and 1500m² 1.5m Over 1500m² 2.5m C2.8 Rear Setbacks Rear setbacks provide private open space opportunities for both passive and active recreation. Such spaces also provide contiguous areas of mid block tree canopy and significant areas of deep soil. C2.8.1 Objectives The objectives of providing adequate rear setbacks are to: (a) provide private open space for both active and passive recreation which has good solar access. (b) Ensure sufficient area on the site for mature trees and vegetation.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C2.7.2 starts on page 194; every number of served control(s) [1141, 1142, 1143] ([Decimal('0.9'), Decimal('1.5'), Decimal('2.5')]) is printed on page 194.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.8.2(c)-(d)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s2/C2.8.2(c)-(d)$sib$, 190,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 186 of 319 (c) Ensure mid block tree canopy can be established or conserved. C2.8.2 Specific Controls All applications for residential development must comply with the following controls: (a) Rear setbacks of new development will be generally consistent with those of existing adjacent development. (b) In the case of inconsistent rear setbacks in the immediate vicinity of the proposed development, Council will assess the proposed setbacks of the new development on merit, taking into consideration impacts on: (i) Existing vegetation and natural features on the site; (ii) Privacy of the proposed dwellings and existing dwellings; (iii) Solar access to the proposed dwellings and existing dwellings. (c) In general, subject to site assessment, Council requires the following rear setbacks: Lot size Minimum Required rear setback Less than 900m² 3.0m -8.0m depending on building height Between 900m² and 1500m² 5.0m – 12.0 depending on building height Over 1500m² 10m – 15m depending on building height (d) Applicants are advised that the minimum rear setback increases on a sliding scale once the building height at the rear of the dwelling exceeds 3.8m. In this case, the rear setback is calculated as the minimum rear setback for the relevant lot size plus three times the height of the rear of the dwelling which exceeds 3.8m. C2.9 Building Height The existing Mittagong residential environment currently reflects a low scale domestic character. New developments which propose to significantly exceed the height of existing residential development would be detrimental to the retention of that character and would not be supported by Council. Such development can also create overshadowing and privacy issues. C2.9.1 Objectives Height constraints are intended to ensure that the following objectives are achieved: (a) Retention of a low scale domestic residential character, (b) Minimal overshadowing of neighbouring properties by new development, (c) Minimal disruption to the views of existing and future development,$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C2.8.2 starts on page 190; every number of served control(s) [1144, 1145, 1146] ([Decimal('3.0'), Decimal('5.0'), Decimal('10.0'), Decimal('8.0'), Decimal('12.0'), Decimal('15.0')]) is printed on page 190.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s2/C2.8.2(c)-(d)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s2/C2.8.2(c)-(d)$sib$, 195,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 2 DETACHED DWELLINGS & ASSOCIATED DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 191 of 283 (c) Ensure mid block tree canopy can be established or conserved. C2.8.2 Specific Controls All applications for residential development must comply with the following controls: (a) Rear setbacks of new development will be generally consistent with those of existing adjacent development. (b) In the case of inconsistent rear setbacks in the immediate vicinity of the proposed development, Council will assess the proposed setbacks of the new development on merit, taking into consideration impacts on: (i) Existing vegetation and natural features on the site; (ii) Privacy of the proposed dwellings and existing dwellings; (iii) Solar access to the proposed dwellings and existing dwellings. (c) In general, subject to site assessment, Council requires the following rear setbacks: Lot size Minimum Required rear setback Less than 900m² 3.0m -8.0m depending on building height Between 900m² and 1500m² 5.0m – 12.0 depending on building height Over 1500m² 10m – 15m depending on building height (d) Applicants are advised that the minimum rear setback increases on a sliding scale once the building height at the rear of the dwelling exceeds 3.8m. In this case, the rear setback is calculated as the minimum rear setback for the relevant lot size plus three times the height of the rear of the dwelling which exceeds 3.8m. C2.9 Building Height The existing Moss Vale residential environment currently reflects a low scale domestic character. New developments which propose to significantly exceed the height of existing residential development would be detrimental to the retention of that character and would not be supported by Council. Such development can also create overshadowing and privacy issues. C2.9.1 Objectives Height constraints are intended to ensure that the following objectives are achieved: (a) Retention of a low scale domestic residential character, (b) Minimal overshadowing of neighbouring properties by new development, (c) Minimal disruption to the views of existing and future development,$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C2.8.2 starts on page 195; every number of served control(s) [1144, 1145, 1146] ([Decimal('3.0'), Decimal('5.0'), Decimal('10.0'), Decimal('8.0'), Decimal('12.0'), Decimal('15.0')]) is printed on page 195.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.13.2(b)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s3/C3.13.2(b)$sib$, 211,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 207 of 319 (a) Provide all new dwellings with useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C3.13.2 Development Controls (a) All dwellings must have a consolidated principal (main) private open space area; (b) All dwellings must provide a minimum private open space area of 50 m² with a minimum length of 5 metres; (c) Private open space must be located to maximise solar access; (d) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (e) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C3.14 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) 50 per cent (50%) of any site developed for multi dwelling housing shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) In calculating the total area of Landscaped Open Space, the following areas shall be included: i. Paths ii. Patios iii. Soft landscaping areas c) In calculating the total area of Landscaped Open Space, the following areas shall be excluded: i. Building footprint ii. Driveways iii. Car parking iv. Garbage storage areas and the like d) Landscaped open space shall provide outdoor entertainment areas for resident use; e) In each case where multi dwelling housing is erected on a site having a frontage to a public road, public place or public open space, Council shall$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C3.13.2 starts on page 211; every number of served control(s) [1161] ([Decimal('50')]) is printed on page 211.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.13.2(b)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s3/C3.13.2(b)$sib$, 217,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 213 of 283 Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C3.13.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide all new dwellings with useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C3.13.2 Development Controls (a) All dwellings must have a consolidated principal (main) private open space area; (b) All dwellings must provide a minimum private open space area of 50 m² with a minimum length of 5 metres; (c) Private open space must be located to maximise solar access; (d) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (e) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C3.14 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) 50 per cent (50%) of any site developed for multi dwelling housing shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) In calculating the total area of Landscaped Open Space, the following areas shall be included: i. Paths ii. Patios iii. Soft landscaping areas c) In calculating the total area of Landscaped Open Space, the following areas shall be excluded:$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C3.13.2 starts on page 217; every number of served control(s) [1161] ([Decimal('50')]) is printed on page 217.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.14(a)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s3/C3.14(a)$sib$, 211,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 207 of 319 (a) Provide all new dwellings with useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C3.13.2 Development Controls (a) All dwellings must have a consolidated principal (main) private open space area; (b) All dwellings must provide a minimum private open space area of 50 m² with a minimum length of 5 metres; (c) Private open space must be located to maximise solar access; (d) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (e) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C3.14 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) 50 per cent (50%) of any site developed for multi dwelling housing shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) In calculating the total area of Landscaped Open Space, the following areas shall be included: i. Paths ii. Patios iii. Soft landscaping areas c) In calculating the total area of Landscaped Open Space, the following areas shall be excluded: i. Building footprint ii. Driveways iii. Car parking iv. Garbage storage areas and the like d) Landscaped open space shall provide outdoor entertainment areas for resident use; e) In each case where multi dwelling housing is erected on a site having a frontage to a public road, public place or public open space, Council shall$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C3.14 starts on page 211; every number of served control(s) [1162] ([Decimal('50')]) is printed on page 211.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.14(a)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s3/C3.14(a)$sib$, 217,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 213 of 283 Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C3.13.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide all new dwellings with useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C3.13.2 Development Controls (a) All dwellings must have a consolidated principal (main) private open space area; (b) All dwellings must provide a minimum private open space area of 50 m² with a minimum length of 5 metres; (c) Private open space must be located to maximise solar access; (d) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (e) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C3.14 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) 50 per cent (50%) of any site developed for multi dwelling housing shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) In calculating the total area of Landscaped Open Space, the following areas shall be included: i. Paths ii. Patios iii. Soft landscaping areas c) In calculating the total area of Landscaped Open Space, the following areas shall be excluded:$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C3.14 starts on page 217; every number of served control(s) [1162] ([Decimal('50')]) is printed on page 217.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.17.2(a)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s3/C3.17.2(a)$sib$, 214,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 210 of 319 (c) To minimise the impact of garages, parking areas and areas for vehicular circulation with medium density developments. C3.17.2 Development Controls (a) Off street parking will be provided at the following rates: (i) Dedicated resident parking at a rate of 1 space per 1 and 2 bedroom dwellings (ii) Dedicated resident parking at a rate of 2 spaces per 3 or more bedroom dwellings (iii) Dedicated visitor parking at a rate of 1 space per 3 dwellings (rounded up to the nearest whole number) (b) Council shall require additional visitor parking spaces to be provided in areas where opportunities for on-street visitor parking are deemed to be insufficient. (c) The width of driveways will be limited to 25% of the frontage to a public street but meet the minimum requirements of standard drawings SD107 for single driveways and SD168 for other driveways as shown in Part A of this Plan. (d) Garages will be located so they do not dominate the streetscape. (e) Where garages form part of the dwelling, they shall be located at least 1.2 metres behind the main building façade and should not exceed more than 40% of the dwelling frontage. (f) Double garages to the street frontage shall be avoided in preference to tandem parking or single garage and car port options. (g) Unrelieved 'gun barrel' driveways will not be permitted. If the alignment of internal access ways cannot be varied, visual relief will be provided by appropriate planting. (h) Where possible, changes in level across a site will be used to provide basement or sub-basement garaging. C3.18 Pedestrian Access The design of medium and high density developments and the location of private entrances to individual dwellings are important in providing a sense of individual identity for each dwelling and to ensure that passive surveillance is available to each dwelling from surrounding dwellings. All new development should provide clear and direct pedestrian access from the dwelling or dwellings to a public street or public space. Applicants are reminded to consult Section A5 for Safer by Design guidelines. C3.18.1 Objectives The controls described below are intended to achieve the following objectives:$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C3.17.2 starts on page 214; every number of served control(s) [1163, 1164] ([Decimal('1'), Decimal('2')]) is printed on page 214.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.17.2(a)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s3/C3.17.2(a)$sib$, 220,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 216 of 283 C3.17.1 Objectives The controls described below are intended to achieve the following objectives: (a) To provide adequate off street parking for residents and visitors. (b) To minimise the dominance of garages and driveways in the streetscape. (c) To minimise the impact of garages, parking areas and areas for vehicular circulation with medium density developments. C3.17.2 Development Controls (a) Off street parking will be provided at the following rates: (i) Dedicated resident parking at a rate of 1 space per 1 and 2 bedroom dwellings (ii) Dedicated resident parking at a rate of 2 spaces per 3 or more bedroom dwellings (iii) Dedicated visitor parking at a rate of 1 space per 3 dwellings (rounded up to the nearest whole number) (b) Council shall require additional visitor parking spaces to be provided in areas where opportunities for on-street visitor parking are deemed to be insufficient. (c) The width of driveways will be limited to 25% of the frontage to a public street but meet the minimum requirements of standard drawings SD107 for single driveways and SD168 for other driveways as shown in Part A of this Plan. (d) Garages will be located so they do not dominate the streetscape. (e) Where garages form part of the dwelling, they shall be located at least 1.2 metres behind the main building façade and should not exceed more than 40% of the dwelling frontage. (f) Double garages to the street frontage shall be avoided in preference to tandem parking or single garage and car port options. (g) Unrelieved 'gun barrel' driveways will not be permitted. If the alignment of internal access ways cannot be varied, visual relief will be provided by appropriate planting. (h) Where possible, changes in level across a site will be used to provide basement or sub-basement garaging. C3.18 Pedestrian Access The design of medium and high density developments and the location of private entrances to individual dwellings are important in providing a sense of individual identity for each dwelling and to ensure that passive surveillance is available to each dwelling from surrounding dwellings. All new development should provide clear and$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C3.17.2 starts on page 220; every number of served control(s) [1163, 1164] ([Decimal('1'), Decimal('2')]) is printed on page 220.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.8.2(c)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s3/C3.8.2(c)$sib$, 206,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 202 of 319 Due to the variety of front setbacks contributing to existing streetscapes, this Plan uses a contextual approach to establish front setbacks. New development should adopt front setbacks similar to those of existing adjacent dwellings, or of relevance in the immediate vicinity. C3.8.1 Objectives The controls described below are intended to achieve the following objectives: (a) Ensure the front setback of new infill development is consistent with the existing streetscape. (b) Preserve existing vegetation in front gardens. (c) Provide areas for trees and vegetation to enhance the streetscape and provide privacy. C3.8.2 Specific Controls (a) Front setbacks of new development will be consistent with those of the dwellings immediately adjacent to the site and to those in the immediate vicinity. (b) Where properties immediately adjacent to the proposed development do not feature a consistent front setback: (i) If the difference between existing front setbacks is 2 metres or greater, new dwellings can adopt a setback within the range established by adjacent dwellings; (ii) If the difference between existing front setbacks is greater than 2 metres, the new dwellings will adopt an average of the existing setbacks; (c) In the case where there are inconsistent setbacks immediately adjacent to the site, or in the immediate vicinity of the proposed development, or there are no dwellings immediately adjacent to, or in the vicinity of the proposed development, Council will assess the proposed front setback on merit. To date, the accepted standard has been 8 metres. (d) Secondary setbacks on corner blocks will be the subject of a contextual approach and will generally be half the requirement of the primary setback. (e) Proposals that seek to vary the front setback controls may do so only if it can be demonstrated to the satisfaction of Council that the proposed variation: (i) will enhance the quality of the existing streetscape, and (ii) will not compromise amenity of the any proposed or existing dwellings immediately adjacent to the proposed development. (f) Where it is common practice in the streetscape to have some variation in the alignment of the front setback, new development should reflect this pattern.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C3.8.2 starts on page 206; every number of served control(s) [1158] ([Decimal('8.0')]) is printed on page 206.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.8.2(c)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s3/C3.8.2(c)$sib$, 213,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 209 of 283 development, Council will assess the proposed front setback on merit. To date, the accepted standard has been 8 metres. (d) Secondary setbacks on corner blocks will be the subject of a contextual approach and will generally be half the requirement of the primary setback. (e) Proposals that seek to vary the front setback controls may do so only if it can be demonstrated to the satisfaction of Council that the proposed variation: (i) will enhance the quality of the existing streetscape, and (ii) will not compromise amenity of the any proposed or existing dwellings immediately adjacent to the proposed development. (f) Where it is common practice in the streetscape to have some variation in the alignment of the front setback, new development should reflect this pattern. Figure C3.7 If the difference between existing front setbacks is 2 metres or greater, new dwellings can adopt a setback within the range established by adjacent dwellings. If the difference between existing front setbacks is greater than 2 metres, new dwellings will adopt an average of the existing setbacks. Where it is common practice in the streetscape to have some variation in the alignment of the front setback, new development should reflect this pattern. C3.9 Side Setbacks Side setbacks provide separation between adjacent dwellings, permit access to back yards and facilitate solar access to proposed and adjoining dwellings. The dimension and use of areas in side setbacks are important character elements in the$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C3.8.2 starts on page 212; every number of served control(s) [1158] ([Decimal('8.0')]) is printed on page 213.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.9.2(c)(i)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s3/C3.9.2(c)(i)$sib$, 208,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Mittagong Town Plan – Effective 17 June 2015 PART C | Page 204 of 319 C3.9.2 Specific Controls (a) Side setbacks of new development will be generally consistent with those of existing development in the immediate adjacent context (see Figure C4.9 below). (b) Where there are inconsistent side setbacks in the immediate context of the proposed development, Council will assess the proposed setbacks of the new development on merit, taking into consideration potential impacts on: (i) The character of the existing streetscape; (ii) Privacy of the proposed dwellings and existing adjacent dwellings; (iii) Solar access to the proposed dwellings and existing dwellings. (iv) Building Code of Australia issues relating to Fire Safety. (c) Notwithstanding the above controls, Council’s standard minimum side setbacks are: (i) Two (2) metres where development is up to 3 metres in height above natural ground level, or (ii) 3.5 metres where development is more than metres in height above natural ground level. Figure C3.10 New development should maintain the existing pattern of separation between buildings C3.10 Rear Setbacks Rear setbacks provide private open space opportunities for both passive and active recreation. Such spaces also provide contiguous areas of mid block tree canopy and significant areas of deep soil. C3.10.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide opportunities for active and passive open space that are both private and allow good solar access. (b) Ensure sufficient area on the site for mature trees and vegetation. (c) Ensure mid block tree canopy can be established or conserved.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C3.9.2 starts on page 208; every number of served control(s) [1159] ([Decimal('2.0')]) is printed on page 208.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s3/C3.9.2(c)(i)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s3/C3.9.2(c)(i)$sib$, 214,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 3 MEDIUM DENSITY DEVELOPMENT Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 210 of 283 streetscape. New development should adopt side setbacks similar to those of existing dwellings in the immediate context. C3.9.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide adequate building separation between new and existing development for privacy, ventilation, fire safety and solar access (b) Provide breaks between dwellings that give individual identity and visual interest, and maintain the detached housing character. (c) Ensure consistent patterns of built and unbuilt spaces within the streetscape. (d) Provide sufficient area on the site for deep soil areas and landscaping. C3.9.2 Specific Controls (a) Side setbacks of new development will be generally consistent with those of existing development in the immediate adjacent context (see Figure C3.8 below). (b) Where there are inconsistent side setbacks in the immediate context of the proposed development, Council will assess the proposed setbacks of the new development on merit, taking into consideration potential impacts on: (i) The character of the existing streetscape; (ii) Privacy of the proposed dwellings and existing adjacent dwellings; (iii) Solar access to the proposed dwellings and existing dwellings. (iv) Building Code of Australia issues relating to Fire Safety. (c) Notwithstanding the above controls, Council’s standard minimum side setbacks are: (i) Two (2) metres where development is up to 3 metres in height above natural ground level, or (ii) 3.5 metres where development is more than metres in height above natural ground level. Figure C3.8 New development should maintain the existing pattern of separation between buildings$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C3.9.2 starts on page 214; every number of served control(s) [1159] ([Decimal('2.0')]) is printed on page 214.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.4.2(b)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s4/C4.4.2(b)$sib$, 220,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Mittagong Town Plan – Effective 17 June 2015 PART C | Page 216 of 319 C4.4 Private Open Space Useable private open space is an essential requirement for all dwellings, particularly residential flat development. When designing new residential developments, the location, orientation and configuration of private open space should all be considered. Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C4.4.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C4.4.2 Development Controls (a) All flats must have a principal private open space area; (b) All ground floor flats must provide a minimum private open space area of 30 m² with a minimum length of 4 metres; (c) All above ground floor flats must provide a minimum private open space area of 15 m² with a minimum length of 3 metres; (d) Private open space must be located to maximise solar access; (e) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (f) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C4.5 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) Fifty per cent (50%) of any site developed for a residential flat building shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C4.4.2 starts on page 220; every number of served control(s) [1165] ([Decimal('30')]) is printed on page 220.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.4.2(b)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s4/C4.4.2(b)$sib$, 227,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 223 of 283 Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C4.4.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C4.4.2 Development Controls (a) All flats must have a principal private open space area; (b) All ground floor flats must provide a minimum private open space area of 30 m² with a minimum length of 4 metres; (c) All above ground floor flats must provide a minimum private open space area of 15 m² with a minimum length of 3 metres; (d) Private open space must be located to maximise solar access; (e) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (f) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C4.5 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) Fifty per cent (50%) of any site developed for a residential flat building shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) Landscaped open space shall provide outdoor entertainment areas for resident use; c) In each case where a residential flat building is erected on a site having a frontage to a public road, public place or public open space, Council shall require an appropriate treatment of boundaries to those frontages and the whole of the site which remains undeveloped;$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C4.4.2 starts on page 227; every number of served control(s) [1165] ([Decimal('30')]) is printed on page 227.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.4.2(c)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s4/C4.4.2(c)$sib$, 220,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Mittagong Town Plan – Effective 17 June 2015 PART C | Page 216 of 319 C4.4 Private Open Space Useable private open space is an essential requirement for all dwellings, particularly residential flat development. When designing new residential developments, the location, orientation and configuration of private open space should all be considered. Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C4.4.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C4.4.2 Development Controls (a) All flats must have a principal private open space area; (b) All ground floor flats must provide a minimum private open space area of 30 m² with a minimum length of 4 metres; (c) All above ground floor flats must provide a minimum private open space area of 15 m² with a minimum length of 3 metres; (d) Private open space must be located to maximise solar access; (e) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (f) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C4.5 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) Fifty per cent (50%) of any site developed for a residential flat building shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C4.4.2 starts on page 220; every number of served control(s) [1166] ([Decimal('15')]) is printed on page 220.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.4.2(c)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s4/C4.4.2(c)$sib$, 227,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 223 of 283 Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C4.4.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C4.4.2 Development Controls (a) All flats must have a principal private open space area; (b) All ground floor flats must provide a minimum private open space area of 30 m² with a minimum length of 4 metres; (c) All above ground floor flats must provide a minimum private open space area of 15 m² with a minimum length of 3 metres; (d) Private open space must be located to maximise solar access; (e) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (f) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C4.5 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) Fifty per cent (50%) of any site developed for a residential flat building shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) Landscaped open space shall provide outdoor entertainment areas for resident use; c) In each case where a residential flat building is erected on a site having a frontage to a public road, public place or public open space, Council shall require an appropriate treatment of boundaries to those frontages and the whole of the site which remains undeveloped;$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C4.4.2 starts on page 227; every number of served control(s) [1166] ([Decimal('15')]) is printed on page 227.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.5(a)$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s4/C4.5(a)$sib$, 220,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Mittagong Town Plan – Effective 17 June 2015 PART C | Page 216 of 319 C4.4 Private Open Space Useable private open space is an essential requirement for all dwellings, particularly residential flat development. When designing new residential developments, the location, orientation and configuration of private open space should all be considered. Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C4.4.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C4.4.2 Development Controls (a) All flats must have a principal private open space area; (b) All ground floor flats must provide a minimum private open space area of 30 m² with a minimum length of 4 metres; (c) All above ground floor flats must provide a minimum private open space area of 15 m² with a minimum length of 3 metres; (d) Private open space must be located to maximise solar access; (e) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (f) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C4.5 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) Fifty per cent (50%) of any site developed for a residential flat building shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C4.5 starts on page 220; every number of served control(s) [1167] ([Decimal('50')]) is printed on page 220.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.5(a)$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s4/C4.5(a)$sib$, 227,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 223 of 283 Rear and side setback areas, courtyards and balconies are all forms of private open space. Areas within the front setback may also be used as private open space, provided that these areas are carefully designed to ensure adequate privacy without presenting solid high walls to the street. C4.4.1 Objectives The controls described below are intended to achieve the following objectives: (a) Provide useable open space, located to maximise solar access. (b) Allow for both passive and active recreation in private open space areas by providing a combination of hard surface, landscaping and deep soil areas. (c) Ensure ease of movement between living areas of dwellings and private open space. C4.4.2 Development Controls (a) All flats must have a principal private open space area; (b) All ground floor flats must provide a minimum private open space area of 30 m² with a minimum length of 4 metres; (c) All above ground floor flats must provide a minimum private open space area of 15 m² with a minimum length of 3 metres; (d) Private open space must be located to maximise solar access; (e) Private open space must allow for a variety of activities by providing a combination of hard surface, landscaping and deep soil areas. (f) The primary private open space should be located adjacent to, and be immediately accessible from, the primary living area. C4.5 Landscaping and Communal Open Space Applicants are reminded to address the landscaping requirements contained in Section 6 of Part A of this Plan as well as the specific controls below: a) Fifty per cent (50%) of any site developed for a residential flat building shall be landscaped to the satisfaction of Council. Landscaping shall be in accordance with a detailed landscaping plan submitted to Council at the Development Application stage and approved by Council prior to the issue of a Construction Certificate; b) Landscaped open space shall provide outdoor entertainment areas for resident use; c) In each case where a residential flat building is erected on a site having a frontage to a public road, public place or public open space, Council shall require an appropriate treatment of boundaries to those frontages and the whole of the site which remains undeveloped;$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C4.5 starts on page 227; every number of served control(s) [1167] ([Decimal('50')]) is printed on page 227.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.6$sib$, $sib$wingecarribee-mittagong-town-plan$sib$,
    $sib$part-c-s4/C4.6$sib$, 221,
    $sib$MITTAGONG TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Mittagong Town Plan – Effective 17 June 2015 PART C | Page 217 of 319 b) Landscaped open space shall provide outdoor entertainment areas for resident use; c) In each case where a residential flat building is erected on a site having a frontage to a public road, public place or public open space, Council shall require an appropriate treatment of boundaries to those frontages and the whole of the site which remains undeveloped; d) Such treatment may include the planting of trees, shrubs, plants and lawns (the species of which may be specified by Council), the erection of fences, walls and screens, or the exclusion thereof; e) The area of the site between the building line and the street alignment shall be devoid of any structure, concrete area, or hard standing surface other than that which is necessary to gain access to the residential flat building; f) Garbage collection receptacles are to be located to the satisfaction of Council and are to be designed and screened so as to be screened from any public road, public place or public open space; g) A tradesman’s toilet, independent of a sole occupancy unit, will be required where 10 or more units are envisaged on a site. The toilet shall be appropriately screened from any public road, public place or public open space. C4.6 Off-street Parking (a) Off street parking will be provided at the following rates: (b) Dedicated resident parking at a rate of 1 space per 1 and 2 bedroom dwellings (c) Dedicated resident parking at a rate of 2 spaces per 3 or more bedroom dwellings (d) Dedicated visitor parking at a rate of 1 space per 3 dwellings (rounded up to the nearest whole number) (e) Council may require additional visitor parking spaces to be provided in areas where opportunities for on-street visitor parking are deemed to be insufficient. (f) The width of driveways will be limited to 25% of the frontage to a public street but meet the minimum requirements of standard drawings SD107. (g) No parking space, covered or uncovered, shall be provided between the building line and the frontage to the site. At least one parking space per dwelling shall be a covered parking space. (h) Where garages are provided or where any wall abuts a parking space and dimensions of the car parking space shall be greater than otherwise required, a minimum width of 3.6 metres shall apply to any single undercover garage. Adequate clearance and additional impact reinforcement to buildings will apply where undercover car parking is envisaged. (i) In the case of a residential flat building requiring in excess of four car parking spaces with a common access way, sufficient space shall be provided so that no reverse manoeuvre onto a road is required.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Mittagong Town Plan (as amended 17 Jun 2015) (sha256 510613c46ede): clause C4.6 starts on page 221; every number of served control(s) [1168, 1169] ([Decimal('1'), Decimal('2')]) is printed on page 221.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

INSERT INTO dcp_clause_sibling_citations (council, chapter_key, section_ref, sibling_chapter_key, sibling_section_ref,
    sibling_pdf_page, sibling_excerpt, verified_note)
VALUES ($sib$wingecarribee$sib$, $sib$wingecarribee-bowral-town-plan$sib$, $sib$part-c-s4/C4.6$sib$, $sib$wingecarribee-moss-vale-town-plan$sib$,
    $sib$part-c-s4/C4.6$sib$, 228,
    $sib$MOSS VALE TOWN PLAN DCP PART C RESIDENTIAL ZONED LAND SECTION 4 RESIDENTIAL FLAT BUILDINGS Moss Vale Town Plan – Effective 17 June 2015 PART C | Page 224 of 283 d) Such treatment may include the planting of trees, shrubs, plants and lawns (the species of which may be specified by Council), the erection of fences, walls and screens, or the exclusion thereof; e) The area of the site between the building line and the street alignment shall be devoid of any structure, concrete area, or hard standing surface other than that which is necessary to gain access to the residential flat building; f) Garbage collection receptacles are to be located to the satisfaction of Council and are to be designed and screened so as to be screened from any public road, public place or public open space; g) A tradesman’s toilet, independent of a sole occupancy unit, will be required where 10 or more units are envisaged on a site. The toilet shall be appropriately screened from any public road, public place or public open space. C4.6 Off-street Parking (a) Off street parking will be provided at the following rates: (b) Dedicated resident parking at a rate of 1 space per 1 and 2 bedroom dwellings (c) Dedicated resident parking at a rate of 2 spaces per 3 or more bedroom dwellings (d) Dedicated visitor parking at a rate of 1 space per 3 dwellings (rounded up to the nearest whole number) (e) Council may require additional visitor parking spaces to be provided in areas where opportunities for on-street visitor parking are deemed to be insufficient. (f) The width of driveways will be limited to 25% of the frontage to a public street but meet the minimum requirements of standard drawings SD107. (g) No parking space, covered or uncovered, shall be provided between the building line and the frontage to the site. At least one parking space per dwelling shall be a covered parking space. (h) Where garages are provided or where any wall abuts a parking space and dimensions of the car parking space shall be greater than otherwise required, a minimum width of 3.6 metres shall apply to any single undercover garage. Adequate clearance and additional impact reinforcement to buildings will apply where undercover car parking is envisaged. (i) In the case of a residential flat building requiring in excess of four car parking spaces with a common access way, sufficient space shall be provided so that no reverse manoeuvre onto a road is required. (j) Except where the Roads and Traffic Authority or Police require otherwise, access driveways and manoeuvring areas shall be the minimum widths and other dimensions as outlined in Council’s relevant technical specifications. (k) Suitable means of physical separation of driveways and parking areas from landscaped open areas shall be provided to prevent indiscriminate vehicular movement upon such areas.$sib$,
    $sib$Located 2026-09-15 in our R2 copy of the Moss Vale Town Plan (as amended 17 Jun 2015) (sha256 8bd923d9eb62): clause C4.6 starts on page 228; every number of served control(s) [1168, 1169] ([Decimal('1'), Decimal('2')]) is printed on page 228.$sib$)
ON CONFLICT (council, chapter_key, section_ref, sibling_chapter_key) DO NOTHING;

-- The sibling plans' own R2 copies, so each sibling citation can link its plan (the Bowral chapter already has one).
UPDATE dcp_chapter_registry
   SET r2_public_pdf_url = 'https://pub-7f3b945f2f0045d6991a6b9d6db51cd8.r2.dev/' || r2_current_path
 WHERE council = 'wingecarribee' AND is_active AND r2_public_pdf_url IS NULL
   AND chapter_key IN ('wingecarribee-mittagong-town-plan', 'wingecarribee-moss-vale-town-plan')
   AND r2_current_path IS NOT NULL;
