-- DQ-142: building-area controls quoted from stored DCP text or the registered PDF (2 rows).
-- Generated by scripts/dq142_build_controls_migration.py from dq142_controls_bayside_2026-10-10.json:
-- every quote was found verbatim in its named, current stored provision and
-- every figure inside its quote before this file was written. Controls with no
-- fixed figure (a formula, or 'match the neighbours') store the DCP's words with
-- condition 'NO FIGURE: ...'. Where a rule rises with storeys or site width the
-- MINIMUM is stored and the rest is in condition, as existing rows do; the
-- buildable-area arithmetic is an upper bound and the minimum keeps it one.
-- VERIFY: python scripts/dq_probe_live.py --id DQ-142

BEGIN;

INSERT INTO dcp_setback_controls
  (lga, dev_type, control_type, value_min, value_max, unit, condition, applicability,
   source_text, section_ref, dcp_version, is_current, extraction_method, source_chapter_key,
   pdf_page, citation_status, needs_review, zones_include)
VALUES
  ('bayside', 'secondary_dwelling', 'front_setback', NULL, NULL, NULL, 'NO FIGURE: outbuildings, including secondary dwellings, located behind the main street face of the development', 'universal_residential', 'Outbuildings are to be located behind the main street face of the development. ... These controls primarily relate to secondary dwellings', '5.1.2 General C4', 'Bayside DCP 2022 Amendment 2 (April 2026)', TRUE, 'manual_curation', 'bayside-dcp-2022-part3', 191, 'unjudged', FALSE, NULL),
  ('bayside', 'secondary_dwelling', 'landscaping_min', 25, NULL, '%', 'of the site area; secondary dwellings must not cause non-compliance with the minimum landscaped area (5.1.2 C2)', 'universal_residential', 'Low and medium density residential 25% ... Outbuildings are not to result in non- compliances relating to minimum landscaped area, private open space, overshadowing, privacy and other relevant ... These controls primarily relate to secondary dwellings', '3.7 C12 Table 7; 5.1.2 C2', 'Bayside DCP 2022 Amendment 2 (April 2026)', TRUE, 'manual_curation', 'bayside-dcp-2022-part3', 87, 'unjudged', FALSE, NULL);

COMMIT;
