export interface GrannyFlatLgaData {
  name: string
  slug: string
  heritageCount: number
  hasFloodData: boolean
  hasAriData: boolean
  /** Geographically adjacent LGAs in the same tool set */
  relatedSlugs: string[]
  faqs: Array<{ q: string; a: string }>
}

export const GRANNY_FLAT_LGAS: GrannyFlatLgaData[] = [
  {
    name: 'Campbelltown',
    slug: 'campbelltown',
    heritageCount: 116,
    hasFloodData: true,
    hasAriData: true,
    relatedSlugs: ['camden', 'liverpool', 'sutherland-shire'],
    faqs: [
      { q: 'Can I build a granny flat in Campbelltown?', a: 'Yes — many Campbelltown properties qualify under SEPP Housing 2021. The minimum lot size is 450 m² and the property must not be a heritage item, flood control lot, or affected by biodiversity or acid sulfate soil exclusions. R1, R2, R3, and RU5 zones are generally permitted. Use the checker above to confirm your specific address.' },
      { q: 'What is the minimum lot size for a granny flat in Campbelltown?', a: 'The minimum lot size under SEPP Housing 2021 is 450 m². Campbelltown has a mix of lot sizes — many post-war suburban lots are 550–700 m² and qualify. Newer estate lots under 450 m² do not qualify for complying development.' },
      { q: 'Does flood risk affect granny flat approvals in Campbelltown?', a: 'Yes. Campbelltown has detailed ARI flood data — properties on flood control lots (within the 1% AEP zone) are ineligible for a CDC secondary dwelling. A DA with a flood risk management report is required. Check flood status above before proceeding.' },
      { q: 'Do I need council approval for a granny flat in Campbelltown?', a: 'If your property passes all SEPP Housing 2021 checks, you can lodge a complying development certificate (CDC) through a private certifier — no council DA required. If any check fails, you need a DA through Campbelltown City Council.' },
      { q: 'How large can a granny flat be in Campbelltown?', a: 'Under SEPP Housing 2021, secondary dwellings are limited to 60 m² internal floor area. On lots over 900 m², attached secondary dwellings may be permitted up to a different size. DCP setbacks and height limits also apply.' },
    ],
  },
  {
    name: 'Hawkesbury',
    slug: 'hawkesbury',
    heritageCount: 604,
    hasFloodData: true,
    hasAriData: true,
    relatedSlugs: ['penrith', 'the-hills-shire', 'blacktown'],
    faqs: [
      { q: 'Can I build a granny flat in Hawkesbury?', a: 'Many Hawkesbury properties qualify, but flood exclusions are significant. The Hawkesbury-Nepean catchment has extensive flood mapping — properties within flood control lots are ineligible for CDC secondary dwellings. Check your address above to see the full picture.' },
      { q: 'How does flooding affect granny flat eligibility in Hawkesbury?', a: 'Hawkesbury has one of NSW\'s most significant flood risks. The 2024 Hawkesbury-Nepean River Flood Study maps 12 ARI scenarios. Properties within the 1% AEP (1-in-100-year) flood extent are on flood control lots and cannot use the CDC pathway for secondary dwellings.' },
      { q: 'What heritage restrictions affect granny flats in Hawkesbury?', a: 'Hawkesbury has 604 heritage items including significant colonial-era properties around Windsor, Richmond, and Wilberforce. Properties that are heritage items are excluded from SEPP Housing 2021 complying development. Conservation area properties may also face restrictions.' },
      { q: 'What lot size is needed for a granny flat in Hawkesbury?', a: 'The SEPP Housing 2021 minimum is 450 m². Rural-residential lots in Hawkesbury are typically large enough, but some town lots in Windsor and Richmond may be closer to the minimum. Check your specific lot area using the checker above.' },
      { q: 'Do I need a DA for a granny flat in Hawkesbury?', a: 'If the CDC eligibility check passes (lot size, zone, heritage, flood all clear), you can lodge through a private certifier without a council DA. If any check fails — particularly flood — a DA through Hawkesbury City Council is required.' },
    ],
  },
  {
    name: 'Inner West',
    slug: 'inner-west',
    heritageCount: 2039,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['bayside', 'canterbury-bankstown', 'lane-cove'],
    faqs: [
      { q: 'Can I build a granny flat in the Inner West?', a: 'Yes, if your property meets the SEPP Housing 2021 criteria. The Inner West has many R2 and R3 zoned properties over 450 m² that qualify. However, with 2,039 heritage items, heritage exclusions are a common reason for ineligibility. Check your address above.' },
      { q: 'Why might my Inner West property be ineligible for a granny flat?', a: 'The most common exclusions in the Inner West are: heritage listing (heritage item or conservation area), lot under 450 m², or a zone that doesn\'t permit secondary dwellings. Flood exclusions are less common but possible near creek lines in Marrickville and Leichhardt.' },
      { q: 'Does heritage listing affect granny flat eligibility in the Inner West?', a: 'Yes. The Inner West has 2,039 heritage items — the highest count of any LGA in our coverage. Properties that are heritage items or within heritage conservation areas are excluded from SEPP Housing 2021 complying development. A DA is required instead.' },
      { q: 'What lot size is needed for a granny flat in the Inner West?', a: 'The minimum under SEPP Housing 2021 is 450 m². Many Inner West terrace houses sit on lots of 200–350 m² and are ineligible on lot size alone. Semi-detached homes and detached houses on larger blocks are more likely to qualify.' },
      { q: 'How large can a granny flat be in the Inner West?', a: 'Secondary dwellings under SEPP Housing 2021 are capped at 60 m² internal floor area. Inner West Council\'s DCP also imposes setback requirements — rear setbacks, side setbacks, and height limits all apply and must be checked before designing.' },
    ],
  },
  {
    name: 'Canterbury-Bankstown',
    slug: 'canterbury-bankstown',
    heritageCount: 274,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['bayside', 'inner-west', 'georges-river'],
    faqs: [
      { q: 'Can I build a granny flat in Canterbury-Bankstown?', a: 'Many properties in Canterbury-Bankstown qualify — the area has a large stock of R2 residential lots over 450 m². Heritage exclusions are less common than in inner-city suburbs. Check your address above to confirm zone, lot area, and any exclusions.' },
      { q: 'What lot size is needed for a granny flat in Canterbury-Bankstown?', a: 'The minimum under SEPP Housing 2021 is 450 m². Post-war suburban lots in Bankstown, Canterbury, and Punchbowl are typically 550–700 m² and qualify. Smaller lots in terrace streets are less likely to meet the minimum.' },
      { q: 'Are heritage exclusions common in Canterbury-Bankstown?', a: 'Canterbury-Bankstown has 274 heritage items — relatively low compared to inner-city councils. Heritage exclusions do occur near Campsie heritage conservation areas and older parts of Canterbury. Check your address to confirm.' },
      { q: 'Do I need council approval for a granny flat in Canterbury-Bankstown?', a: 'If the SEPP Housing 2021 checks all pass, you can lodge a CDC through a private certifier — no council DA needed. Canterbury-Bankstown Council must be involved if any check fails.' },
      { q: 'What are the flood risks for granny flats in Canterbury-Bankstown?', a: 'Parts of Canterbury-Bankstown near the Cooks River and Duck River have flood risk. The checker above cross-references statutory flood overlays — if your address is a flood control lot, a CDC is not available and a DA is required.' },
    ],
  },
  {
    name: 'Parramatta',
    slug: 'parramatta',
    heritageCount: 803,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['blacktown', 'ryde', 'penrith'],
    faqs: [
      { q: 'Can I build a granny flat in Parramatta?', a: 'Yes, many Parramatta properties qualify under SEPP Housing 2021. R2 residential lots over 450 m² in suburbs like Merrylands, Granville, and Toongabbie are good candidates. Heritage exclusions are more common near the Parramatta CBD heritage conservation area.' },
      { q: 'Does heritage affect granny flat eligibility in Parramatta?', a: 'Parramatta has 803 heritage items, with significant heritage conservation areas around the CBD and older residential precincts. Properties that are heritage items are excluded from SEPP Housing 2021 complying development.' },
      { q: 'What lot size is needed for a granny flat in Parramatta?', a: 'The minimum is 450 m² under SEPP Housing 2021. Many post-war lots in the outer Parramatta suburbs are 550–700 m² and qualify. Compact lots near the CBD or in townhouse estates may be below the threshold.' },
      { q: 'What zone do I need for a granny flat in Parramatta?', a: 'R1 General Residential, R2 Low Density, R3 Medium Density, and RU5 Village zones all permit secondary dwellings under SEPP Housing 2021. Commercial, industrial, and rural zones do not. The checker above confirms your zone.' },
      { q: 'Do I need a DA for a granny flat in Parramatta?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Parramatta City Council requires a DA if any criterion fails — including heritage, flood, or lot size.' },
    ],
  },
  {
    name: 'Blacktown',
    slug: 'blacktown',
    heritageCount: 131,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['parramatta', 'the-hills-shire', 'penrith'],
    faqs: [
      { q: 'Can I build a granny flat in Blacktown?', a: 'Blacktown is one of the most granny-flat-friendly LGAs in Greater Sydney. With low heritage density and large lot sizes across most suburbs, many properties qualify under SEPP Housing 2021. Check your address above to confirm.' },
      { q: 'What lot size is needed for a granny flat in Blacktown?', a: 'The minimum is 450 m². Blacktown\'s post-war and newer suburban lots are typically 600–900 m² — well above the minimum. Even many newer estate lots qualify.' },
      { q: 'Are heritage exclusions common in Blacktown?', a: 'Blacktown has only 131 heritage items — very low for a major LGA. Heritage exclusions are uncommon outside the Blacktown CBD heritage conservation area and a small number of individual heritage items.' },
      { q: 'Do I need council approval for a granny flat in Blacktown?', a: 'If the SEPP checks all pass, you can lodge a CDC through a private certifier — no council DA needed. Blacktown City Council is only involved if a check fails.' },
      { q: 'How large can a granny flat be in Blacktown?', a: 'Secondary dwellings under SEPP Housing 2021 are capped at 60 m² internal floor area. Blacktown\'s DCP also specifies setbacks and height limits. On larger lots, a detached granny flat at the rear of the property is common.' },
    ],
  },
  {
    name: 'The Hills Shire',
    slug: 'the-hills-shire',
    heritageCount: 223,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['hornsby', 'blacktown', 'penrith'],
    faqs: [
      { q: 'Can I build a granny flat in The Hills Shire?', a: 'The Hills Shire is well-suited to granny flats. Large residential lots across Castle Hill, Baulkham Hills, and Kellyville frequently exceed 450 m², and heritage exclusions are relatively uncommon. Check your address above to confirm all criteria.' },
      { q: 'What lot size is needed for a granny flat in The Hills Shire?', a: 'The minimum under SEPP Housing 2021 is 450 m². The Hills Shire has some of Greater Sydney\'s larger residential lots — 700 m²+ is common in established suburbs. Newer townhouse estates with compact lots may be below the threshold.' },
      { q: 'Are heritage exclusions common in The Hills?', a: 'The Hills Shire has 223 heritage items, mainly concentrated in historic village centres like Rouse Hill and Old Northern Road corridor. Most residential suburbs are not heritage-affected.' },
      { q: 'What are the DCP setback requirements in The Hills Shire?', a: 'The Hills Shire DCP sets rear setback requirements for secondary dwellings. These are separate from SEPP eligibility — a property can pass the SEPP check but still have design constraints from DCP setbacks, height limits, and landscaping requirements.' },
      { q: 'Do I need council approval for a granny flat in The Hills Shire?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. The Hills Shire Council involvement is only required if a criterion fails.' },
    ],
  },
  {
    name: 'Northern Beaches',
    slug: 'northern-beaches',
    heritageCount: 956,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['ku-ring-gai', 'lane-cove', 'hornsby'],
    faqs: [
      { q: 'Can I build a granny flat on the Northern Beaches?', a: 'Many Northern Beaches properties qualify, but heritage exclusions are significant — 956 heritage items cover large portions of Manly, Avalon, and Pittwater. Coastal properties may also have biodiversity or acid sulfate soil exclusions. Check your address above.' },
      { q: 'Why might my Northern Beaches property be ineligible?', a: 'The most common exclusions are heritage (conservation areas in beachside villages), biodiversity values map (coastal heathlands and bushland areas), and lot size (some older beachside lots are under 450 m²). The checker above identifies which exclusion applies.' },
      { q: 'Does heritage affect granny flat approvals on the Northern Beaches?', a: 'Yes significantly. Northern Beaches has 956 heritage items. Properties in heritage conservation areas in Manly, Avalon, and Palm Beach are ineligible for CDC secondary dwellings and require a DA.' },
      { q: 'What lot size is needed for a granny flat on the Northern Beaches?', a: 'The minimum is 450 m² under SEPP Housing 2021. Many Northern Beaches lots are 600–900 m² in established suburbs. Some compact lots near Manly and Dee Why may be below 450 m².' },
      { q: 'Do biodiversity exclusions affect granny flat eligibility on the Northern Beaches?', a: 'Yes. Coastal heathland and bushland areas on the Northern Beaches are mapped on the Biodiversity Values Map. Properties within this map are excluded from SEPP Housing 2021 complying development for secondary dwellings.' },
    ],
  },
  {
    name: 'Hornsby',
    slug: 'hornsby',
    heritageCount: 769,
    hasFloodData: true,
    hasAriData: false,
    relatedSlugs: ['ku-ring-gai', 'the-hills-shire', 'northern-beaches'],
    faqs: [
      { q: 'Can I build a granny flat in Hornsby Shire?', a: 'Many Hornsby properties qualify, but bushland setting means biodiversity exclusions are common, and heritage is significant with 769 items. Large lot sizes work in favour of eligibility. Check your address above to confirm.' },
      { q: 'Are biodiversity exclusions common in Hornsby?', a: 'Yes. Hornsby Shire has extensive bushland areas mapped on the Biodiversity Values Map. Properties near creek lines, reserves, and bushland edges are frequently affected. The checker above cross-references this map for your specific address.' },
      { q: 'Does heritage affect granny flat eligibility in Hornsby?', a: 'Hornsby has 769 heritage items. Heritage conservation areas in Berowra, Galston, and Hornsby township can affect eligibility. Heritage item properties are excluded from SEPP Housing 2021 complying development.' },
      { q: 'What lot size is needed for a granny flat in Hornsby?', a: 'The minimum is 450 m². Hornsby\'s established suburbs have predominantly larger lots — 600 m²+ is typical. This works in favour of eligibility, offsetting higher rates of environmental exclusions.' },
      { q: 'Do I need council approval for a granny flat in Hornsby?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Hornsby Shire Council is involved if any criterion fails — biodiversity and heritage are the most likely failure points in this LGA.' },
    ],
  },
  {
    name: 'Ku-ring-gai',
    slug: 'ku-ring-gai',
    heritageCount: 1046,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['hornsby', 'northern-beaches', 'lane-cove'],
    faqs: [
      { q: 'Can I build a granny flat in Ku-ring-gai?', a: 'Ku-ring-gai is one of the harder LGAs for granny flat eligibility. With 1,046 heritage items and extensive heritage conservation areas across Gordon, Killara, Lindfield, and Wahroonga, heritage exclusions affect a large proportion of properties. Check your address above.' },
      { q: 'Why do so many Ku-ring-gai properties fail the heritage check?', a: 'Ku-ring-gai has the second-highest heritage item count in our coverage. Entire streets in established suburbs are within heritage conservation areas. Any property within a conservation area — not just individually listed items — is excluded from SEPP Housing 2021 complying development.' },
      { q: 'What lot size is needed for a granny flat in Ku-ring-gai?', a: 'The minimum is 450 m². Ku-ring-gai\'s large blocks (700 m²+ is common) easily clear the lot size threshold. The binding constraint for most properties is heritage, not lot size.' },
      { q: 'Can I still build a granny flat if my Ku-ring-gai property fails SEPP?', a: 'Yes, via a DA. A heritage impact assessment from a qualified consultant would be required. Some Ku-ring-gai properties can accommodate secondary dwellings through DA with appropriate design conditions. Council\'s heritage officer is the first point of contact.' },
      { q: 'Are biodiversity exclusions common in Ku-ring-gai?', a: 'Yes. Ku-ring-gai\'s extensive bush corridor — including Garigal National Park and local reserves — creates biodiversity value mapping across many residential properties near bushland edges.' },
    ],
  },
  {
    name: 'Georges River',
    slug: 'georges-river',
    heritageCount: 328,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['sutherland-shire', 'bayside', 'campbelltown'],
    faqs: [
      { q: 'Can I build a granny flat in Georges River?', a: 'Many Georges River properties qualify under SEPP Housing 2021. Suburbs like Hurstville, Kogarah, Penshurst, and Oatley have R2 lots over 450 m² that are good candidates. Heritage exclusions are moderate. Check your address above.' },
      { q: 'What lot size is needed for a granny flat in Georges River?', a: 'The minimum is 450 m². Post-war suburban lots in Georges River are typically 550–700 m² and qualify. Compact lots near town centres and some strata-style subdivisions may be below the minimum.' },
      { q: 'Are heritage exclusions common in Georges River?', a: 'Georges River has 328 heritage items. Heritage conservation areas exist in Oatley and parts of Hurstville. Check your address above — most residential streets in Mortdale, Penshurst, and Beverly Hills are not heritage-affected.' },
      { q: 'What are the flood risks for granny flats in Georges River?', a: 'Parts of Georges River near the river itself and Salt Pan Creek have flood risk. The checker above cross-references statutory flood overlays. Properties on flood control lots require a DA rather than CDC.' },
      { q: 'Do I need council approval for a granny flat in Georges River?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Georges River Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Bayside',
    slug: 'bayside',
    heritageCount: 424,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['randwick', 'georges-river', 'inner-west'],
    faqs: [
      { q: 'Can I build a granny flat in Bayside?', a: 'Many Bayside properties qualify. Suburbs like Bexley, Arncliffe, Rockdale, and Mascot have R2 lots over 450 m² that are good candidates. Heritage exclusions exist in some precincts. Check your address above.' },
      { q: 'What lot size is needed for a granny flat in Bayside?', a: 'The minimum is 450 m² under SEPP Housing 2021. Post-war suburban lots in Bayside are typically 500–700 m². Compact lots near Botany and inner areas may be below the threshold.' },
      { q: 'Are heritage exclusions common in Bayside?', a: 'Bayside has 424 heritage items. Heritage conservation areas exist in parts of Rockdale and Bexley. Most residential streets outside the conservation area precincts are not heritage-affected.' },
      { q: 'What are the flood and acid sulfate soil risks in Bayside?', a: 'Bayside has some acid sulfate soil risk in low-lying areas near Botany Bay. The checker above cross-references both acid sulfate soil maps and statutory flood overlays. Either can be an exclusion under SEPP Housing 2021.' },
      { q: 'Do I need council approval for a granny flat in Bayside?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Bayside Council is involved only if a check fails.' },
    ],
  },
  {
    name: 'Randwick',
    slug: 'randwick',
    heritageCount: 574,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['waverley', 'woollahra', 'bayside'],
    faqs: [
      { q: 'Can I build a granny flat in Randwick?', a: 'It depends heavily on your specific address. Randwick has 574 heritage items and many streets in Coogee, Kensington, and Randwick itself are in heritage conservation areas. Lot sizes in inner Randwick are often below 450 m². Check your address above.' },
      { q: 'Why are many Randwick properties ineligible for a granny flat?', a: 'Two main reasons: lot size (many terrace and semi-detached lots are under 450 m²) and heritage (conservation areas cover large parts of Randwick, Coogee, and Kingsford). The checker identifies which constraint applies to your address.' },
      { q: 'What lot size is needed for a granny flat in Randwick?', a: 'The minimum is 450 m². Detached houses in outer Randwick suburbs like Matraville and Little Bay are more likely to clear 450 m². Inner suburbs and terrace streets typically do not.' },
      { q: 'Do acid sulfate soils affect granny flat eligibility in Randwick?', a: 'Parts of coastal Randwick have acid sulfate soil mapping. The checker above cross-references Class 1 and 2 acid sulfate soil maps — properties on these are excluded from SEPP Housing 2021 complying development.' },
      { q: 'Do I need council approval for a granny flat in Randwick?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Randwick City Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Waverley',
    slug: 'waverley',
    heritageCount: 633,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['woollahra', 'randwick', 'bayside'],
    faqs: [
      { q: 'Can I build a granny flat in Waverley?', a: 'Waverley is one of the harder council areas for granny flat eligibility. Most lots are under 450 m², and heritage conservation areas cover large parts of Bondi, Waverley, and Bronte. Check your address above — detached homes on larger blocks have the best chance.' },
      { q: 'Why are most Waverley properties ineligible?', a: 'Waverley\'s density means most residential lots are under 450 m² — the most common reason for ineligibility. Heritage conservation areas add a second common exclusion. The two together make Waverley one of the lowest SEPP eligibility rates in Sydney.' },
      { q: 'What lot size is needed for a granny flat in Waverley?', a: 'The minimum is 450 m². Most Waverley terrace and semi-detached properties are on lots of 150–350 m². Detached houses in Bronte and North Bondi on larger blocks are the most likely candidates.' },
      { q: 'Is a DA an option for a granny flat in Waverley?', a: 'Yes. If the CDC pathway is unavailable, a DA can be lodged with Waverley Council. On lots under 450 m², an attached secondary dwelling may still be achievable through DA depending on the DCP provisions.' },
      { q: 'Does heritage affect granny flats in Waverley?', a: 'Yes. Waverley has 633 heritage items. Heritage conservation areas in Bondi and Waverley cover many residential streets. Properties within conservation areas are excluded from SEPP Housing 2021 complying development.' },
    ],
  },
  {
    name: 'Woollahra',
    slug: 'woollahra',
    heritageCount: 761,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['waverley', 'randwick', 'inner-west'],
    faqs: [
      { q: 'Can I build a granny flat in Woollahra?', a: 'Woollahra is challenging for granny flat eligibility. With 761 heritage items and many lots under 450 m² in Paddington and Double Bay, a large proportion of properties are ineligible via CDC. Check your address above — larger detached homes in Woollahra and Bellevue Hill have better prospects.' },
      { q: 'Why are many Woollahra properties ineligible for a granny flat?', a: 'Two main reasons: heritage (conservation areas cover most of Paddington and parts of Woollahra village) and lot size (Paddington terrace lots are typically 100–250 m²). Either exclusion alone is enough to block the CDC pathway.' },
      { q: 'Can I build a granny flat on a Paddington terrace?', a: 'Almost certainly not via CDC — Paddington lots are typically well under 450 m² and heritage-listed. A DA is theoretically possible but would require heritage impact assessment and council approval, and may still face DCP restrictions.' },
      { q: 'What lot size is needed for a granny flat in Woollahra?', a: 'The minimum is 450 m². Larger detached homes in Bellevue Hill, Rose Bay, and parts of Woollahra on bigger blocks have the best prospects. Even these should be checked for heritage conservation area status.' },
      { q: 'Do I need council approval for a granny flat in Woollahra?', a: 'If the rare combination of sufficient lot size and no heritage exclusion is confirmed, a CDC through a private certifier is possible. More commonly in Woollahra, a DA through Woollahra Municipal Council is required.' },
    ],
  },
  {
    name: 'Sutherland Shire',
    slug: 'sutherland-shire',
    heritageCount: 477,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['georges-river', 'campbelltown', 'camden'],
    faqs: [
      { q: 'Can I build a granny flat in the Sutherland Shire?', a: 'Many Sutherland Shire properties qualify. The area has predominantly detached suburban homes on lots well over 450 m², and heritage exclusions are moderate. Biodiversity exclusions near bushland are the main risk factor. Check your address above.' },
      { q: 'Are biodiversity exclusions common in the Sutherland Shire?', a: 'Yes. The Royal National Park and extensive bushland corridors through Sutherland Shire create biodiversity value mapping across many residential properties near the bush. The checker above cross-references the Biodiversity Values Map for your address.' },
      { q: 'What lot size is needed for a granny flat in Sutherland Shire?', a: 'The minimum is 450 m². Most Sutherland Shire suburban lots are 600–900 m² — well above the minimum. This is one of Greater Sydney\'s better areas for clearing the lot size check.' },
      { q: 'Are heritage exclusions common in Sutherland Shire?', a: 'Sutherland Shire has 477 heritage items. Conservation areas exist in Cronulla and parts of Engadine and Helensburgh. Most residential suburbs are not heritage-affected.' },
      { q: 'Do I need council approval for a granny flat in Sutherland Shire?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Sutherland Shire Council is involved only if a check fails — biodiversity is the most likely failure point near bushland areas.' },
    ],
  },
  {
    name: 'Camden',
    slug: 'camden',
    heritageCount: 149,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['campbelltown', 'liverpool', 'sutherland-shire'],
    faqs: [
      { q: 'Can I build a granny flat in Camden?', a: 'Camden is one of the most granny-flat-friendly LGAs in Greater Sydney. Large lots, low heritage density, and R2 zoning across most residential areas make eligibility rates high. Check your address above to confirm.' },
      { q: 'What lot size is needed for a granny flat in Camden?', a: 'The minimum is 450 m² under SEPP Housing 2021. Camden\'s established suburbs have lots typically 600–900 m². Some newer estate lots in Leppington and Oran Park may be under 450 m² — check your specific lot.' },
      { q: 'Are heritage exclusions common in Camden?', a: 'Camden has 149 heritage items, mainly concentrated in the Camden Town heritage conservation area. Most residential suburbs are not heritage-affected — one of Camden\'s advantages for granny flat eligibility.' },
      { q: 'Do I need council approval for a granny flat in Camden?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient — no council DA needed. Camden Council is only involved if a criterion fails.' },
      { q: 'How large can a granny flat be in Camden?', a: 'Secondary dwellings under SEPP Housing 2021 are capped at 60 m² internal floor area. Camden\'s large lots often allow a detached granny flat at the rear. DCP setbacks and height limits apply and should be confirmed before designing.' },
    ],
  },
  {
    name: 'Liverpool',
    slug: 'liverpool',
    heritageCount: 97,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['camden', 'campbelltown', 'parramatta'],
    faqs: [
      { q: 'Can I build a granny flat in Liverpool?', a: 'Liverpool has strong granny flat eligibility. Low heritage density, predominantly R2 zoning, and suburban lot sizes over 450 m² across most of the LGA combine for high eligibility rates. Check your address above to confirm.' },
      { q: 'What lot size is needed for a granny flat in Liverpool?', a: 'The minimum is 450 m². Liverpool\'s established suburbs typically have lots of 600–800 m². Newer estate subdivisions in Edmondson Park and Carnes Hill may have smaller lots — check your specific lot.' },
      { q: 'Are heritage exclusions common in Liverpool?', a: 'Liverpool has only 97 heritage items — one of the lowest counts in our coverage. Heritage exclusions are mainly limited to the Liverpool CBD heritage precinct. Most residential suburbs are unaffected.' },
      { q: 'What are the flood risks for granny flats in Liverpool?', a: 'Parts of Liverpool near the Georges River and South Creek have flood risk. The checker above cross-references statutory flood overlays. Properties on flood control lots require a DA rather than CDC.' },
      { q: 'Do I need council approval for a granny flat in Liverpool?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Liverpool City Council is involved only if a check fails.' },
    ],
  },
  {
    name: 'Penrith',
    slug: 'penrith',
    heritageCount: 253,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['blacktown', 'hawkesbury', 'the-hills-shire'],
    faqs: [
      { q: 'Can I build a granny flat in Penrith?', a: 'Penrith has good granny flat eligibility. Large residential lots, moderate heritage density, and R2 zoning across most suburbs make many properties eligible. Flood exclusions near the Nepean River are worth checking. Use the checker above.' },
      { q: 'What lot size is needed for a granny flat in Penrith?', a: 'The minimum is 450 m². Penrith\'s established suburbs typically have lots of 600–900 m². Newer estate lots in Jordan Springs and Thornton may be smaller — check your specific lot.' },
      { q: 'Are heritage exclusions common in Penrith?', a: 'Penrith has 253 heritage items, mainly around the Penrith CBD and Emu Plains heritage precincts. Most residential suburbs are not heritage-affected.' },
      { q: 'What flood risk exists for granny flats in Penrith?', a: 'Properties near the Nepean River and South Creek have flood risk. Penrith\'s flood history is significant — the Nepean has reached record levels in recent years. The checker cross-references statutory flood overlays for your address.' },
      { q: 'Do I need council approval for a granny flat in Penrith?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Penrith City Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Lane Cove',
    slug: 'lane-cove',
    heritageCount: 318,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['ryde', 'ku-ring-gai', 'inner-west'],
    faqs: [
      { q: 'Can I build a granny flat in Lane Cove?', a: 'Many Lane Cove properties qualify. Post-war detached homes on lots over 450 m² are common. Heritage exclusions are moderate and mainly affect the Lane Cove village area. Biodiversity exclusions near the Lane Cove River are worth checking.' },
      { q: 'Are biodiversity exclusions a risk in Lane Cove?', a: 'Yes. Lane Cove National Park and bushland corridors create biodiversity value mapping near creek lines and reserves. Properties adjoining or near Lane Cove National Park should check the Biodiversity Values Map.' },
      { q: 'What lot size is needed for a granny flat in Lane Cove?', a: 'The minimum is 450 m². Lane Cove\'s post-war residential lots are typically 600–800 m² and qualify. Smaller lots in newer townhouse subdivisions may be below the threshold.' },
      { q: 'Are heritage exclusions common in Lane Cove?', a: 'Lane Cove has 318 heritage items. Heritage conservation areas exist around Lane Cove village and some older residential streets. Most of the broader residential area is not heritage-affected.' },
      { q: 'Do I need council approval for a granny flat in Lane Cove?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Lane Cove Council is involved only if a check fails.' },
    ],
  },
  {
    name: 'Ryde',
    slug: 'ryde',
    heritageCount: 221,
    hasFloodData: false,
    hasAriData: false,
    relatedSlugs: ['lane-cove', 'parramatta', 'ku-ring-gai'],
    faqs: [
      { q: 'Can I build a granny flat in Ryde?', a: 'Many Ryde properties qualify under SEPP Housing 2021. Post-war suburban lots over 450 m² are common across Meadowbank, West Ryde, and Eastwood. Heritage exclusions are moderate. Check your address above.' },
      { q: 'What lot size is needed for a granny flat in Ryde?', a: 'The minimum is 450 m². Ryde\'s established suburbs typically have lots of 550–750 m². Newer apartment-adjacent subdivisions and smaller inner lots may be below the threshold.' },
      { q: 'Are heritage exclusions common in Ryde?', a: 'Ryde has 221 heritage items — relatively low. Heritage conservation areas exist in parts of Meadowbank and the historic top of Ryde. Most residential suburbs are not affected.' },
      { q: 'What flood and acid sulfate risks exist in Ryde?', a: 'Properties near the Parramatta River and Lane Cove River in Ryde may have flood risk or acid sulfate soil mapping. The checker above cross-references both for your specific address.' },
      { q: 'Do I need council approval for a granny flat in Ryde?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. City of Ryde Council is involved only if a check fails.' },
    ],
  },
  {
    name: 'Wollongong',
    slug: 'wollongong',
    heritageCount: 519,
    hasFloodData: true,
    hasAriData: false,
    relatedSlugs: ['wingecarribee', 'campbelltown', 'sutherland-shire'],
    faqs: [
      { q: 'Can I build a granny flat in Wollongong?', a: 'Many Wollongong properties qualify under SEPP Housing 2021. Suburban lots across Wollongong, Figtree, and Unanderra are typically over 450 m². Heritage and flood exclusions are worth checking depending on suburb. Use the checker above.' },
      { q: 'What lot size is needed for a granny flat in Wollongong?', a: 'The minimum is 450 m² under SEPP Housing 2021. Most post-war residential lots in Wollongong are 550–800 m². Compact lots near the CBD and beachside suburbs may be below the threshold.' },
      { q: 'Does flood risk affect granny flat eligibility in Wollongong?', a: 'Parts of Wollongong near coastal lagoons, Mullet Creek, and Allans Creek have flood risk. Properties on flood control lots are excluded from the CDC pathway. The checker above cross-references statutory flood overlays for your address.' },
      { q: 'Are heritage exclusions common in Wollongong?', a: 'Wollongong has 519 heritage items. Heritage conservation areas exist in the Wollongong CBD and historic mining townships. Most residential suburbs are not heritage-affected.' },
      { q: 'Do I need council approval for a granny flat in Wollongong?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Wollongong City Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Clarence Valley',
    slug: 'clarence-valley',
    heritageCount: 1153,
    hasFloodData: true,
    hasAriData: true,
    relatedSlugs: ['tamworth-regional', 'bathurst-regional', 'yass-valley'],
    faqs: [
      { q: 'Can I build a granny flat in Clarence Valley?', a: 'Clarence Valley eligibility varies significantly by location. Flood exclusions are significant across the Clarence River floodplain. Heritage exclusions are also notable with 1,153 items. Rural-residential lots away from the floodplain have better prospects.' },
      { q: 'How does flooding affect granny flat eligibility in Clarence Valley?', a: 'The Clarence River creates extensive flood planning areas across Grafton, Maclean, and Yamba. Properties on flood control lots are excluded from the CDC pathway. Given the 2022 flood events, flood status should always be checked before proceeding.' },
      { q: 'What lot size is needed for a granny flat in Clarence Valley?', a: 'The minimum is 450 m². Rural-residential lots in Clarence Valley are typically much larger than this. Town lots in Grafton and Maclean vary — check your specific lot.' },
      { q: 'Are heritage exclusions common in Clarence Valley?', a: 'Clarence Valley has 1,153 heritage items — a high count reflecting the region\'s colonial and pastoral history. Heritage conservation areas exist in Grafton\'s jacaranda city precinct and historic town centres. Check your address.' },
      { q: 'Do I need council approval for a granny flat in Clarence Valley?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Clarence Valley Council is involved only if a criterion fails — flood and heritage are the most common failure points.' },
    ],
  },
  {
    name: 'Yass Valley',
    slug: 'yass-valley',
    heritageCount: 332,
    hasFloodData: true,
    hasAriData: true,
    relatedSlugs: ['wingecarribee', 'bathurst-regional', 'wollongong'],
    faqs: [
      { q: 'Can I build a granny flat in Yass Valley?', a: 'Many Yass Valley properties qualify. Rural-residential and suburban lots in the Yass area are typically large. The main exclusion risks are flood (near the Yass River) and heritage in the Yass town centre precinct.' },
      { q: 'What lot size is needed for a granny flat in Yass Valley?', a: 'The minimum is 450 m². Most Yass Valley residential lots clear this easily. Compact town lots in central Yass are the exception.' },
      { q: 'Does flood risk affect granny flat eligibility in Yass Valley?', a: 'Properties near the Yass River in central Yass are within flood planning areas. These properties require a DA rather than CDC for a secondary dwelling.' },
      { q: 'Are heritage exclusions common in Yass Valley?', a: 'Yass Valley has 332 heritage items. The Yass town centre heritage conservation area affects a number of older residential properties. Rural areas outside the town precinct are generally unaffected.' },
      { q: 'Do I need council approval for a granny flat in Yass Valley?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Yass Valley Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Forbes',
    slug: 'forbes',
    heritageCount: 168,
    hasFloodData: true,
    hasAriData: false,
    relatedSlugs: ['bathurst-regional', 'tamworth-regional', 'parramatta'],
    faqs: [
      { q: 'Can I build a granny flat in Forbes?', a: 'Forbes eligibility is significantly affected by flood risk — the town has a history of major Lachlan River floods. Many Forbes lots are within flood planning areas. Rural properties away from the floodplain have better prospects. Check your address above.' },
      { q: 'How does flooding affect granny flat eligibility in Forbes?', a: 'Forbes has experienced multiple major Lachlan River floods, most recently in 2022. A large portion of Forbes town lots are within flood planning areas. Properties on flood control lots are excluded from the CDC pathway and require a DA.' },
      { q: 'What lot size is needed for a granny flat in Forbes?', a: 'The minimum is 450 m². Most Forbes residential lots are over 450 m². The binding constraint for many Forbes properties is flood, not lot size.' },
      { q: 'Are heritage exclusions common in Forbes?', a: 'Forbes has 168 heritage items, mainly in the Forbes heritage conservation area in the town centre. Most residential streets outside the conservation area are not heritage-affected.' },
      { q: 'Do I need council approval for a granny flat in Forbes?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Forbes Shire Council is involved only if a criterion fails — flood is the most likely failure point.' },
    ],
  },
  {
    name: 'Tamworth Regional',
    slug: 'tamworth-regional',
    heritageCount: 513,
    hasFloodData: true,
    hasAriData: false,
    relatedSlugs: ['bathurst-regional', 'forbes', 'clarence-valley'],
    faqs: [
      { q: 'Can I build a granny flat in Tamworth?', a: 'Many Tamworth Regional properties qualify. The area has predominantly R2 residential lots over 450 m². Flood exclusions near the Peel River are the main risk. Heritage is notable but mainly affects the CBD precinct.' },
      { q: 'What lot size is needed for a granny flat in Tamworth?', a: 'The minimum is 450 m². Tamworth\'s suburban lots are typically 600–900 m² and well above the minimum. Rural-residential lots are even larger.' },
      { q: 'Does flood risk affect granny flat eligibility in Tamworth?', a: 'Properties near the Peel River, Cockburn River, and Dungowan Creek in Tamworth are within flood planning areas. These require a DA rather than CDC for secondary dwellings. Check your address above.' },
      { q: 'Are heritage exclusions common in Tamworth?', a: 'Tamworth Regional has 513 heritage items. Heritage conservation areas exist in the Tamworth CBD and some historic townships. Most suburban residential streets are not affected.' },
      { q: 'Do I need council approval for a granny flat in Tamworth?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Tamworth Regional Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Bathurst Regional',
    slug: 'bathurst-regional',
    heritageCount: 431,
    hasFloodData: true,
    hasAriData: false,
    relatedSlugs: ['tamworth-regional', 'yass-valley', 'forbes'],
    faqs: [
      { q: 'Can I build a granny flat in Bathurst?', a: 'Many Bathurst properties qualify. Suburban lots over 450 m² are common and heritage exclusions mainly affect the Bathurst CBD heritage conservation area. Flood risk near the Macquarie River is worth checking.' },
      { q: 'What lot size is needed for a granny flat in Bathurst?', a: 'The minimum is 450 m². Bathurst\'s established suburbs typically have lots of 600–800 m². Newer subdivisions may have smaller lots — check your specific lot.' },
      { q: 'Does flood risk affect granny flat eligibility in Bathurst?', a: 'Properties near the Macquarie River and local drainage lines in Bathurst may be within flood planning areas. These require a DA rather than CDC. The checker above cross-references statutory flood overlays.' },
      { q: 'Are heritage exclusions common in Bathurst?', a: 'Bathurst Regional has 431 heritage items. The Bathurst CBD and historic precincts have conservation areas. Most residential suburbs away from the town centre are not heritage-affected.' },
      { q: 'Do I need council approval for a granny flat in Bathurst?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Bathurst Regional Council is involved only if a criterion fails.' },
    ],
  },
  {
    name: 'Wingecarribee',
    slug: 'wingecarribee',
    heritageCount: 577,
    hasFloodData: true,
    hasAriData: false,
    relatedSlugs: ['wollongong', 'yass-valley', 'campbelltown'],
    faqs: [
      { q: 'Can I build a granny flat in the Southern Highlands?', a: 'Many Wingecarribee properties qualify. Rural-residential and suburban lots are typically large. Heritage exclusions in Bowral, Moss Vale, and Mittagong, and flood risk near the Wingecarribee River, are the main considerations.' },
      { q: 'What lot size is needed for a granny flat in Wingecarribee?', a: 'The minimum is 450 m². Southern Highlands residential lots are typically well over 450 m². Rural-residential lots of 2,000 m²+ are common and easily qualify.' },
      { q: 'Does flood risk affect granny flat eligibility in Wingecarribee?', a: 'Properties near the Wingecarribee River around Moss Vale and Bowral, and low-lying areas near local creeks, may be within flood planning areas. These require a DA rather than CDC.' },
      { q: 'Are heritage exclusions common in Wingecarribee?', a: 'Wingecarribee has 577 heritage items. Heritage conservation areas exist in Bowral, Moss Vale, Berrima, and Mittagong. Many rural residential areas outside the town precincts are not heritage-affected.' },
      { q: 'Do I need council approval for a granny flat in Wingecarribee?', a: 'If all SEPP checks pass, a CDC through a private certifier is sufficient. Wingecarribee Shire Council is involved only if a criterion fails.' },
    ],
  },
]

export const GRANNY_FLAT_LGA_SLUG_MAP: Record<string, GrannyFlatLgaData> = Object.fromEntries(
  GRANNY_FLAT_LGAS.map(lga => [lga.slug, lga])
)
