export interface ThreatRadarLgaData {
  name: string
  slug: string
  activityLevel: 'High' | 'Medium' | 'Low'
  activityDescription: string
  hasGrannyFlatPage: boolean
  hasFloodPage: boolean
  faqs: Array<{ q: string; a: string }>
}

export const THREAT_RADAR_LGAS: ThreatRadarLgaData[] = [
  {
    name: 'Inner West',
    slug: 'inner-west',
    activityLevel: 'High',
    activityDescription: 'Infill apartments, terrace conversions, multi-dwelling DAs',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in the Inner West?', a: 'The Inner West has consistently high DA and CDC volumes. Medium-density uplift under the Inner West LEP, dual-occupancy approvals, and apartment conversions generate significant ongoing activity. Suburbs like Marrickville, Leichhardt, and Ashfield regularly see 20–40 new applications per month within 500m of residential addresses.' },
      { q: 'What types of development should Inner West homeowners watch?', a: 'The most common DAs affecting neighbouring properties are: dual-occupancy and secondary dwelling approvals (can change street character), demolition and new construction of multi-dwelling housing, and commercial development on mixed-use corridors. Building works within 50m can also affect street parking and construction amenity.' },
      { q: 'Can I object to a neighbour\'s DA in the Inner West?', a: 'Yes. DAs in Inner West are publicly notified for at least 14 days. You can submit an objection to Inner West Council during the notification period. Weekly alerts give you enough lead time — you typically have 14–28 days from lodgement to submit a submission.' },
      { q: 'How far away do alerts cover?', a: 'The tool checks for DA and CDC applications lodged within 200m of your address. In a dense suburb like Newtown or Leichhardt, this can include 40–80 properties. Most neighbours who would affect your amenity, solar access, or street parking fall within this radius.' },
      { q: 'Do alerts include both council DAs and private certifier CDCs?', a: 'Yes. The tool draws from the NSW ePlanning Portal which includes both council development applications (DAs) and complying development certificates (CDCs) lodged through private certifiers. CDCs — which don\'t require council approval — are often the fastest route for neighbours adding granny flats or making additions.' },
    ],
  },
  {
    name: 'Canterbury-Bankstown',
    slug: 'canterbury-bankstown',
    activityLevel: 'High',
    activityDescription: 'Medium-density residential, dual-occupancy, secondary dwellings',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Canterbury-Bankstown?', a: 'Canterbury-Bankstown has high DA volumes driven by medium-density residential activity. Dual-occupancy, secondary dwelling (granny flat), and multi-unit development are common in inner suburbs like Campsie, Bankstown, and Belmore. The Sydenham to Bankstown corridor renewal adds further activity.' },
      { q: 'What types of development should Canterbury-Bankstown homeowners watch?', a: 'Common DAs include dual-occupancy and granny flat CDCs (typically approved quickly through private certifiers), demolition and new multi-dwelling housing, and boundary fence and structure DAs near rear boundaries. Terraced dual occupancies are the most common source of shadow and amenity concerns.' },
      { q: 'Can I object to a neighbour\'s DA in Canterbury-Bankstown?', a: 'Yes. Council DAs are publicly notified. You can lodge a written submission with Canterbury-Bankstown Council during the notification period (typically 14–28 days). CDCs through private certifiers are not subject to public notification — the weekly alert is your only early warning system for these.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover DA and CDC applications within 200m of your address. In Canterbury-Bankstown\'s suburban grid this typically covers 50–100 nearby properties.' },
      { q: 'Do alerts cover granny flat CDCs lodged by neighbours?', a: 'Yes. Secondary dwelling (granny flat) CDCs from private certifiers appear on the NSW ePlanning Portal and are included in weekly alert checks. These are common in Canterbury-Bankstown and are often approved without any public notification period.' },
    ],
  },
  {
    name: 'Parramatta',
    slug: 'parramatta',
    activityLevel: 'High',
    activityDescription: 'High-rise residential, commercial towers, infill apartments',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Parramatta?', a: 'Parramatta has among the highest DA volumes in Greater Sydney. The CBD is a major high-rise construction zone, with residential towers, commercial buildings, and mixed-use development generating constant applications. Outer suburbs like Merrylands and Granville see high secondary dwelling and dual-occupancy activity.' },
      { q: 'What types of development should Parramatta homeowners watch?', a: 'In the CBD and surrounds: high-rise apartment DAs that affect solar access and views over several blocks. In residential suburbs: dual-occupancy, secondary dwelling CDCs, and multi-dwelling housing. Parramatta\'s Urban Transformation precincts (Telopea, Carter Street) also generate large-scale rezoning DAs.' },
      { q: 'Can I object to a neighbour\'s DA in Parramatta?', a: 'Yes. Council DAs are publicly notified. Parramatta City Council typically allows 14–28 days for public submissions. For large development applications, there may be community information sessions. CDCs through private certifiers are not notified — weekly alerts are your only early warning.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Parramatta CBD, this radius can encompass major tower DAs that significantly affect amenity. In residential suburbs, it typically covers 50–80 properties.' },
      { q: 'Do the alerts cover rezoning proposals near Parramatta?', a: 'The tool monitors DA and CDC lodgements on the ePlanning Portal. Planning proposals (rezonings) are a separate process managed by Parramatta City Council and NSW Department of Planning — these are not on the ePlanning Portal and are not included in alerts. For rezoning monitoring, check the Parramatta Planning Proposals register directly.' },
    ],
  },
  {
    name: 'Blacktown',
    slug: 'blacktown',
    activityLevel: 'High',
    activityDescription: 'High residential volume, secondary dwellings, greenfield lots',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Blacktown?', a: 'Blacktown is one of Greater Sydney\'s highest-volume DA councils. Large greenfield estates in the northwest, combined with infill secondary dwelling and dual-occupancy activity in established suburbs, generate thousands of applications annually. Western suburbs like Rooty Hill, Mount Druitt, and Quakers Hill see consistent residential construction activity.' },
      { q: 'What types of development should Blacktown homeowners watch?', a: 'Secondary dwelling (granny flat) CDCs are very common — many approved within weeks with no notification. New dwelling construction and knockdown-rebuild DAs are frequent in established suburbs. Larger commercial and industrial DAs are common near Seven Hills Road and Richmond Road corridors.' },
      { q: 'Can I object to a neighbour\'s DA in Blacktown?', a: 'Yes. Council DAs are publicly notified by Blacktown City Council for at least 14 days. Weekly alerts give you time to respond before the submission deadline. CDCs through private certifiers — very common in Blacktown — are not notified and require proactive monitoring.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Blacktown\'s suburban grid this typically covers 60–100 properties depending on suburb density.' },
      { q: 'Do granny flat CDCs show up in Blacktown alerts?', a: 'Yes. Secondary dwelling CDCs lodged through private certifiers are recorded on the NSW ePlanning Portal and are included. Blacktown has a high rate of granny flat CDC lodgements — this is one of the primary use cases for weekly alerts in the LGA.' },
    ],
  },
  {
    name: 'Campbelltown',
    slug: 'campbelltown',
    activityLevel: 'Medium',
    activityDescription: 'Suburban residential, secondary dwellings, estate development',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Campbelltown?', a: 'Campbelltown has moderate-to-high DA volumes. Established suburbs see secondary dwelling CDC activity and infill dual-occupancy development. The southwest growth corridor around Menangle Park and Appin adds greenfield construction activity. The Campbelltown Macarthur and Glenfield to Macarthur Corridor renewal areas generate larger development applications.' },
      { q: 'What types of development should Campbelltown homeowners watch?', a: 'Secondary dwelling CDCs (granny flats) are common in established R2 suburbs and are often lodged without council notice. Knockdown-rebuild and new dwelling DAs are frequent in post-war suburbs. Larger commercial and retail DAs near Campbelltown CBD and Macquarie Fields are worth monitoring for residents of nearby mixed-use streets.' },
      { q: 'Can I object to a neighbour\'s DA in Campbelltown?', a: 'Yes. Council DAs are publicly notified by Campbelltown City Council for a minimum of 14 days. Submit a written objection during the notification window. CDCs through private certifiers do not require notification — weekly alerts are the only proactive way to track these.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Campbelltown\'s suburban areas this typically covers 40–70 properties.' },
      { q: 'Are flood-related DAs common in Campbelltown?', a: 'Yes. Campbelltown has detailed ARI flood data and some DAs near Georges River tributaries include flood risk management reports. If you\'re near a creek or drainage line, flood-related DAs for neighbouring properties can affect drainage patterns and stormwater. The alerts will flag these alongside all other application types.' },
    ],
  },
  {
    name: 'The Hills Shire',
    slug: 'the-hills-shire',
    activityLevel: 'Medium',
    activityDescription: 'Large-lot residential, secondary dwellings, estate subdivisions',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in The Hills Shire?', a: 'The Hills Shire has moderate-to-high DA volumes driven by secondary dwelling CDCs in established suburbs and large subdivision DAs in growth precincts around Box Hill and Rouse Hill. Castle Hill and Kellyville see consistent residential construction activity. Sydney Metro Northwest infrastructure DAs have also added to recent volumes.' },
      { q: 'What types of development should Hills Shire homeowners watch?', a: 'Secondary dwelling CDCs — very common given the large lot sizes that qualify under SEPP Housing 2021. Multi-dwelling housing DAs near town centres. Subdivision DAs in greenfield precincts that can create new access roads and infrastructure near existing properties.' },
      { q: 'Can I object to a neighbour\'s DA in The Hills Shire?', a: 'Yes. The Hills Shire Council publicly notifies DAs for the standard 14-day period. Weekly alerts give you time to prepare a submission before the deadline. CDCs through private certifiers are not notified — the weekly check covers these.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In The Hills\' lower-density suburban areas this typically covers 30–60 properties on larger blocks.' },
      { q: 'Are large-scale subdivision DAs common in The Hills?', a: 'Yes in the growth precincts (Box Hill, Rouse Hill, Kellyville Ridge). If you\'re near the urban growth boundary, subdivision and infrastructure DAs are worth monitoring as they can affect access roads, drainage, and amenity over time.' },
    ],
  },
  {
    name: 'Northern Beaches',
    slug: 'northern-beaches',
    activityLevel: 'Medium',
    activityDescription: 'Residential additions, dual-occupancy, coastal development',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development on the Northern Beaches?', a: 'The Northern Beaches has moderate DA volumes. Residential additions and renovations are common in established beachside suburbs. Dual-occupancy and secondary dwelling DAs are frequent in Dee Why and Brookvale. Heritage-affected suburbs like Manly and Avalon see DAs with heritage impact assessments.' },
      { q: 'What types of development should Northern Beaches homeowners watch?', a: 'Residential additions that affect solar access (particularly significant in coastal suburbs with north-facing rear yards). Dual-occupancy DAs in R2 zones. Secondary dwelling CDCs — common in Dee Why, Cromer, and Narrabeen where lot sizes typically qualify. Coastal management DAs near beachfront properties.' },
      { q: 'Can I object to a neighbour\'s DA on the Northern Beaches?', a: 'Yes. Northern Beaches Council publicly notifies DAs. You can submit a written objection within the notification period. Heritage-affected DAs often have extended notification periods. CDCs through private certifiers do not require public notification.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In lower-density Northern Beaches suburbs this typically covers 30–50 properties on larger lots.' },
      { q: 'Are DAs for secondary dwellings common on the Northern Beaches?', a: 'CDCs for secondary dwellings are common in suburbs where lot sizes clear 450m² — particularly Dee Why, Cromer, Narrabeen, and Warriewood. In heritage-affected suburbs like Manly and Avalon, secondary dwellings typically require a DA rather than CDC due to heritage constraints.' },
    ],
  },
  {
    name: 'Hornsby',
    slug: 'hornsby',
    activityLevel: 'Medium',
    activityDescription: 'Residential additions, secondary dwellings, bushland interfaces',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Hornsby Shire?', a: 'Hornsby has moderate DA volumes. Secondary dwelling CDCs and residential additions are common in established suburbs. Hornsby CBD sees periodic larger DA activity. Bushland interface properties generate tree removal DAs and development near biodiversity mapping.' },
      { q: 'What types of development should Hornsby homeowners watch?', a: 'Secondary dwelling and dual-occupancy DAs — common in established R2 suburbs like Pennant Hills, West Pennant Hills, and Cherrybrook. Tree removal DAs can indicate upcoming construction. Multi-dwelling housing in higher-density zones near Hornsby and Waitara stations.' },
      { q: 'Can I object to a neighbour\'s DA in Hornsby?', a: 'Yes. Hornsby Shire Council publicly notifies DAs. Some DAs near bushland or heritage areas have extended notification periods. Submit a written objection within the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Hornsby\'s lower-density suburban and semi-rural areas this typically covers 25–50 properties.' },
      { q: 'Do alerts flag tree removal DAs in Hornsby?', a: 'Yes. Tree removal DAs are lodged on the NSW ePlanning Portal and are included in alert checks. In Hornsby\'s bushland corridors, tree DAs can be an early signal of planned development on a neighbouring property.' },
    ],
  },
  {
    name: 'Ku-ring-gai',
    slug: 'ku-ring-gai',
    activityLevel: 'Medium',
    activityDescription: 'Heritage DAs, dual-occupancy, residential additions',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Ku-ring-gai?', a: 'Ku-ring-gai has moderate DA volumes. Heritage-affected DAs are common given the large number of heritage conservation areas. Dual-occupancy and secondary dwelling activity is lower than average due to heritage restrictions — but where it occurs, it can be contentious.' },
      { q: 'What types of development should Ku-ring-gai homeowners watch?', a: 'Heritage impact assessment DAs for alterations to neighbouring heritage properties. Multi-dwelling housing DAs near train stations (Gordon, Turramurra, Wahroonga) in higher-density zones. Secondary dwelling CDCs in R2 areas outside heritage conservation zones.' },
      { q: 'Can I object to a neighbour\'s DA in Ku-ring-gai?', a: 'Yes. Ku-ring-gai Council publicly notifies DAs. Heritage-related DAs often have longer notification periods. If a DA affects a heritage conservation area you live in, you have grounds to submit a heritage impact objection.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Ku-ring-gai\'s lower-density large-lot suburbs this typically covers 20–40 properties.' },
      { q: 'Are dual-occupancy DAs common in Ku-ring-gai?', a: 'Less common than in western Sydney due to widespread heritage conservation areas and minimum lot size controls. Where dual-occupancy does occur — typically in R2 zones outside conservation areas near the Pacific Highway — they can be significant. Weekly alerts capture these as soon as they\'re lodged.' },
    ],
  },
  {
    name: 'Georges River',
    slug: 'georges-river',
    activityLevel: 'Medium',
    activityDescription: 'Medium-density uplift, secondary dwellings, residential infill',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Georges River?', a: 'Georges River has moderate-to-high DA volumes driven by medium-density residential activity. Hurstville and Kogarah see frequent multi-dwelling and mixed-use DAs. Established residential suburbs in Penshurst, Mortdale, and Oatley see secondary dwelling CDCs and residential additions.' },
      { q: 'What types of development should Georges River homeowners watch?', a: 'Multi-dwelling housing DAs near Hurstville and Kogarah town centres can affect traffic and amenity over a wider area. Secondary dwelling CDCs are common in established R2 suburbs. Dual-occupancy DAs near railway station precincts.' },
      { q: 'Can I object to a neighbour\'s DA in Georges River?', a: 'Yes. Georges River Council publicly notifies DAs. Submit a written submission within the notification period (typically 14 days). CDCs through private certifiers are not publicly notified — the weekly check is the only proactive monitoring available.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Georges River\'s suburban grid this typically covers 40–70 properties.' },
      { q: 'Are medium-density DAs common near train stations in Georges River?', a: 'Yes. The Hurstville and Kogarah station precincts are designated for medium-to-high density under the Georges River LEP. Residents within 500m of these stations may see multi-dwelling and mixed-use DAs that affect street character and parking.' },
    ],
  },
  {
    name: 'Bayside',
    slug: 'bayside',
    activityLevel: 'Medium',
    activityDescription: 'Residential infill, dual-occupancy, medium density near stations',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Bayside?', a: 'Bayside has moderate DA volumes. Established suburbs in Rockdale, Bexley, and Arncliffe see infill dual-occupancy and secondary dwelling activity. The Alexandra Canal corridor and areas near Green Square see larger development applications.' },
      { q: 'What types of development should Bayside homeowners watch?', a: 'Dual-occupancy and secondary dwelling CDCs are common in R2 suburbs. Multi-unit development near train stations (Arncliffe, Rockdale, Kogarah). Industrial conversion DAs near the Alexandra Canal precinct.' },
      { q: 'Can I object to a neighbour\'s DA in Bayside?', a: 'Yes. Bayside Council publicly notifies DAs for the standard 14-day period. Weekly alerts give you time to respond. CDCs through private certifiers are not notified.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Bayside\'s suburban areas this typically covers 40–70 properties.' },
      { q: 'Are acid sulfate soil DAs common in Bayside?', a: 'Some DAs in low-lying Bayside areas include acid sulfate soil management plans. These are not a common source of neighbourhood impact directly, but they can indicate development in ecologically sensitive areas near Botany Bay.' },
    ],
  },
  {
    name: 'Randwick',
    slug: 'randwick',
    activityLevel: 'Medium',
    activityDescription: 'Residential additions, dual-occupancy, coastal development',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Randwick?', a: 'Randwick has moderate DA volumes. Residential additions and alterations are common in the dense inner suburbs. Dual-occupancy and secondary dwelling activity is lower in the heritage-heavy eastern areas but higher in Matraville and Little Bay where lot sizes and zoning are more permissive.' },
      { q: 'What types of development should Randwick homeowners watch?', a: 'Residential alterations and additions in adjoining properties — common in terrace and semi-detached streets. Multi-dwelling DAs near Kingsford and Randwick town centres. Development near the UNSW campus precinct.' },
      { q: 'Can I object to a neighbour\'s DA in Randwick?', a: 'Yes. Randwick City Council publicly notifies DAs. Written submissions are accepted during the notification period. Heritage-affected DAs may have extended notification.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Randwick\'s denser inner suburbs this can encompass 60–100 properties.' },
      { q: 'Do secondary dwelling CDCs show up in Randwick alerts?', a: 'Yes. While many Randwick lots are too small for SEPP Housing 2021 CDC eligibility, those that qualify (typically detached homes in outer Randwick and Matraville) may have secondary dwelling CDCs lodged without notification. These are included in weekly alert checks.' },
    ],
  },
  {
    name: 'Waverley',
    slug: 'waverley',
    activityLevel: 'Medium',
    activityDescription: 'Heritage DAs, residential additions, beachside development',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Waverley?', a: 'Waverley has moderate DA volumes. Residential additions, renovations, and heritage-affected DAs dominate. Multi-dwelling and dual-occupancy applications are less common given lot size and heritage constraints, but do occur in Bronte and North Bondi where larger lots exist.' },
      { q: 'What types of development should Waverley homeowners watch?', a: 'Residential additions that affect solar access in dense streets — common in terrace and semi-detached areas. Heritage impact DAs. Occasional multi-dwelling and dual-occupancy DAs in less constrained parts of the LGA.' },
      { q: 'Can I object to a neighbour\'s DA in Waverley?', a: 'Yes. Waverley Council publicly notifies DAs. Heritage-related DAs often have extended notification. Submit written objections during the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Waverley\'s dense suburbs this can encompass 60–100+ properties.' },
      { q: 'Are there DA types specific to Waverley\'s coastal setting?', a: 'Yes. Coastal management DAs, seawall and retaining wall applications, and rock platform works are specific to Waverley\'s beachfront properties. Development near the coastal foreshore may also trigger Coastal Management SEPP checks.' },
    ],
  },
  {
    name: 'Woollahra',
    slug: 'woollahra',
    activityLevel: 'Medium',
    activityDescription: 'Heritage DAs, residential additions, high-value alterations',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Woollahra?', a: 'Woollahra has moderate DA volumes, dominated by residential alterations and heritage-affected applications in Paddington, Woollahra, and Double Bay. Large-scale multi-dwelling development is uncommon due to heritage and zoning constraints. High-value single-dwelling renovations are frequent.' },
      { q: 'What types of development should Woollahra homeowners watch?', a: 'Heritage-affected alterations and additions — common throughout Paddington and Woollahra. Larger residential renovations in Bellevue Hill and Rose Bay that can affect solar access and views. Occasional dual-occupancy DAs in less constrained parts of the LGA.' },
      { q: 'Can I object to a neighbour\'s DA in Woollahra?', a: 'Yes. Woollahra Municipal Council publicly notifies DAs. Heritage conservation area DAs often have extended notification periods. You can submit written objections to Council during the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Woollahra\'s denser Paddington streets this can cover 60–100 properties. In larger-lot Rose Bay and Bellevue Hill areas, typically 25–50 properties.' },
      { q: 'Are CDCs common in Woollahra?', a: 'Less common than in western Sydney. The heritage constraints and smaller lots in Paddington mean most development goes through DA. Where CDCs do occur — typically minor works on non-heritage properties — they appear in the NSW ePlanning Portal and are included in weekly alert checks.' },
    ],
  },
  {
    name: 'Sutherland Shire',
    slug: 'sutherland-shire',
    activityLevel: 'Medium',
    activityDescription: 'Secondary dwellings, residential additions, bushland interface',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in the Sutherland Shire?', a: 'Sutherland Shire has moderate DA volumes. Secondary dwelling CDCs are common given the large lot sizes that qualify under SEPP Housing 2021. Residential additions and new dwelling construction are frequent across established suburbs. Bushland interface properties can see tree removal and vegetation clearing DAs.' },
      { q: 'What types of development should Sutherland Shire homeowners watch?', a: 'Secondary dwelling CDCs — common across Caringbah, Miranda, Engadine, and other established R2 suburbs with large lots. Knockdown-rebuild DAs near creeks and reserves. Commercial and industrial DAs near Kirrawee and Caringbah industrial areas.' },
      { q: 'Can I object to a neighbour\'s DA in Sutherland Shire?', a: 'Yes. Sutherland Shire Council publicly notifies DAs for the standard 14-day period. Weekly alerts let you respond before notification closes. CDCs are not publicly notified — only catchable through proactive monitoring.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Sutherland Shire\'s lower-density suburban areas this typically covers 30–60 properties.' },
      { q: 'Do alerts flag development near national park boundaries in Sutherland Shire?', a: 'The tool monitors NSW ePlanning Portal applications for all development types within 200m of your address, including those near Royal National Park boundaries. DAs near park interfaces often include biodiversity management plans and may generate objections from environmental groups.' },
    ],
  },
  {
    name: 'Lane Cove',
    slug: 'lane-cove',
    activityLevel: 'Medium',
    activityDescription: 'Residential additions, secondary dwellings, medium density near station',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Lane Cove?', a: 'Lane Cove has moderate DA volumes. Residential additions and secondary dwelling CDCs are common in established R2 suburbs. Multi-dwelling development near Lane Cove village and the Pacific Highway generates periodic larger DAs.' },
      { q: 'What types of development should Lane Cove homeowners watch?', a: 'Secondary dwelling CDCs in large-lot R2 areas. Multi-dwelling DAs near Lane Cove town centre and the Pacific Highway corridor. Residential additions near creek lines that may include stormwater DAs.' },
      { q: 'Can I object to a neighbour\'s DA in Lane Cove?', a: 'Yes. Lane Cove Council publicly notifies DAs. Submit written objections during the notification period (typically 14 days). CDCs are not notified — weekly monitoring is the only way to stay across these.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Lane Cove\'s predominantly low-density areas this typically covers 30–55 properties.' },
      { q: 'Are biodiversity-related DAs common in Lane Cove?', a: 'Tree removal and vegetation DAs near Lane Cove National Park and the Lane Cove River are common. These can indicate upcoming construction or land clearing on neighbouring properties.' },
    ],
  },
  {
    name: 'Ryde',
    slug: 'ryde',
    activityLevel: 'High',
    activityDescription: 'Medium density, apartment DAs, secondary dwellings',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Ryde?', a: 'Ryde has high DA volumes driven by medium-density residential activity. Meadowbank, West Ryde, and Eastwood see consistent apartment and multi-unit DAs. Established suburbs across the LGA generate secondary dwelling CDCs and residential additions.' },
      { q: 'What types of development should Ryde homeowners watch?', a: 'Multi-dwelling and apartment DAs near Meadowbank, West Ryde, and Macquarie Park. Secondary dwelling CDCs in established R2 suburbs. Development near the Parramatta River foreshore precinct.' },
      { q: 'Can I object to a neighbour\'s DA in Ryde?', a: 'Yes. City of Ryde Council publicly notifies DAs. Submit written submissions during the notification period. Significant DAs near station precincts may also be considered by the Sydney Eastern City Planning Panel rather than Council.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Ryde\'s medium-density areas this can encompass 60–100+ properties.' },
      { q: 'Are Macquarie Park commercial DAs relevant for residential neighbours?', a: 'Large commercial DAs in Macquarie Park can affect traffic, construction amenity, and long-term overshadowing for residential properties within the alert radius. The tool captures all DA types, not just residential.' },
    ],
  },
  {
    name: 'Camden',
    slug: 'camden',
    activityLevel: 'High',
    activityDescription: 'Greenfield estates, secondary dwellings, growth corridor DAs',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Camden?', a: 'Camden is one of Australia\'s fastest-growing LGAs. Greenfield estate development across Leppington, Oran Park, and Gledswood Hills generates very high DA volumes. Established suburbs see secondary dwelling and dual-occupancy activity. Infrastructure DAs for roads and utilities are also common.' },
      { q: 'What types of development should Camden homeowners watch?', a: 'Subdivision DAs in greenfield estates that create new streets and infrastructure near existing properties. Secondary dwelling CDCs in established suburbs like Camden, Narellan, and Smeaton Grange. Large-format retail and commercial DAs near Narellan and Oran Park town centres.' },
      { q: 'Can I object to a neighbour\'s DA in Camden?', a: 'Yes. Camden Council publicly notifies DAs. Greenfield subdivision DAs often have extended assessment periods. CDCs through private certifiers are not notified — weekly alerts are the only proactive monitoring available.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Camden\'s low-density growth areas this can cover 20–50 properties. In denser established suburbs like Narellan, typically 50–80 properties.' },
      { q: 'Are infrastructure DAs included in Camden alerts?', a: 'Yes. Road construction, drainage, and utility DAs lodged on the NSW ePlanning Portal are included in alert checks. In Camden\'s active growth corridors, these can affect access, construction noise, and amenity for existing residents.' },
    ],
  },
  {
    name: 'Liverpool',
    slug: 'liverpool',
    activityLevel: 'High',
    activityDescription: 'High DA volume, residential infill, growth corridor activity',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Liverpool?', a: 'Liverpool has high DA volumes. The Liverpool CBD is a major development focus with medium-to-high density residential and commercial DAs. Established suburbs across Casula, Miller, and Moorebank see secondary dwelling CDCs and residential construction. The Western Sydney Aerotropolis proximity adds major infrastructure DA activity.' },
      { q: 'What types of development should Liverpool homeowners watch?', a: 'Secondary dwelling CDCs — common across established R2 Liverpool suburbs with large lots. Multi-dwelling and mixed-use DAs near Liverpool CBD and train station precinct. Industrial and logistics DAs near Moorebank.' },
      { q: 'Can I object to a neighbour\'s DA in Liverpool?', a: 'Yes. Liverpool City Council publicly notifies DAs. Large DAs near the CBD may be assessed by the Western City Planning Panel rather than Council. Submit written objections during the notification period.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Liverpool\'s suburban areas this typically covers 50–80 properties.' },
      { q: 'Do the alerts include Aerotropolis-related DAs?', a: 'The tool covers NSW ePlanning Portal applications within 200m of your address. Major Aerotropolis DAs may be assessed under a different state-led planning pathway and may not appear on the ePlanning Portal directly. Check the Western Parkland City Authority for precinct-level development proposals.' },
    ],
  },
  {
    name: 'Penrith',
    slug: 'penrith',
    activityLevel: 'Medium',
    activityDescription: 'Residential infill, secondary dwellings, growth corridor activity',
    hasGrannyFlatPage: true,
    hasFloodPage: false,
    faqs: [
      { q: 'How active is development in Penrith?', a: 'Penrith has moderate-to-high DA volumes. Established suburbs see secondary dwelling CDCs and residential construction. Growth areas in Jordan Springs and Thornton add subdivision and new dwelling DAs. Penrith CBD regeneration adds commercial and mixed-use DAs.' },
      { q: 'What types of development should Penrith homeowners watch?', a: 'Secondary dwelling CDCs in large-lot R2 suburbs. Subdivision DAs in northern growth areas. Commercial and retail DAs near Penrith city centre and Westfield precinct.' },
      { q: 'Can I object to a neighbour\'s DA in Penrith?', a: 'Yes. Penrith City Council publicly notifies DAs for the standard period. Large DAs may be assessed by the Western City Planning Panel. Submit objections within the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Penrith\'s suburban areas this typically covers 40–70 properties.' },
      { q: 'Are flood-related DAs common near the Nepean River in Penrith?', a: 'Yes. Properties near the Nepean River and South Creek sometimes generate DAs that include flood risk management reports. These can affect drainage and stormwater for neighbouring properties. The weekly alert captures all DA types including flood-related applications.' },
    ],
  },
  {
    name: 'Wollongong',
    slug: 'wollongong',
    activityLevel: 'Medium',
    activityDescription: 'Residential infill, secondary dwellings, coastal development',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Wollongong?', a: 'Wollongong has moderate DA volumes. The Wollongong CBD and Corrimal see medium-density residential and commercial DAs. Established suburbs across Figtree, Unanderra, and Dapto see secondary dwelling CDCs and residential construction activity.' },
      { q: 'What types of development should Wollongong homeowners watch?', a: 'Secondary dwelling CDCs — common in suburban R2 areas with qualifying lot sizes. Multi-dwelling DAs near Wollongong, North Wollongong, and Corrimal stations. Coastal development DAs near the escarpment and beachfront.' },
      { q: 'Can I object to a neighbour\'s DA in Wollongong?', a: 'Yes. Wollongong City Council publicly notifies DAs. Submit written objections during the notification period. CDCs through private certifiers are not notified.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Wollongong\'s suburban areas this typically covers 40–70 properties.' },
      { q: 'Are coastal hazard DAs common in Wollongong?', a: 'DAs near the Wollongong escarpment and beachfront sometimes include coastal hazard or bushfire management components. These are included in weekly alert checks alongside all other DA types.' },
    ],
  },
  {
    name: 'Hawkesbury',
    slug: 'hawkesbury',
    activityLevel: 'Low',
    activityDescription: 'Rural residential, secondary dwellings, flood-related DAs',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Hawkesbury?', a: 'Hawkesbury has relatively low DA volumes compared to metropolitan Sydney. Rural-residential subdivision and secondary dwelling activity are the most common application types. Flood-affected areas generate DAs with flood risk management reports. Windsor and Richmond town centres see periodic retail and commercial DAs.' },
      { q: 'What types of development should Hawkesbury homeowners watch?', a: 'Secondary dwelling CDCs in large rural-residential lots. Subdivision DAs that can affect access roads and drainage. Flood risk management DAs near the Hawkesbury-Nepean River and its tributaries.' },
      { q: 'Can I object to a neighbour\'s DA in Hawkesbury?', a: 'Yes. Hawkesbury City Council publicly notifies DAs for the standard 14-day period. In rural-residential areas, physical notice on the property is common. Submit written objections within the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Hawkesbury\'s lower-density rural-residential areas this typically covers fewer properties than metropolitan Sydney — often 10–30.' },
      { q: 'Are flood risk DAs common in Hawkesbury?', a: 'Yes. Given the Hawkesbury-Nepean floodplain, many DAs include flood risk management reports and levee offset requirements. These can affect drainage patterns for neighbouring properties. The weekly check captures all flood-related applications alongside standard residential DAs.' },
    ],
  },
  {
    name: 'Clarence Valley',
    slug: 'clarence-valley',
    activityLevel: 'Low',
    activityDescription: 'Rural residential, flood-related DAs, small commercial',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Clarence Valley?', a: 'Clarence Valley has low DA volumes relative to Sydney metropolitan LGAs. Rural-residential construction and secondary dwelling activity are common. Flood-affected areas near the Clarence River generate DAs with flood risk management components.' },
      { q: 'What types of development should Clarence Valley homeowners watch?', a: 'Flood-affected construction DAs near the Clarence River floodplain. Rural subdivision and boundary adjustment DAs. Secondary dwelling CDCs in established town lots in Grafton and Maclean.' },
      { q: 'Can I object to a neighbour\'s DA in Clarence Valley?', a: 'Yes. Clarence Valley Council publicly notifies DAs. In rural areas, physical site notices are typically posted. Submit written objections during the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Clarence Valley\'s rural and town areas this typically covers 10–30 properties depending on density.' },
      { q: 'Are DAs for flood levees or raised buildings common in Clarence Valley?', a: 'Yes. Given the 2022 flood experience, some property owners are lodging DAs for floor level raises, levee works, and flood-resilient construction. These can affect drainage and flood flow paths for neighbouring properties.' },
    ],
  },
  {
    name: 'Yass Valley',
    slug: 'yass-valley',
    activityLevel: 'Low',
    activityDescription: 'Rural residential, secondary dwellings, small commercial',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Yass Valley?', a: 'Yass Valley has low DA volumes. Rural-residential construction and secondary dwelling activity are common. Yass town centre sees periodic retail and commercial DAs. Flood-related applications near the Yass River are occasional.' },
      { q: 'What types of development should Yass Valley homeowners watch?', a: 'Secondary dwelling CDCs in Yass town lots. Rural subdivision and rural residential DAs. Small commercial DAs near the Yass town centre.' },
      { q: 'Can I object to a neighbour\'s DA in Yass Valley?', a: 'Yes. Yass Valley Council publicly notifies DAs. In rural settings, physical site notices are standard. Submit written objections during the notification window.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In Yass Valley\'s town areas this typically covers 15–40 properties.' },
      { q: 'Do alerts work for rural properties in Yass Valley?', a: 'Yes. The tool works for any NSW address. In rural areas with low neighbour density, the 200m radius may encompass only a handful of properties — but the weekly check is still valuable, particularly for subdivision DAs that can affect access roads and drainage.' },
    ],
  },
  {
    name: 'Wingecarribee',
    slug: 'wingecarribee',
    activityLevel: 'Low',
    activityDescription: 'Heritage DAs, rural residential, lifestyle lot development',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Wingecarribee (Southern Highlands)?', a: 'Wingecarribee has low-to-moderate DA volumes. Heritage-affected DAs in Bowral and Moss Vale are common. Rural-residential and lifestyle lot construction is steady. Secondary dwelling CDCs occur in town areas where lot sizes qualify.' },
      { q: 'What types of development should Southern Highlands homeowners watch?', a: 'Heritage impact DAs in Bowral, Moss Vale, and Berrima conservation areas. Rural subdivision and boundary adjustment DAs. Agricultural and equestrian facility DAs in rural-residential zones.' },
      { q: 'Can I object to a neighbour\'s DA in Wingecarribee?', a: 'Yes. Wingecarribee Shire Council publicly notifies DAs. Heritage-affected DAs often have extended notification. Submit written objections during the notification period.' },
      { q: 'How far away do alerts cover?', a: 'Alerts cover applications within 200m. In the Southern Highlands\' town areas this typically covers 20-50 properties. Rural areas may cover only a few neighbouring properties.' },
      { q: 'Do the alerts include rural and equestrian DAs?', a: 'Yes. The NSW ePlanning Portal includes all DA types including agricultural buildings, equestrian facilities, and rural subdivision. These are included in weekly alert checks for Wingecarribee addresses near rural-residential zones.' },
    ],
  },
  {
    name: 'Forbes',
    slug: 'forbes',
    activityLevel: 'Low',
    activityDescription: 'Rural residential, small commercial, agricultural subdivision',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Forbes?', a: 'Forbes has low DA volumes typical of a NSW central west country town. Residential construction and secondary dwelling CDCs in the town area are the most common application types. Agricultural subdivision and rural-residential DAs occur on the outskirts. The Forbes town centre sees periodic small commercial and retail DAs.' },
      { q: 'What types of development should Forbes homeowners watch?', a: 'Secondary dwelling CDCs in town residential lots -- these can be lodged without council notification and are the most common neighbour-affecting application type. Agricultural subdivision DAs on the town fringe can affect road access and drainage. Flood risk management DAs near the Lachlan River and Forbes Creek are occasional but impactful.' },
      { q: 'Can I object to a neighbour\'s DA in Forbes?', a: 'Yes. Forbes Shire Council publicly notifies DAs for the standard 14-day period. In rural and town areas, physical site notices are typically posted on the property boundary. Submit a written objection to Council within the notification window to have it considered by the assessing officer.' },
    ],
  },
  {
    name: 'Tamworth Regional',
    slug: 'tamworth-regional',
    activityLevel: 'Medium',
    activityDescription: 'Regional centre growth, residential subdivision, commercial development',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Tamworth Regional?', a: 'Tamworth is the largest regional city in northwest NSW and has moderate DA volumes that reflect its role as a service hub. Residential subdivision in growth areas on the city fringe is ongoing. Secondary dwelling CDCs are common across established R2 suburbs. The Tamworth CBD sees periodic commercial and mixed-use DAs driven by population and employment growth.' },
      { q: 'What types of development should Tamworth homeowners watch?', a: 'Secondary dwelling CDCs across established residential areas -- common in Tamworth\'s large-lot suburban streets and lodged without public notification. Residential subdivision DAs in growth precincts north and south of the CBD can affect local road and drainage infrastructure. Commercial DAs along the New England Highway corridor are worth monitoring for residents on mixed-use streets.' },
      { q: 'Can I object to a neighbour\'s DA in Tamworth Regional?', a: 'Yes. Tamworth Regional Council publicly notifies DAs for the standard period. Significant DAs in commercial or growth precinct areas may attract longer assessment timelines. Submit a written objection during the notification period to have it recorded on the file. CDCs through private certifiers are not subject to notification -- weekly alerts are your only early warning for those.' },
    ],
  },
  {
    name: 'Bathurst Regional',
    slug: 'bathurst-regional',
    activityLevel: 'Medium',
    activityDescription: 'University town growth, residential infill, heritage DAs',
    hasGrannyFlatPage: true,
    hasFloodPage: true,
    faqs: [
      { q: 'How active is development in Bathurst Regional?', a: 'Bathurst has moderate DA volumes driven by university-linked residential demand and steady population growth. Charles Sturt University\'s presence underpins rental housing construction and student accommodation DAs. Established residential suburbs see secondary dwelling CDCs and infill dual-occupancy activity. The heritage-rich city centre generates heritage-affected DAs across all development scales.' },
      { q: 'What types of development should Bathurst homeowners watch?', a: 'Heritage-affected DAs in the Bathurst city centre and surrounding conservation precincts -- these require heritage impact assessments and often attract neighbour objections. Secondary dwelling CDCs in suburban R2 areas are common and frequently proceed without notification. Student accommodation DAs near the university precinct can significantly affect parking and traffic on surrounding streets.' },
      { q: 'Can I object to a neighbour\'s DA in Bathurst Regional?', a: 'Yes. Bathurst Regional Council publicly notifies DAs. Heritage conservation area DAs often have extended notification periods. Written submissions can address heritage impact, visual amenity, and built form. For CDCs through private certifiers -- including many secondary dwellings -- the weekly alert is the only way to track lodgements before construction begins.' },
    ],
  },
]

export const THREAT_RADAR_LGA_SLUG_MAP: Record<string, ThreatRadarLgaData> = Object.fromEntries(
  THREAT_RADAR_LGAS.map(lga => [lga.slug, lga])
)
