/**
 * Deterministic Compliance Engine for NSW Development Assessment
 * Uses: NSW API (LEP) + Manually Verified DCP Rules + Standard Section References
 */

import { PropertyData } from './property-data';

export interface DeterministicRule {
 id: string;
 jurisdiction: "LEP" | "DCP";
 document: string;
 section: string;
 clause: string;
 applies_to: {
 lga: string;
 zones: string[];
 former_council?: string;
 };
 rule: {
 type: "max_height" | "max_fsr" | "min_setback";
 subtype?: "rear" | "side" | "front";
 value: number;
 units: string;
 condition?: string;
 };
 source_url: string;
 confidence: "HIGH" | "VERIFIED" | "STANDARD";
}

export class DeterministicComplianceEngine {
 private rules: DeterministicRule[] = [];
 private extractedRules: any[] = [];

 constructor() {
 this.loadExtractedRules().then(() => {
 this.loadVerifiedRules();
 }).catch(() => {
 // Fallback to hardcoded rules if extraction loading fails
 this.loadVerifiedRules();
 });
 }

 /**
 * Load RAG-extracted rules from JSON files
 */
 private async loadExtractedRules(): Promise<void> {
 try {
 // Load the combined rules generated by RAG-Anything + AutoSchemaKG pipeline
 const baseUrl = typeof window !== 'undefined' ? '' : 'http://localhost:3000';
 const response = await fetch(`${baseUrl}/regulatory-data/inner-west-compliance-rules.json`);
 
 if (response.ok) {
 const data = await response.json();
 this.extractedRules = data.rules || [];
 console.log(`Loaded ${this.extractedRules.length} extracted compliance rules`);
 
 // Convert extracted rules to our deterministic rule format
 this.convertExtractedRules();
 } else {
 console.warn('Could not load extracted rules, using fallback hardcoded rules');
 }
 } catch (error) {
 console.warn('Failed to load extracted rules:', error);
 }
 }

 /**
 * Convert RAG-extracted rules to deterministic rule format
 */
 private convertExtractedRules(): void {
 for (const extractedRule of this.extractedRules) {
 try {
 const deterministicRule = this.convertToDeterministicRule(extractedRule);
 if (deterministicRule) {
 this.rules.push(deterministicRule);
 }
 } catch (error) {
 console.warn(`Failed to convert extracted rule ${extractedRule.id}:`, error);
 }
 }
 
 console.log(`Converted ${this.rules.length} extracted rules to deterministic format`);
 }

 /**
 * Convert a single extracted rule to deterministic format
 */
 private convertToDeterministicRule(extractedRule: any): DeterministicRule | null {
 try {
 const requirement = extractedRule.requirements?.[0];
 if (!requirement) return null;

 return {
 id: extractedRule.id,
 jurisdiction: extractedRule.jurisdiction as "LEP" | "DCP",
 document: extractedRule.source?.document || 'Unknown Document',
 section: extractedRule.source?.section || 'Unknown Section',
 clause: extractedRule.source?.clause || 'Unknown Clause',
 applies_to: {
 lga: extractedRule.applies_to?.lga || 'Inner West',
 zones: extractedRule.applies_to?.zones || ['R2'],
 former_council: extractedRule.applies_to?.former_council
 },
 rule: {
 type: requirement.type,
 subtype: requirement.subtype,
 value: requirement.value,
 units: requirement.units || 'metres',
 condition: requirement.context
 },
 source_url: extractedRule.source?.url || '#',
 confidence: this.mapConfidenceLevel(requirement.confidence || extractedRule.extraction_metadata?.quality_score)
 };
 } catch (error) {
 console.warn('Error converting extracted rule:', error);
 return null;
 }
 }

 /**
 * Map extracted confidence levels to our system
 */
 private mapConfidenceLevel(confidence: string | number): "HIGH" | "VERIFIED" | "STANDARD" {
 if (typeof confidence === 'string') {
 switch (confidence.toUpperCase()) {
 case 'VERIFIED': return 'VERIFIED';
 case 'EXTRACTED': return 'STANDARD';
 case 'TENTATIVE': return 'STANDARD';
 default: return 'STANDARD';
 }
 }
 
 if (typeof confidence === 'number') {
 if (confidence >= 0.8) return 'VERIFIED';
 if (confidence >= 0.6) return 'STANDARD';
 return 'STANDARD';
 }
 
 return 'STANDARD';
 }

 /**
 * Load hardcoded fallback rules (only used as backup when RAG extraction completely fails)
 */
 private loadVerifiedRules() {
 // Only load hardcoded rules if no extracted rules were loaded
 if (this.rules.length > 0) {
 console.log(`Using ${this.rules.length} RAG-extracted rules, skipping hardcoded fallback`);
 return;
 }

 console.log('No RAG-extracted rules loaded - system requires regulatory data');
 // Don't load any hardcoded rules - force use of RAG-extracted data only
 this.rules = [];
 }

 /**
 * Get all applicable rules for a property - DETERMINISTIC
 */
 getApplicableRules(propertyData: PropertyData, formerCouncilArea?: string): DeterministicRule[] {
 console.log('=== DEBUG: Rule matching ===');
 console.log('Property LGA:', propertyData.constraints.lga);
 console.log('Property Zone:', propertyData.constraints.zone);
 console.log('Property LGA type:', typeof propertyData.constraints.lga);
 console.log('Former Council Area:', formerCouncilArea);
 console.log('Total rules to check:', this.rules.length);
 
 const matchedRules = this.rules.filter(rule => {
 const criteria = rule.applies_to;
 console.log(`\nChecking rule: ${rule.id}`);
 console.log('Rule LGA:', criteria.lga);
 console.log('Rule zones:', criteria.zones);
 console.log('Rule former council:', criteria.former_council);
 
 // Must match LGA
 const lgaMatch = propertyData.constraints.lga?.toLowerCase().includes(criteria.lga.toLowerCase());
 console.log('LGA match:', lgaMatch);
 if (!lgaMatch) {
 return false;
 }
 
 // Must match zone
 const zoneMatch = criteria.zones.some(zone => propertyData.constraints.zone?.includes(zone));
 console.log('Zone match:', zoneMatch);
 if (!zoneMatch) {
 return false;
 }
 
 // If rule specifies former council, must match
 if (criteria.former_council && formerCouncilArea !== criteria.former_council) {
 console.log('Former council mismatch');
 return false;
 }
 
 console.log(' Rule matches!');
 return true;
 });
 
 console.log('=== END DEBUG ===');
 return matchedRules;
 }

 /**
 * Check compliance - DETERMINISTIC calculations only
 */
 checkCompliance(
 propertyData: PropertyData,
 proposal: {
 height?: number;
 fsr?: number;
 rear_setback?: number;
 side_setback?: number;
 front_setback?: number;
 },
 formerCouncilArea?: string
 ) {
 
 const results = [];
 
 // LEP Compliance (from NSW API - always check first)
 if (proposal.height && propertyData.constraints.maxHeight) {
 console.log('Checking height compliance:', proposal.height, 'vs max', propertyData.constraints.maxHeight);
 results.push(this.checkHeightCompliance(propertyData, proposal.height));
 }
 
 if (proposal.fsr && propertyData.constraints.maxFsr) {
 console.log('Checking FSR compliance:', proposal.fsr, 'vs max', propertyData.constraints.maxFsr);
 results.push(this.checkFSRCompliance(propertyData, proposal.fsr));
 }
 
 // DCP Setback Compliance (manually verified rules)
 const applicableRules = this.getApplicableRules(propertyData, formerCouncilArea);
 console.log('Applicable rules found:', applicableRules.length);
 
 for (const rule of applicableRules) {
 if (rule.rule.type === "min_setback") {
 const proposalValue = this.getSetbackValue(proposal, rule.rule.subtype!);
 if (proposalValue !== undefined) {
 results.push(this.checkSetbackCompliance(rule, proposalValue));
 }
 }
 }
 
 return results;
 }

 private checkHeightCompliance(propertyData: PropertyData, proposedHeight: number) {
 const limit = propertyData.constraints.maxHeight!;
 const compliant = proposedHeight <= limit;
 
 return {
 rule_id: "NSW_LEP_HEIGHT",
 type: "max_height",
 compliant,
 proposed_value: proposedHeight,
 required_value: limit,
 gap: limit - proposedHeight,
 source: {
 document: `${propertyData.constraints.lga} LEP`,
 section: "Height of Buildings Map",
 clause: propertyData.heightSource?.clause || "Clause 4.3",
 url: propertyData.heightSource?.legislationUrl || "#"
 },
 confidence: "HIGH",
 mitigation: !compliant ? `Reduce height by ${(proposedHeight - limit).toFixed(1)}m` : undefined
 };
 }

 private checkFSRCompliance(propertyData: PropertyData, proposedFsr: number) {
 const limit = propertyData.constraints.maxFsr!;
 const compliant = proposedFsr <= limit;
 
 return {
 rule_id: "NSW_LEP_FSR",
 type: "max_fsr", 
 compliant,
 proposed_value: proposedFsr,
 required_value: limit,
 gap: limit - proposedFsr,
 source: {
 document: `${propertyData.constraints.lga} LEP`,
 section: "Floor Space Ratio Map",
 clause: propertyData.fsrSource?.clause || "Clause 4.4",
 url: propertyData.fsrSource?.legislationUrl || "#"
 },
 confidence: "HIGH",
 mitigation: !compliant ? `Reduce FSR to ${limit}` : undefined
 };
 }

 private checkSetbackCompliance(rule: DeterministicRule, proposedSetback: number) {
 const required = rule.rule.value;
 const compliant = proposedSetback >= required;
 
 return {
 rule_id: rule.id,
 type: rule.rule.type,
 subtype: rule.rule.subtype,
 compliant,
 proposed_value: proposedSetback,
 required_value: required,
 gap: proposedSetback - required,
 source: {
 document: rule.document,
 section: rule.section,
 clause: rule.clause,
 url: rule.source_url
 },
 confidence: rule.confidence,
 mitigation: !compliant ? `Increase ${rule.rule.subtype} setback to ${required}m` : undefined
 };
 }

 private getSetbackValue(proposal: any, setbackType: string): number | undefined {
 switch (setbackType) {
 case "rear": return proposal.rear_setback;
 case "side": return proposal.side_setback;
 case "front": return proposal.front_setback;
 default: return undefined;
 }
 }

 /**
 * Get document references for manual review
 */
 getRequiredDocuments(propertyData: PropertyData, formerCouncilArea?: string) {
 const applicableRules = this.getApplicableRules(propertyData, formerCouncilArea);
 
 const documents = new Set([
 // Always include LEP for height/FSR
 `${propertyData.constraints.lga} LEP`
 ]);
 
 // Add DCP documents based on applicable rules
 applicableRules.forEach(rule => {
 documents.add(rule.document);
 });
 
 return Array.from(documents);
 }
}