/**
 * PART 2: Zone Translation Mapping
 *
 * NSW Employment Zones Reform (April 26, 2023) replaced Business/Industrial zones
 * with new Employment zones. This mapping allows queries using new zone codes
 * to find provisions tagged with legacy codes.
 *
 * Background:
 * - Documents extracted before 2023 use B1, B2, IN1, etc.
 * - NSW Planning Portal API returns E1, E2, E4, etc. (current codes)
 * - Database preserves original zone codes as written in documents
 * - Query-time translation bridges the gap
 *
 * The mapping itself is NOT authored here — it's loaded from
 * shared/zone-taxonomy.json (generated by scripts/generate_zone_taxonomy.py),
 * the single source shared with the Python side
 * (enrichment/config/zone_taxonomy.py). See DQ-30 in
 * .claude/DATA_QUALITY_TRACKER.md: this file previously hardcoded its own
 * copy, and that copy had real mapping errors (B4 wrongly under E2 instead of
 * MU1, IN1/IN4 wrongly under E4 instead of IN1/IN2, IN2 wrongly under E5
 * instead of E4) that a second, independent hardcode elsewhere could never
 * have caught. Edit shared/zone-taxonomy.json's source
 * (scripts/generate_zone_taxonomy.py) to change the mapping, not this file.
 */
import zoneTaxonomy from '../shared/zone-taxonomy.json';

/**
 * Zone translation mapping: Current zone → [Current + Legacy equivalents]
 */
export const ZONE_TRANSLATION_MAP: Record<string, string[]> = zoneTaxonomy.legacyToCurrentAliases;

/**
 * Legacy zone codes (pre-April 2023)
 * These should only appear in database, never in API requests
 */
export const LEGACY_ZONES: string[] = zoneTaxonomy.legacyZones;

/**
 * Get zone aliases for a given zone code
 * Returns array including both current and legacy equivalents
 *
 * @param zone - The zone code from API request (should be current code like E1)
 * @returns Array of zone codes to search ([current, ...legacy])
 *
 * @example
 * getZoneAliases('E1') // Returns ['E1', 'B1', 'B2']
 * getZoneAliases('R2') // Returns ['R2'] (no legacy equivalent)
 * getZoneAliases('B1') // Returns ['E1', 'B1', 'B2'] (translates legacy to current)
 */
export function getZoneAliases(zone: string): string[] {
  // If zone is already in translation map, return its aliases
  if (zone in ZONE_TRANSLATION_MAP) {
    return ZONE_TRANSLATION_MAP[zone];
  }

  // If zone is a legacy code, find its current equivalent
  if (LEGACY_ZONES.includes(zone)) {
    // Find which current zone this legacy zone maps to
    for (const [currentZone, aliases] of Object.entries(ZONE_TRANSLATION_MAP)) {
      if (aliases.includes(zone)) {
        return aliases; // Return full alias list including current zone
      }
    }
  }

  // Unknown zone - return as-is (will search only that zone)
  return [zone];
}

/**
 * Build SQL IN clause for zone search
 *
 * @param zone - The zone code to search for
 * @param parameterIndex - Starting index for SQL parameters (e.g., $1, $2, $3)
 * @returns Object with SQL fragment and parameter values
 *
 * @example
 * buildZoneInClause('E1', 1)
 * // Returns: { sql: 'zone IN ($1, $2, $3)', params: ['E1', 'B1', 'B2'] }
 */
export function buildZoneInClause(zone: string, parameterIndex: number = 1): {
  sql: string;
  params: string[];
} {
  const aliases = getZoneAliases(zone);
  const placeholders = aliases.map((_, i) => `$${parameterIndex + i}`).join(', ');

  return {
    sql: `zone IN (${placeholders})`,
    params: aliases
  };
}

/**
 * Check if a zone code is legacy (pre-April 2023)
 *
 * @param zone - Zone code to check
 * @returns true if zone is a legacy code
 */
export function isLegacyZone(zone: string): boolean {
  return LEGACY_ZONES.includes(zone);
}

/**
 * Get current zone equivalent for a legacy zone
 *
 * @param legacyZone - Legacy zone code (e.g., 'B1')
 * @returns Current zone code (e.g., 'E1') or null if not found
 *
 * @example
 * getCurrentZone('B1') // Returns 'E1'
 * getCurrentZone('IN1') // Returns 'E4'
 */
export function getCurrentZone(legacyZone: string): string | null {
  for (const [currentZone, aliases] of Object.entries(ZONE_TRANSLATION_MAP)) {
    if (aliases.includes(legacyZone) && currentZone !== legacyZone) {
      return currentZone;
    }
  }
  return null;
}
